// Code generated by consolidation generator. DO NOT EDIT manually.
// This file extends the base Client with organized sub-client access patterns.

package api

import "context"

// ClientExt wraps the base Client and adds organized sub-client methods for all 139 API operations.
type ClientExt struct {
	*Client
	apiTokens *ApiTokensClient
	auth *AuthClient
	configProfile *ConfigProfileClient
	externalSquad *ExternalSquadClient
	hosts *HostsClient
	hostsBulkActions *HostsBulkActionsClient
	hwidUserDevices *HwidUserDevicesClient
	infraBilling *InfraBillingClient
	internalSquad *InternalSquadClient
	keygen *KeygenClient
	nodes *NodesClient
	nodesUsageHistory *NodesUsageHistoryClient
	nodesUserUsageHistory *NodesUserUsageHistoryClient
	passkey *PasskeyClient
	remnawaveSettings *RemnawaveSettingsClient
	snippets *SnippetsClient
	subscription *SubscriptionClient
	subscriptionSettings *SubscriptionSettingsClient
	subscriptionTemplate *SubscriptionTemplateClient
	subscriptions *SubscriptionsClient
	system *SystemClient
	userSubscriptionRequestHistory *UserSubscriptionRequestHistoryClient
	users *UsersClient
	usersBulkActions *UsersBulkActionsClient
	usersStats *UsersStatsClient

}

// NewClientExt wraps an existing Client with sub-client access.
func NewClientExt(client *Client) *ClientExt {
	return &ClientExt{
		Client: client,
		apiTokens: NewApiTokensClient(client),
		auth: NewAuthClient(client),
		configProfile: NewConfigProfileClient(client),
		externalSquad: NewExternalSquadClient(client),
		hosts: NewHostsClient(client),
		hostsBulkActions: NewHostsBulkActionsClient(client),
		hwidUserDevices: NewHwidUserDevicesClient(client),
		infraBilling: NewInfraBillingClient(client),
		internalSquad: NewInternalSquadClient(client),
		keygen: NewKeygenClient(client),
		nodes: NewNodesClient(client),
		nodesUsageHistory: NewNodesUsageHistoryClient(client),
		nodesUserUsageHistory: NewNodesUserUsageHistoryClient(client),
		passkey: NewPasskeyClient(client),
		remnawaveSettings: NewRemnawaveSettingsClient(client),
		snippets: NewSnippetsClient(client),
		subscription: NewSubscriptionClient(client),
		subscriptionSettings: NewSubscriptionSettingsClient(client),
		subscriptionTemplate: NewSubscriptionTemplateClient(client),
		subscriptions: NewSubscriptionsClient(client),
		system: NewSystemClient(client),
		userSubscriptionRequestHistory: NewUserSubscriptionRequestHistoryClient(client),
		users: NewUsersClient(client),
		usersBulkActions: NewUsersBulkActionsClient(client),
		usersStats: NewUsersStatsClient(client),
	}
}

// ApiTokens returns the ApiTokensClient for ApiTokens operations.
func (ce *ClientExt) ApiTokens() *ApiTokensClient {
	return ce.apiTokens
}

// Auth returns the AuthClient for Auth operations.
func (ce *ClientExt) Auth() *AuthClient {
	return ce.auth
}

// ConfigProfile returns the ConfigProfileClient for ConfigProfile operations.
func (ce *ClientExt) ConfigProfile() *ConfigProfileClient {
	return ce.configProfile
}

// ExternalSquad returns the ExternalSquadClient for ExternalSquad operations.
func (ce *ClientExt) ExternalSquad() *ExternalSquadClient {
	return ce.externalSquad
}

// Hosts returns the HostsClient for Hosts operations.
func (ce *ClientExt) Hosts() *HostsClient {
	return ce.hosts
}

// HostsBulkActions returns the HostsBulkActionsClient for HostsBulkActions operations.
func (ce *ClientExt) HostsBulkActions() *HostsBulkActionsClient {
	return ce.hostsBulkActions
}

// HwidUserDevices returns the HwidUserDevicesClient for HwidUserDevices operations.
func (ce *ClientExt) HwidUserDevices() *HwidUserDevicesClient {
	return ce.hwidUserDevices
}

// InfraBilling returns the InfraBillingClient for InfraBilling operations.
func (ce *ClientExt) InfraBilling() *InfraBillingClient {
	return ce.infraBilling
}

// InternalSquad returns the InternalSquadClient for InternalSquad operations.
func (ce *ClientExt) InternalSquad() *InternalSquadClient {
	return ce.internalSquad
}

// Keygen returns the KeygenClient for Keygen operations.
func (ce *ClientExt) Keygen() *KeygenClient {
	return ce.keygen
}

// Nodes returns the NodesClient for Nodes operations.
func (ce *ClientExt) Nodes() *NodesClient {
	return ce.nodes
}

// NodesUsageHistory returns the NodesUsageHistoryClient for NodesUsageHistory operations.
func (ce *ClientExt) NodesUsageHistory() *NodesUsageHistoryClient {
	return ce.nodesUsageHistory
}

// NodesUserUsageHistory returns the NodesUserUsageHistoryClient for NodesUserUsageHistory operations.
func (ce *ClientExt) NodesUserUsageHistory() *NodesUserUsageHistoryClient {
	return ce.nodesUserUsageHistory
}

// Passkey returns the PasskeyClient for Passkey operations.
func (ce *ClientExt) Passkey() *PasskeyClient {
	return ce.passkey
}

// RemnawaveSettings returns the RemnawaveSettingsClient for RemnawaveSettings operations.
func (ce *ClientExt) RemnawaveSettings() *RemnawaveSettingsClient {
	return ce.remnawaveSettings
}

// Snippets returns the SnippetsClient for Snippets operations.
func (ce *ClientExt) Snippets() *SnippetsClient {
	return ce.snippets
}

// Subscription returns the SubscriptionClient for Subscription operations.
func (ce *ClientExt) Subscription() *SubscriptionClient {
	return ce.subscription
}

// SubscriptionSettings returns the SubscriptionSettingsClient for SubscriptionSettings operations.
func (ce *ClientExt) SubscriptionSettings() *SubscriptionSettingsClient {
	return ce.subscriptionSettings
}

// SubscriptionTemplate returns the SubscriptionTemplateClient for SubscriptionTemplate operations.
func (ce *ClientExt) SubscriptionTemplate() *SubscriptionTemplateClient {
	return ce.subscriptionTemplate
}

// Subscriptions returns the SubscriptionsClient for Subscriptions operations.
func (ce *ClientExt) Subscriptions() *SubscriptionsClient {
	return ce.subscriptions
}

// System returns the SystemClient for System operations.
func (ce *ClientExt) System() *SystemClient {
	return ce.system
}

// UserSubscriptionRequestHistory returns the UserSubscriptionRequestHistoryClient for UserSubscriptionRequestHistory operations.
func (ce *ClientExt) UserSubscriptionRequestHistory() *UserSubscriptionRequestHistoryClient {
	return ce.userSubscriptionRequestHistory
}

// Users returns the UsersClient for Users operations.
func (ce *ClientExt) Users() *UsersClient {
	return ce.users
}

// UsersBulkActions returns the UsersBulkActionsClient for UsersBulkActions operations.
func (ce *ClientExt) UsersBulkActions() *UsersBulkActionsClient {
	return ce.usersBulkActions
}

// UsersStats returns the UsersStatsClient for UsersStats operations.
func (ce *ClientExt) UsersStats() *UsersStatsClient {
	return ce.usersStats
}

// ApiTokensClient provides methods for ApiTokens operations.
type ApiTokensClient struct {
	client *Client
}

// NewApiTokensClient creates a new ApiTokensClient.
func NewApiTokensClient(client *Client) *ApiTokensClient {
	return &ApiTokensClient{client: client}
}

// AuthClient provides methods for Auth operations.
type AuthClient struct {
	client *Client
}

// NewAuthClient creates a new AuthClient.
func NewAuthClient(client *Client) *AuthClient {
	return &AuthClient{client: client}
}

// ConfigProfileClient provides methods for ConfigProfile operations.
type ConfigProfileClient struct {
	client *Client
}

// NewConfigProfileClient creates a new ConfigProfileClient.
func NewConfigProfileClient(client *Client) *ConfigProfileClient {
	return &ConfigProfileClient{client: client}
}

// ExternalSquadClient provides methods for ExternalSquad operations.
type ExternalSquadClient struct {
	client *Client
}

// NewExternalSquadClient creates a new ExternalSquadClient.
func NewExternalSquadClient(client *Client) *ExternalSquadClient {
	return &ExternalSquadClient{client: client}
}

// HostsClient provides methods for Hosts operations.
type HostsClient struct {
	client *Client
}

// NewHostsClient creates a new HostsClient.
func NewHostsClient(client *Client) *HostsClient {
	return &HostsClient{client: client}
}

// HostsBulkActionsClient provides methods for HostsBulkActions operations.
type HostsBulkActionsClient struct {
	client *Client
}

// NewHostsBulkActionsClient creates a new HostsBulkActionsClient.
func NewHostsBulkActionsClient(client *Client) *HostsBulkActionsClient {
	return &HostsBulkActionsClient{client: client}
}

// HwidUserDevicesClient provides methods for HwidUserDevices operations.
type HwidUserDevicesClient struct {
	client *Client
}

// NewHwidUserDevicesClient creates a new HwidUserDevicesClient.
func NewHwidUserDevicesClient(client *Client) *HwidUserDevicesClient {
	return &HwidUserDevicesClient{client: client}
}

// InfraBillingClient provides methods for InfraBilling operations.
type InfraBillingClient struct {
	client *Client
}

// NewInfraBillingClient creates a new InfraBillingClient.
func NewInfraBillingClient(client *Client) *InfraBillingClient {
	return &InfraBillingClient{client: client}
}

// InternalSquadClient provides methods for InternalSquad operations.
type InternalSquadClient struct {
	client *Client
}

// NewInternalSquadClient creates a new InternalSquadClient.
func NewInternalSquadClient(client *Client) *InternalSquadClient {
	return &InternalSquadClient{client: client}
}

// KeygenClient provides methods for Keygen operations.
type KeygenClient struct {
	client *Client
}

// NewKeygenClient creates a new KeygenClient.
func NewKeygenClient(client *Client) *KeygenClient {
	return &KeygenClient{client: client}
}

// NodesClient provides methods for Nodes operations.
type NodesClient struct {
	client *Client
}

// NewNodesClient creates a new NodesClient.
func NewNodesClient(client *Client) *NodesClient {
	return &NodesClient{client: client}
}

// NodesUsageHistoryClient provides methods for NodesUsageHistory operations.
type NodesUsageHistoryClient struct {
	client *Client
}

// NewNodesUsageHistoryClient creates a new NodesUsageHistoryClient.
func NewNodesUsageHistoryClient(client *Client) *NodesUsageHistoryClient {
	return &NodesUsageHistoryClient{client: client}
}

// NodesUserUsageHistoryClient provides methods for NodesUserUsageHistory operations.
type NodesUserUsageHistoryClient struct {
	client *Client
}

// NewNodesUserUsageHistoryClient creates a new NodesUserUsageHistoryClient.
func NewNodesUserUsageHistoryClient(client *Client) *NodesUserUsageHistoryClient {
	return &NodesUserUsageHistoryClient{client: client}
}

// PasskeyClient provides methods for Passkey operations.
type PasskeyClient struct {
	client *Client
}

// NewPasskeyClient creates a new PasskeyClient.
func NewPasskeyClient(client *Client) *PasskeyClient {
	return &PasskeyClient{client: client}
}

// RemnawaveSettingsClient provides methods for RemnawaveSettings operations.
type RemnawaveSettingsClient struct {
	client *Client
}

// NewRemnawaveSettingsClient creates a new RemnawaveSettingsClient.
func NewRemnawaveSettingsClient(client *Client) *RemnawaveSettingsClient {
	return &RemnawaveSettingsClient{client: client}
}

// SnippetsClient provides methods for Snippets operations.
type SnippetsClient struct {
	client *Client
}

// NewSnippetsClient creates a new SnippetsClient.
func NewSnippetsClient(client *Client) *SnippetsClient {
	return &SnippetsClient{client: client}
}

// SubscriptionClient provides methods for Subscription operations.
type SubscriptionClient struct {
	client *Client
}

// NewSubscriptionClient creates a new SubscriptionClient.
func NewSubscriptionClient(client *Client) *SubscriptionClient {
	return &SubscriptionClient{client: client}
}

// SubscriptionSettingsClient provides methods for SubscriptionSettings operations.
type SubscriptionSettingsClient struct {
	client *Client
}

// NewSubscriptionSettingsClient creates a new SubscriptionSettingsClient.
func NewSubscriptionSettingsClient(client *Client) *SubscriptionSettingsClient {
	return &SubscriptionSettingsClient{client: client}
}

// SubscriptionTemplateClient provides methods for SubscriptionTemplate operations.
type SubscriptionTemplateClient struct {
	client *Client
}

// NewSubscriptionTemplateClient creates a new SubscriptionTemplateClient.
func NewSubscriptionTemplateClient(client *Client) *SubscriptionTemplateClient {
	return &SubscriptionTemplateClient{client: client}
}

// SubscriptionsClient provides methods for Subscriptions operations.
type SubscriptionsClient struct {
	client *Client
}

// NewSubscriptionsClient creates a new SubscriptionsClient.
func NewSubscriptionsClient(client *Client) *SubscriptionsClient {
	return &SubscriptionsClient{client: client}
}

// SystemClient provides methods for System operations.
type SystemClient struct {
	client *Client
}

// NewSystemClient creates a new SystemClient.
func NewSystemClient(client *Client) *SystemClient {
	return &SystemClient{client: client}
}

// UserSubscriptionRequestHistoryClient provides methods for UserSubscriptionRequestHistory operations.
type UserSubscriptionRequestHistoryClient struct {
	client *Client
}

// NewUserSubscriptionRequestHistoryClient creates a new UserSubscriptionRequestHistoryClient.
func NewUserSubscriptionRequestHistoryClient(client *Client) *UserSubscriptionRequestHistoryClient {
	return &UserSubscriptionRequestHistoryClient{client: client}
}

// UsersClient provides methods for Users operations.
type UsersClient struct {
	client *Client
}

// NewUsersClient creates a new UsersClient.
func NewUsersClient(client *Client) *UsersClient {
	return &UsersClient{client: client}
}

// UsersBulkActionsClient provides methods for UsersBulkActions operations.
type UsersBulkActionsClient struct {
	client *Client
}

// NewUsersBulkActionsClient creates a new UsersBulkActionsClient.
func NewUsersBulkActionsClient(client *Client) *UsersBulkActionsClient {
	return &UsersBulkActionsClient{client: client}
}

// UsersStatsClient provides methods for UsersStats operations.
type UsersStatsClient struct {
	client *Client
}

// NewUsersStatsClient creates a new UsersStatsClient.
func NewUsersStatsClient(client *Client) *UsersStatsClient {
	return &UsersStatsClient{client: client}
}

