// Code generated by pipeline.py. DO NOT EDIT manually.

package api

import "context"

// ClientExt wraps the base Client with organized sub-client access.
// Use controller methods (e.g., client.Users().GetByUuid()) to call API operations.
type ClientExt struct {
	client *Client
	apiTokens *ApiTokensClient
	auth *AuthClient
	bandwidthStatsNodes *BandwidthStatsNodesClient
	bandwidthStatsUsers *BandwidthStatsUsersClient
	configProfile *ConfigProfileClient
	externalSquad *ExternalSquadClient
	hosts *HostsClient
	hostsBulkActions *HostsBulkActionsClient
	hwidUserDevices *HwidUserDevicesClient
	infraBilling *InfraBillingClient
	internalSquad *InternalSquadClient
	keygen *KeygenClient
	nodes *NodesClient
	nodesUsageHistory *NodesUsageHistoryClient
	passkey *PasskeyClient
	remnawaveSettings *RemnawaveSettingsClient
	snippets *SnippetsClient
	subscription *SubscriptionClient
	subscriptionPageConfig *SubscriptionPageConfigClient
	subscriptionSettings *SubscriptionSettingsClient
	subscriptionTemplate *SubscriptionTemplateClient
	subscriptions *SubscriptionsClient
	system *SystemClient
	userSubscriptionRequestHistory *UserSubscriptionRequestHistoryClient
	users *UsersClient
	usersBulkActions *UsersBulkActionsClient
}

// NewClientExt creates a new ClientExt wrapper.
func NewClientExt(client *Client) *ClientExt {
	return &ClientExt{
		client: client,
		apiTokens: NewApiTokensClient(client),
		auth: NewAuthClient(client),
		bandwidthStatsNodes: NewBandwidthStatsNodesClient(client),
		bandwidthStatsUsers: NewBandwidthStatsUsersClient(client),
		configProfile: NewConfigProfileClient(client),
		externalSquad: NewExternalSquadClient(client),
		hosts: NewHostsClient(client),
		hostsBulkActions: NewHostsBulkActionsClient(client),
		hwidUserDevices: NewHwidUserDevicesClient(client),
		infraBilling: NewInfraBillingClient(client),
		internalSquad: NewInternalSquadClient(client),
		keygen: NewKeygenClient(client),
		nodes: NewNodesClient(client),
		nodesUsageHistory: NewNodesUsageHistoryClient(client),
		passkey: NewPasskeyClient(client),
		remnawaveSettings: NewRemnawaveSettingsClient(client),
		snippets: NewSnippetsClient(client),
		subscription: NewSubscriptionClient(client),
		subscriptionPageConfig: NewSubscriptionPageConfigClient(client),
		subscriptionSettings: NewSubscriptionSettingsClient(client),
		subscriptionTemplate: NewSubscriptionTemplateClient(client),
		subscriptions: NewSubscriptionsClient(client),
		system: NewSystemClient(client),
		userSubscriptionRequestHistory: NewUserSubscriptionRequestHistoryClient(client),
		users: NewUsersClient(client),
		usersBulkActions: NewUsersBulkActionsClient(client),
	}
}

// Client returns the underlying ogen Client.
func (ce *ClientExt) Client() *Client {
	return ce.client
}

// ApiTokens returns the ApiTokensClient.
func (ce *ClientExt) ApiTokens() *ApiTokensClient {
	return ce.apiTokens
}

// Auth returns the AuthClient.
func (ce *ClientExt) Auth() *AuthClient {
	return ce.auth
}

// BandwidthStatsNodes returns the BandwidthStatsNodesClient.
func (ce *ClientExt) BandwidthStatsNodes() *BandwidthStatsNodesClient {
	return ce.bandwidthStatsNodes
}

// BandwidthStatsUsers returns the BandwidthStatsUsersClient.
func (ce *ClientExt) BandwidthStatsUsers() *BandwidthStatsUsersClient {
	return ce.bandwidthStatsUsers
}

// ConfigProfile returns the ConfigProfileClient.
func (ce *ClientExt) ConfigProfile() *ConfigProfileClient {
	return ce.configProfile
}

// ExternalSquad returns the ExternalSquadClient.
func (ce *ClientExt) ExternalSquad() *ExternalSquadClient {
	return ce.externalSquad
}

// Hosts returns the HostsClient.
func (ce *ClientExt) Hosts() *HostsClient {
	return ce.hosts
}

// HostsBulkActions returns the HostsBulkActionsClient.
func (ce *ClientExt) HostsBulkActions() *HostsBulkActionsClient {
	return ce.hostsBulkActions
}

// HwidUserDevices returns the HwidUserDevicesClient.
func (ce *ClientExt) HwidUserDevices() *HwidUserDevicesClient {
	return ce.hwidUserDevices
}

// InfraBilling returns the InfraBillingClient.
func (ce *ClientExt) InfraBilling() *InfraBillingClient {
	return ce.infraBilling
}

// InternalSquad returns the InternalSquadClient.
func (ce *ClientExt) InternalSquad() *InternalSquadClient {
	return ce.internalSquad
}

// Keygen returns the KeygenClient.
func (ce *ClientExt) Keygen() *KeygenClient {
	return ce.keygen
}

// Nodes returns the NodesClient.
func (ce *ClientExt) Nodes() *NodesClient {
	return ce.nodes
}

// NodesUsageHistory returns the NodesUsageHistoryClient.
func (ce *ClientExt) NodesUsageHistory() *NodesUsageHistoryClient {
	return ce.nodesUsageHistory
}

// Passkey returns the PasskeyClient.
func (ce *ClientExt) Passkey() *PasskeyClient {
	return ce.passkey
}

// RemnawaveSettings returns the RemnawaveSettingsClient.
func (ce *ClientExt) RemnawaveSettings() *RemnawaveSettingsClient {
	return ce.remnawaveSettings
}

// Snippets returns the SnippetsClient.
func (ce *ClientExt) Snippets() *SnippetsClient {
	return ce.snippets
}

// Subscription returns the SubscriptionClient.
func (ce *ClientExt) Subscription() *SubscriptionClient {
	return ce.subscription
}

// SubscriptionPageConfig returns the SubscriptionPageConfigClient.
func (ce *ClientExt) SubscriptionPageConfig() *SubscriptionPageConfigClient {
	return ce.subscriptionPageConfig
}

// SubscriptionSettings returns the SubscriptionSettingsClient.
func (ce *ClientExt) SubscriptionSettings() *SubscriptionSettingsClient {
	return ce.subscriptionSettings
}

// SubscriptionTemplate returns the SubscriptionTemplateClient.
func (ce *ClientExt) SubscriptionTemplate() *SubscriptionTemplateClient {
	return ce.subscriptionTemplate
}

// Subscriptions returns the SubscriptionsClient.
func (ce *ClientExt) Subscriptions() *SubscriptionsClient {
	return ce.subscriptions
}

// System returns the SystemClient.
func (ce *ClientExt) System() *SystemClient {
	return ce.system
}

// UserSubscriptionRequestHistory returns the UserSubscriptionRequestHistoryClient.
func (ce *ClientExt) UserSubscriptionRequestHistory() *UserSubscriptionRequestHistoryClient {
	return ce.userSubscriptionRequestHistory
}

// Users returns the UsersClient.
func (ce *ClientExt) Users() *UsersClient {
	return ce.users
}

// UsersBulkActions returns the UsersBulkActionsClient.
func (ce *ClientExt) UsersBulkActions() *UsersBulkActionsClient {
	return ce.usersBulkActions
}

// ApiTokensClient provides ApiTokens operations.
type ApiTokensClient struct {
	client *Client
}

// NewApiTokensClient creates a new ApiTokensClient.
func NewApiTokensClient(client *Client) *ApiTokensClient {
	return &ApiTokensClient{client: client}
}

// Create calls ApiTokensController_create.
func (sc *ApiTokensClient) Create(ctx context.Context, request *CreateApiTokenRequestDto) (ApiTokensControllerCreateRes, error) {
	return sc.client.ApiTokensControllerCreate(ctx, request)
}

// Delete calls ApiTokensController_delete.
func (sc *ApiTokensClient) Delete(ctx context.Context, uuid string) (ApiTokensControllerDeleteRes, error) {
	return sc.client.ApiTokensControllerDelete(ctx, ApiTokensControllerDeleteParams{
		UUID: uuid,
	})
}

// FindAll calls ApiTokensController_findAll.
func (sc *ApiTokensClient) FindAll(ctx context.Context) (ApiTokensControllerFindAllRes, error) {
	return sc.client.ApiTokensControllerFindAll(ctx)
}

// AuthClient provides Auth operations.
type AuthClient struct {
	client *Client
}

// NewAuthClient creates a new AuthClient.
func NewAuthClient(client *Client) *AuthClient {
	return &AuthClient{client: client}
}

// GetStatus calls AuthController_getStatus.
func (sc *AuthClient) GetStatus(ctx context.Context) (AuthControllerGetStatusRes, error) {
	return sc.client.AuthControllerGetStatus(ctx)
}

// Login calls AuthController_login.
func (sc *AuthClient) Login(ctx context.Context, request *LoginRequestDto) (AuthControllerLoginRes, error) {
	return sc.client.AuthControllerLogin(ctx, request)
}

// Oauth2Authorize calls AuthController_oauth2Authorize.
func (sc *AuthClient) Oauth2Authorize(ctx context.Context, request *OAuth2AuthorizeRequestDto) (AuthControllerOauth2AuthorizeRes, error) {
	return sc.client.AuthControllerOauth2Authorize(ctx, request)
}

// Oauth2Callback calls AuthController_oauth2Callback.
func (sc *AuthClient) Oauth2Callback(ctx context.Context, request *OAuth2CallbackRequestDto) (AuthControllerOauth2CallbackRes, error) {
	return sc.client.AuthControllerOauth2Callback(ctx, request)
}

// PasskeyAuthenticationOptions calls AuthController_passkeyAuthenticationOptions.
func (sc *AuthClient) PasskeyAuthenticationOptions(ctx context.Context) (AuthControllerPasskeyAuthenticationOptionsRes, error) {
	return sc.client.AuthControllerPasskeyAuthenticationOptions(ctx)
}

// PasskeyAuthenticationVerify calls AuthController_passkeyAuthenticationVerify.
func (sc *AuthClient) PasskeyAuthenticationVerify(ctx context.Context, request *PasskeyOptions) (AuthControllerPasskeyAuthenticationVerifyRes, error) {
	return sc.client.AuthControllerPasskeyAuthenticationVerify(ctx, request)
}

// Register calls AuthController_register.
func (sc *AuthClient) Register(ctx context.Context, request *RegisterRequestDto) (AuthControllerRegisterRes, error) {
	return sc.client.AuthControllerRegister(ctx, request)
}

// TelegramCallback calls AuthController_telegramCallback.
func (sc *AuthClient) TelegramCallback(ctx context.Context, request *TelegramCallbackRequestDto) (AuthControllerTelegramCallbackRes, error) {
	return sc.client.AuthControllerTelegramCallback(ctx, request)
}

// BandwidthStatsNodesClient provides BandwidthStatsNodes operations.
type BandwidthStatsNodesClient struct {
	client *Client
}

// NewBandwidthStatsNodesClient creates a new BandwidthStatsNodesClient.
func NewBandwidthStatsNodesClient(client *Client) *BandwidthStatsNodesClient {
	return &BandwidthStatsNodesClient{client: client}
}

// GetNodeUserUsage calls BandwidthStatsNodesController_getNodeUserUsage.
func (sc *BandwidthStatsNodesClient) GetNodeUserUsage(ctx context.Context, params BandwidthStatsNodesControllerGetNodeUserUsageParams) (BandwidthStatsNodesControllerGetNodeUserUsageRes, error) {
	return sc.client.BandwidthStatsNodesControllerGetNodeUserUsage(ctx, params)
}

// GetNodesRealtimeUsage calls BandwidthStatsNodesController_getNodesRealtimeUsage.
func (sc *BandwidthStatsNodesClient) GetNodesRealtimeUsage(ctx context.Context) (BandwidthStatsNodesControllerGetNodesRealtimeUsageRes, error) {
	return sc.client.BandwidthStatsNodesControllerGetNodesRealtimeUsage(ctx)
}

// GetStatsNodeUsersUsage calls BandwidthStatsNodesController_getStatsNodeUsersUsage.
func (sc *BandwidthStatsNodesClient) GetStatsNodeUsersUsage(ctx context.Context, params BandwidthStatsNodesControllerGetStatsNodeUsersUsageParams) (BandwidthStatsNodesControllerGetStatsNodeUsersUsageRes, error) {
	return sc.client.BandwidthStatsNodesControllerGetStatsNodeUsersUsage(ctx, params)
}

// BandwidthStatsUsersClient provides BandwidthStatsUsers operations.
type BandwidthStatsUsersClient struct {
	client *Client
}

// NewBandwidthStatsUsersClient creates a new BandwidthStatsUsersClient.
func NewBandwidthStatsUsersClient(client *Client) *BandwidthStatsUsersClient {
	return &BandwidthStatsUsersClient{client: client}
}

// GetStatsNodesUsage calls BandwidthStatsUsersController_getStatsNodesUsage.
func (sc *BandwidthStatsUsersClient) GetStatsNodesUsage(ctx context.Context, params BandwidthStatsUsersControllerGetStatsNodesUsageParams) (BandwidthStatsUsersControllerGetStatsNodesUsageRes, error) {
	return sc.client.BandwidthStatsUsersControllerGetStatsNodesUsage(ctx, params)
}

// GetUserUsageByRange calls BandwidthStatsUsersController_getUserUsageByRange.
func (sc *BandwidthStatsUsersClient) GetUserUsageByRange(ctx context.Context, params BandwidthStatsUsersControllerGetUserUsageByRangeParams) (BandwidthStatsUsersControllerGetUserUsageByRangeRes, error) {
	return sc.client.BandwidthStatsUsersControllerGetUserUsageByRange(ctx, params)
}

// ConfigProfileClient provides ConfigProfile operations.
type ConfigProfileClient struct {
	client *Client
}

// NewConfigProfileClient creates a new ConfigProfileClient.
func NewConfigProfileClient(client *Client) *ConfigProfileClient {
	return &ConfigProfileClient{client: client}
}

// CreateConfigProfile calls ConfigProfileController_createConfigProfile.
func (sc *ConfigProfileClient) CreateConfigProfile(ctx context.Context, request *CreateConfigProfileRequestDto) (ConfigProfileControllerCreateConfigProfileRes, error) {
	return sc.client.ConfigProfileControllerCreateConfigProfile(ctx, request)
}

// DeleteConfigProfileByUuid calls ConfigProfileController_deleteConfigProfileByUuid.
func (sc *ConfigProfileClient) DeleteConfigProfileByUuid(ctx context.Context, uuid string) (ConfigProfileControllerDeleteConfigProfileByUuidRes, error) {
	return sc.client.ConfigProfileControllerDeleteConfigProfileByUuid(ctx, ConfigProfileControllerDeleteConfigProfileByUuidParams{
		UUID: uuid,
	})
}

// GetAllInbounds calls ConfigProfileController_getAllInbounds.
func (sc *ConfigProfileClient) GetAllInbounds(ctx context.Context) (ConfigProfileControllerGetAllInboundsRes, error) {
	return sc.client.ConfigProfileControllerGetAllInbounds(ctx)
}

// GetComputedConfigProfileByUuid calls ConfigProfileController_getComputedConfigProfileByUuid.
func (sc *ConfigProfileClient) GetComputedConfigProfileByUuid(ctx context.Context, uuid string) (ConfigProfileControllerGetComputedConfigProfileByUuidRes, error) {
	return sc.client.ConfigProfileControllerGetComputedConfigProfileByUuid(ctx, ConfigProfileControllerGetComputedConfigProfileByUuidParams{
		UUID: uuid,
	})
}

// GetConfigProfileByUuid calls ConfigProfileController_getConfigProfileByUuid.
func (sc *ConfigProfileClient) GetConfigProfileByUuid(ctx context.Context, uuid string) (ConfigProfileControllerGetConfigProfileByUuidRes, error) {
	return sc.client.ConfigProfileControllerGetConfigProfileByUuid(ctx, ConfigProfileControllerGetConfigProfileByUuidParams{
		UUID: uuid,
	})
}

// GetConfigProfiles calls ConfigProfileController_getConfigProfiles.
func (sc *ConfigProfileClient) GetConfigProfiles(ctx context.Context) (ConfigProfileControllerGetConfigProfilesRes, error) {
	return sc.client.ConfigProfileControllerGetConfigProfiles(ctx)
}

// GetInboundsByProfileUuid calls ConfigProfileController_getInboundsByProfileUuid.
func (sc *ConfigProfileClient) GetInboundsByProfileUuid(ctx context.Context, uuid string) (ConfigProfileControllerGetInboundsByProfileUuidRes, error) {
	return sc.client.ConfigProfileControllerGetInboundsByProfileUuid(ctx, ConfigProfileControllerGetInboundsByProfileUuidParams{
		UUID: uuid,
	})
}

// ReorderConfigProfiles calls ConfigProfileController_reorderConfigProfiles.
func (sc *ConfigProfileClient) ReorderConfigProfiles(ctx context.Context, request *ReorderRequest) (ConfigProfileControllerReorderConfigProfilesRes, error) {
	return sc.client.ConfigProfileControllerReorderConfigProfiles(ctx, request)
}

// UpdateConfigProfile calls ConfigProfileController_updateConfigProfile.
func (sc *ConfigProfileClient) UpdateConfigProfile(ctx context.Context, request *UpdateConfigProfileRequestDto) (ConfigProfileControllerUpdateConfigProfileRes, error) {
	return sc.client.ConfigProfileControllerUpdateConfigProfile(ctx, request)
}

// ExternalSquadClient provides ExternalSquad operations.
type ExternalSquadClient struct {
	client *Client
}

// NewExternalSquadClient creates a new ExternalSquadClient.
func NewExternalSquadClient(client *Client) *ExternalSquadClient {
	return &ExternalSquadClient{client: client}
}

// AddUsersToExternalSquad calls ExternalSquadController_addUsersToExternalSquad.
func (sc *ExternalSquadClient) AddUsersToExternalSquad(ctx context.Context, uuid string) (ExternalSquadControllerAddUsersToExternalSquadRes, error) {
	return sc.client.ExternalSquadControllerAddUsersToExternalSquad(ctx, ExternalSquadControllerAddUsersToExternalSquadParams{
		UUID: uuid,
	})
}

// CreateExternalSquad calls ExternalSquadController_createExternalSquad.
func (sc *ExternalSquadClient) CreateExternalSquad(ctx context.Context, request *CreateExternalSquadRequestDto) (ExternalSquadControllerCreateExternalSquadRes, error) {
	return sc.client.ExternalSquadControllerCreateExternalSquad(ctx, request)
}

// DeleteExternalSquad calls ExternalSquadController_deleteExternalSquad.
func (sc *ExternalSquadClient) DeleteExternalSquad(ctx context.Context, uuid string) (ExternalSquadControllerDeleteExternalSquadRes, error) {
	return sc.client.ExternalSquadControllerDeleteExternalSquad(ctx, ExternalSquadControllerDeleteExternalSquadParams{
		UUID: uuid,
	})
}

// GetExternalSquadByUuid calls ExternalSquadController_getExternalSquadByUuid.
func (sc *ExternalSquadClient) GetExternalSquadByUuid(ctx context.Context, uuid string) (ExternalSquadControllerGetExternalSquadByUuidRes, error) {
	return sc.client.ExternalSquadControllerGetExternalSquadByUuid(ctx, ExternalSquadControllerGetExternalSquadByUuidParams{
		UUID: uuid,
	})
}

// GetExternalSquads calls ExternalSquadController_getExternalSquads.
func (sc *ExternalSquadClient) GetExternalSquads(ctx context.Context) (ExternalSquadControllerGetExternalSquadsRes, error) {
	return sc.client.ExternalSquadControllerGetExternalSquads(ctx)
}

// RemoveUsersFromExternalSquad calls ExternalSquadController_removeUsersFromExternalSquad.
func (sc *ExternalSquadClient) RemoveUsersFromExternalSquad(ctx context.Context, uuid string) (ExternalSquadControllerRemoveUsersFromExternalSquadRes, error) {
	return sc.client.ExternalSquadControllerRemoveUsersFromExternalSquad(ctx, ExternalSquadControllerRemoveUsersFromExternalSquadParams{
		UUID: uuid,
	})
}

// ReorderExternalSquads calls ExternalSquadController_reorderExternalSquads.
func (sc *ExternalSquadClient) ReorderExternalSquads(ctx context.Context, request *ReorderRequest) (ExternalSquadControllerReorderExternalSquadsRes, error) {
	return sc.client.ExternalSquadControllerReorderExternalSquads(ctx, request)
}

// UpdateExternalSquad calls ExternalSquadController_updateExternalSquad.
func (sc *ExternalSquadClient) UpdateExternalSquad(ctx context.Context, request *UpdateExternalSquadRequestDto) (ExternalSquadControllerUpdateExternalSquadRes, error) {
	return sc.client.ExternalSquadControllerUpdateExternalSquad(ctx, request)
}

// HostsClient provides Hosts operations.
type HostsClient struct {
	client *Client
}

// NewHostsClient creates a new HostsClient.
func NewHostsClient(client *Client) *HostsClient {
	return &HostsClient{client: client}
}

// CreateHost calls HostsController_createHost.
func (sc *HostsClient) CreateHost(ctx context.Context, request *CreateHostRequestDto) (HostsControllerCreateHostRes, error) {
	return sc.client.HostsControllerCreateHost(ctx, request)
}

// DeleteHost calls HostsController_deleteHost.
func (sc *HostsClient) DeleteHost(ctx context.Context, uuid string) (HostsControllerDeleteHostRes, error) {
	return sc.client.HostsControllerDeleteHost(ctx, HostsControllerDeleteHostParams{
		UUID: uuid,
	})
}

// GetAllHostTags calls HostsController_getAllHostTags.
func (sc *HostsClient) GetAllHostTags(ctx context.Context) (HostsControllerGetAllHostTagsRes, error) {
	return sc.client.HostsControllerGetAllHostTags(ctx)
}

// GetAllHosts calls HostsController_getAllHosts.
func (sc *HostsClient) GetAllHosts(ctx context.Context) (HostsControllerGetAllHostsRes, error) {
	return sc.client.HostsControllerGetAllHosts(ctx)
}

// GetOneHost calls HostsController_getOneHost.
func (sc *HostsClient) GetOneHost(ctx context.Context, uuid string) (HostsControllerGetOneHostRes, error) {
	return sc.client.HostsControllerGetOneHost(ctx, HostsControllerGetOneHostParams{
		UUID: uuid,
	})
}

// ReorderHosts calls HostsController_reorderHosts.
func (sc *HostsClient) ReorderHosts(ctx context.Context, request *ReorderHostRequestDto) (HostsControllerReorderHostsRes, error) {
	return sc.client.HostsControllerReorderHosts(ctx, request)
}

// UpdateHost calls HostsController_updateHost.
func (sc *HostsClient) UpdateHost(ctx context.Context, request *UpdateHostRequestDto) (HostsControllerUpdateHostRes, error) {
	return sc.client.HostsControllerUpdateHost(ctx, request)
}

// HostsBulkActionsClient provides HostsBulkActions operations.
type HostsBulkActionsClient struct {
	client *Client
}

// NewHostsBulkActionsClient creates a new HostsBulkActionsClient.
func NewHostsBulkActionsClient(client *Client) *HostsBulkActionsClient {
	return &HostsBulkActionsClient{client: client}
}

// DeleteHosts calls HostsBulkActionsController_deleteHosts.
func (sc *HostsBulkActionsClient) DeleteHosts(ctx context.Context, request *BulkUuidsRequest2) (HostsBulkActionsControllerDeleteHostsRes, error) {
	return sc.client.HostsBulkActionsControllerDeleteHosts(ctx, request)
}

// DisableHosts calls HostsBulkActionsController_disableHosts.
func (sc *HostsBulkActionsClient) DisableHosts(ctx context.Context, request *BulkUuidsRequest2) (HostsBulkActionsControllerDisableHostsRes, error) {
	return sc.client.HostsBulkActionsControllerDisableHosts(ctx, request)
}

// EnableHosts calls HostsBulkActionsController_enableHosts.
func (sc *HostsBulkActionsClient) EnableHosts(ctx context.Context, request *BulkUuidsRequest2) (HostsBulkActionsControllerEnableHostsRes, error) {
	return sc.client.HostsBulkActionsControllerEnableHosts(ctx, request)
}

// SetInboundToHosts calls HostsBulkActionsController_setInboundToHosts.
func (sc *HostsBulkActionsClient) SetInboundToHosts(ctx context.Context, request *SetInboundToManyHostsRequestDto) (HostsBulkActionsControllerSetInboundToHostsRes, error) {
	return sc.client.HostsBulkActionsControllerSetInboundToHosts(ctx, request)
}

// SetPortToHosts calls HostsBulkActionsController_setPortToHosts.
func (sc *HostsBulkActionsClient) SetPortToHosts(ctx context.Context, request *SetPortToManyHostsRequestDto) (HostsBulkActionsControllerSetPortToHostsRes, error) {
	return sc.client.HostsBulkActionsControllerSetPortToHosts(ctx, request)
}

// HwidUserDevicesClient provides HwidUserDevices operations.
type HwidUserDevicesClient struct {
	client *Client
}

// NewHwidUserDevicesClient creates a new HwidUserDevicesClient.
func NewHwidUserDevicesClient(client *Client) *HwidUserDevicesClient {
	return &HwidUserDevicesClient{client: client}
}

// CreateUserHwidDevice calls HwidUserDevicesController_createUserHwidDevice.
func (sc *HwidUserDevicesClient) CreateUserHwidDevice(ctx context.Context, request *CreateUserHwidDeviceRequestDto) (HwidUserDevicesControllerCreateUserHwidDeviceRes, error) {
	return sc.client.HwidUserDevicesControllerCreateUserHwidDevice(ctx, request)
}

// DeleteAllUserHwidDevices calls HwidUserDevicesController_deleteAllUserHwidDevices.
func (sc *HwidUserDevicesClient) DeleteAllUserHwidDevices(ctx context.Context, request *DeleteAllUserHwidDevicesRequestDto) (HwidUserDevicesControllerDeleteAllUserHwidDevicesRes, error) {
	return sc.client.HwidUserDevicesControllerDeleteAllUserHwidDevices(ctx, request)
}

// DeleteUserHwidDevice calls HwidUserDevicesController_deleteUserHwidDevice.
func (sc *HwidUserDevicesClient) DeleteUserHwidDevice(ctx context.Context, request *DeleteUserHwidDeviceRequestDto) (HwidUserDevicesControllerDeleteUserHwidDeviceRes, error) {
	return sc.client.HwidUserDevicesControllerDeleteUserHwidDevice(ctx, request)
}

// GetAllUsers calls HwidUserDevicesController_getAllUsers.
func (sc *HwidUserDevicesClient) GetAllUsers(ctx context.Context, size float64, start float64) (HwidUserDevicesControllerGetAllUsersRes, error) {
	return sc.client.HwidUserDevicesControllerGetAllUsers(ctx, HwidUserDevicesControllerGetAllUsersParams{
		Size: NewOptFloat64(size),
		Start: NewOptFloat64(start),
	})
}

// GetHwidDevicesStats calls HwidUserDevicesController_getHwidDevicesStats.
func (sc *HwidUserDevicesClient) GetHwidDevicesStats(ctx context.Context) (HwidUserDevicesControllerGetHwidDevicesStatsRes, error) {
	return sc.client.HwidUserDevicesControllerGetHwidDevicesStats(ctx)
}

// GetTopUsersByHwidDevices calls HwidUserDevicesController_getTopUsersByHwidDevices.
func (sc *HwidUserDevicesClient) GetTopUsersByHwidDevices(ctx context.Context, size float64, start float64) (HwidUserDevicesControllerGetTopUsersByHwidDevicesRes, error) {
	return sc.client.HwidUserDevicesControllerGetTopUsersByHwidDevices(ctx, HwidUserDevicesControllerGetTopUsersByHwidDevicesParams{
		Size: NewOptFloat64(size),
		Start: NewOptFloat64(start),
	})
}

// GetUserHwidDevices calls HwidUserDevicesController_getUserHwidDevices.
func (sc *HwidUserDevicesClient) GetUserHwidDevices(ctx context.Context, useruuid string) (HwidUserDevicesControllerGetUserHwidDevicesRes, error) {
	return sc.client.HwidUserDevicesControllerGetUserHwidDevices(ctx, HwidUserDevicesControllerGetUserHwidDevicesParams{
		UserUuid: useruuid,
	})
}

// InfraBillingClient provides InfraBilling operations.
type InfraBillingClient struct {
	client *Client
}

// NewInfraBillingClient creates a new InfraBillingClient.
func NewInfraBillingClient(client *Client) *InfraBillingClient {
	return &InfraBillingClient{client: client}
}

// CreateInfraBillingHistoryRecord calls InfraBillingController_createInfraBillingHistoryRecord.
func (sc *InfraBillingClient) CreateInfraBillingHistoryRecord(ctx context.Context, request *CreateInfraBillingHistoryRecordRequestDto) (InfraBillingControllerCreateInfraBillingHistoryRecordRes, error) {
	return sc.client.InfraBillingControllerCreateInfraBillingHistoryRecord(ctx, request)
}

// CreateInfraBillingNode calls InfraBillingController_createInfraBillingNode.
func (sc *InfraBillingClient) CreateInfraBillingNode(ctx context.Context, request *CreateInfraBillingNodeRequestDto) (InfraBillingControllerCreateInfraBillingNodeRes, error) {
	return sc.client.InfraBillingControllerCreateInfraBillingNode(ctx, request)
}

// CreateInfraProvider calls InfraBillingController_createInfraProvider.
func (sc *InfraBillingClient) CreateInfraProvider(ctx context.Context, request *CreateInfraProviderRequestDto) (InfraBillingControllerCreateInfraProviderRes, error) {
	return sc.client.InfraBillingControllerCreateInfraProvider(ctx, request)
}

// DeleteInfraBillingHistoryRecordByUuid calls InfraBillingController_deleteInfraBillingHistoryRecordByUuid.
func (sc *InfraBillingClient) DeleteInfraBillingHistoryRecordByUuid(ctx context.Context, uuid string) (InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidRes, error) {
	return sc.client.InfraBillingControllerDeleteInfraBillingHistoryRecordByUuid(ctx, InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidParams{
		UUID: uuid,
	})
}

// DeleteInfraBillingNodeByUuid calls InfraBillingController_deleteInfraBillingNodeByUuid.
func (sc *InfraBillingClient) DeleteInfraBillingNodeByUuid(ctx context.Context, uuid string) (InfraBillingControllerDeleteInfraBillingNodeByUuidRes, error) {
	return sc.client.InfraBillingControllerDeleteInfraBillingNodeByUuid(ctx, InfraBillingControllerDeleteInfraBillingNodeByUuidParams{
		UUID: uuid,
	})
}

// DeleteInfraProviderByUuid calls InfraBillingController_deleteInfraProviderByUuid.
func (sc *InfraBillingClient) DeleteInfraProviderByUuid(ctx context.Context, uuid string) (InfraBillingControllerDeleteInfraProviderByUuidRes, error) {
	return sc.client.InfraBillingControllerDeleteInfraProviderByUuid(ctx, InfraBillingControllerDeleteInfraProviderByUuidParams{
		UUID: uuid,
	})
}

// GetBillingNodes calls InfraBillingController_getBillingNodes.
func (sc *InfraBillingClient) GetBillingNodes(ctx context.Context) (InfraBillingControllerGetBillingNodesRes, error) {
	return sc.client.InfraBillingControllerGetBillingNodes(ctx)
}

// GetInfraBillingHistoryRecords calls InfraBillingController_getInfraBillingHistoryRecords.
func (sc *InfraBillingClient) GetInfraBillingHistoryRecords(ctx context.Context) (InfraBillingControllerGetInfraBillingHistoryRecordsRes, error) {
	return sc.client.InfraBillingControllerGetInfraBillingHistoryRecords(ctx)
}

// GetInfraProviderByUuid calls InfraBillingController_getInfraProviderByUuid.
func (sc *InfraBillingClient) GetInfraProviderByUuid(ctx context.Context, uuid string) (InfraBillingControllerGetInfraProviderByUuidRes, error) {
	return sc.client.InfraBillingControllerGetInfraProviderByUuid(ctx, InfraBillingControllerGetInfraProviderByUuidParams{
		UUID: uuid,
	})
}

// GetInfraProviders calls InfraBillingController_getInfraProviders.
func (sc *InfraBillingClient) GetInfraProviders(ctx context.Context) (InfraBillingControllerGetInfraProvidersRes, error) {
	return sc.client.InfraBillingControllerGetInfraProviders(ctx)
}

// UpdateInfraBillingNode calls InfraBillingController_updateInfraBillingNode.
func (sc *InfraBillingClient) UpdateInfraBillingNode(ctx context.Context, request *UpdateInfraBillingNodeRequestDto) (InfraBillingControllerUpdateInfraBillingNodeRes, error) {
	return sc.client.InfraBillingControllerUpdateInfraBillingNode(ctx, request)
}

// UpdateInfraProvider calls InfraBillingController_updateInfraProvider.
func (sc *InfraBillingClient) UpdateInfraProvider(ctx context.Context, request *UpdateInfraProviderRequestDto) (InfraBillingControllerUpdateInfraProviderRes, error) {
	return sc.client.InfraBillingControllerUpdateInfraProvider(ctx, request)
}

// InternalSquadClient provides InternalSquad operations.
type InternalSquadClient struct {
	client *Client
}

// NewInternalSquadClient creates a new InternalSquadClient.
func NewInternalSquadClient(client *Client) *InternalSquadClient {
	return &InternalSquadClient{client: client}
}

// AddUsersToInternalSquad calls InternalSquadController_addUsersToInternalSquad.
func (sc *InternalSquadClient) AddUsersToInternalSquad(ctx context.Context, uuid string) (InternalSquadControllerAddUsersToInternalSquadRes, error) {
	return sc.client.InternalSquadControllerAddUsersToInternalSquad(ctx, InternalSquadControllerAddUsersToInternalSquadParams{
		UUID: uuid,
	})
}

// CreateInternalSquad calls InternalSquadController_createInternalSquad.
func (sc *InternalSquadClient) CreateInternalSquad(ctx context.Context, request *CreateInternalSquadRequestDto) (InternalSquadControllerCreateInternalSquadRes, error) {
	return sc.client.InternalSquadControllerCreateInternalSquad(ctx, request)
}

// DeleteInternalSquad calls InternalSquadController_deleteInternalSquad.
func (sc *InternalSquadClient) DeleteInternalSquad(ctx context.Context, uuid string) (InternalSquadControllerDeleteInternalSquadRes, error) {
	return sc.client.InternalSquadControllerDeleteInternalSquad(ctx, InternalSquadControllerDeleteInternalSquadParams{
		UUID: uuid,
	})
}

// GetInternalSquadAccessibleNodes calls InternalSquadController_getInternalSquadAccessibleNodes.
func (sc *InternalSquadClient) GetInternalSquadAccessibleNodes(ctx context.Context, uuid string) (InternalSquadControllerGetInternalSquadAccessibleNodesRes, error) {
	return sc.client.InternalSquadControllerGetInternalSquadAccessibleNodes(ctx, InternalSquadControllerGetInternalSquadAccessibleNodesParams{
		UUID: uuid,
	})
}

// GetInternalSquadByUuid calls InternalSquadController_getInternalSquadByUuid.
func (sc *InternalSquadClient) GetInternalSquadByUuid(ctx context.Context, uuid string) (InternalSquadControllerGetInternalSquadByUuidRes, error) {
	return sc.client.InternalSquadControllerGetInternalSquadByUuid(ctx, InternalSquadControllerGetInternalSquadByUuidParams{
		UUID: uuid,
	})
}

// GetInternalSquads calls InternalSquadController_getInternalSquads.
func (sc *InternalSquadClient) GetInternalSquads(ctx context.Context) (InternalSquadControllerGetInternalSquadsRes, error) {
	return sc.client.InternalSquadControllerGetInternalSquads(ctx)
}

// RemoveUsersFromInternalSquad calls InternalSquadController_removeUsersFromInternalSquad.
func (sc *InternalSquadClient) RemoveUsersFromInternalSquad(ctx context.Context, uuid string) (InternalSquadControllerRemoveUsersFromInternalSquadRes, error) {
	return sc.client.InternalSquadControllerRemoveUsersFromInternalSquad(ctx, InternalSquadControllerRemoveUsersFromInternalSquadParams{
		UUID: uuid,
	})
}

// ReorderInternalSquads calls InternalSquadController_reorderInternalSquads.
func (sc *InternalSquadClient) ReorderInternalSquads(ctx context.Context, request *ReorderRequest) (InternalSquadControllerReorderInternalSquadsRes, error) {
	return sc.client.InternalSquadControllerReorderInternalSquads(ctx, request)
}

// UpdateInternalSquad calls InternalSquadController_updateInternalSquad.
func (sc *InternalSquadClient) UpdateInternalSquad(ctx context.Context, request *UpdateInternalSquadRequestDto) (InternalSquadControllerUpdateInternalSquadRes, error) {
	return sc.client.InternalSquadControllerUpdateInternalSquad(ctx, request)
}

// KeygenClient provides Keygen operations.
type KeygenClient struct {
	client *Client
}

// NewKeygenClient creates a new KeygenClient.
func NewKeygenClient(client *Client) *KeygenClient {
	return &KeygenClient{client: client}
}

// GenerateKey calls KeygenController_generateKey.
func (sc *KeygenClient) GenerateKey(ctx context.Context) (KeygenControllerGenerateKeyRes, error) {
	return sc.client.KeygenControllerGenerateKey(ctx)
}

// NodesClient provides Nodes operations.
type NodesClient struct {
	client *Client
}

// NewNodesClient creates a new NodesClient.
func NewNodesClient(client *Client) *NodesClient {
	return &NodesClient{client: client}
}

// BulkNodesActions calls NodesController_bulkNodesActions.
func (sc *NodesClient) BulkNodesActions(ctx context.Context, request *BulkNodesActionsRequestDto) (NodesControllerBulkNodesActionsRes, error) {
	return sc.client.NodesControllerBulkNodesActions(ctx, request)
}

// CreateNode calls NodesController_createNode.
func (sc *NodesClient) CreateNode(ctx context.Context, request *CreateNodeRequestDto) (NodesControllerCreateNodeRes, error) {
	return sc.client.NodesControllerCreateNode(ctx, request)
}

// DeleteNode calls NodesController_deleteNode.
func (sc *NodesClient) DeleteNode(ctx context.Context, uuid string) (NodesControllerDeleteNodeRes, error) {
	return sc.client.NodesControllerDeleteNode(ctx, NodesControllerDeleteNodeParams{
		UUID: uuid,
	})
}

// DisableNode calls NodesController_disableNode.
func (sc *NodesClient) DisableNode(ctx context.Context, uuid string) (NodesControllerDisableNodeRes, error) {
	return sc.client.NodesControllerDisableNode(ctx, NodesControllerDisableNodeParams{
		UUID: uuid,
	})
}

// EnableNode calls NodesController_enableNode.
func (sc *NodesClient) EnableNode(ctx context.Context, uuid string) (NodesControllerEnableNodeRes, error) {
	return sc.client.NodesControllerEnableNode(ctx, NodesControllerEnableNodeParams{
		UUID: uuid,
	})
}

// GetAllNodes calls NodesController_getAllNodes.
func (sc *NodesClient) GetAllNodes(ctx context.Context) (NodesControllerGetAllNodesRes, error) {
	return sc.client.NodesControllerGetAllNodes(ctx)
}

// GetAllNodesTags calls NodesController_getAllNodesTags.
func (sc *NodesClient) GetAllNodesTags(ctx context.Context) (NodesControllerGetAllNodesTagsRes, error) {
	return sc.client.NodesControllerGetAllNodesTags(ctx)
}

// GetOneNode calls NodesController_getOneNode.
func (sc *NodesClient) GetOneNode(ctx context.Context, uuid string) (NodesControllerGetOneNodeRes, error) {
	return sc.client.NodesControllerGetOneNode(ctx, NodesControllerGetOneNodeParams{
		UUID: uuid,
	})
}

// ProfileModification calls NodesController_profileModification.
func (sc *NodesClient) ProfileModification(ctx context.Context, request *ProfileModificationRequestDto) (NodesControllerProfileModificationRes, error) {
	return sc.client.NodesControllerProfileModification(ctx, request)
}

// ReorderNodes calls NodesController_reorderNodes.
func (sc *NodesClient) ReorderNodes(ctx context.Context, request *ReorderNodeRequestDto) (NodesControllerReorderNodesRes, error) {
	return sc.client.NodesControllerReorderNodes(ctx, request)
}

// ResetNodeTraffic calls NodesController_resetNodeTraffic.
func (sc *NodesClient) ResetNodeTraffic(ctx context.Context, uuid string) (NodesControllerResetNodeTrafficRes, error) {
	return sc.client.NodesControllerResetNodeTraffic(ctx, NodesControllerResetNodeTrafficParams{
		UUID: uuid,
	})
}

// RestartAllNodes calls NodesController_restartAllNodes.
func (sc *NodesClient) RestartAllNodes(ctx context.Context, request *RestartAllNodesRequestBodyDto) (NodesControllerRestartAllNodesRes, error) {
	return sc.client.NodesControllerRestartAllNodes(ctx, request)
}

// RestartNode calls NodesController_restartNode.
func (sc *NodesClient) RestartNode(ctx context.Context, uuid string) (NodesControllerRestartNodeRes, error) {
	return sc.client.NodesControllerRestartNode(ctx, NodesControllerRestartNodeParams{
		UUID: uuid,
	})
}

// UpdateNode calls NodesController_updateNode.
func (sc *NodesClient) UpdateNode(ctx context.Context, request *UpdateNodeRequestDto) (NodesControllerUpdateNodeRes, error) {
	return sc.client.NodesControllerUpdateNode(ctx, request)
}

// NodesUsageHistoryClient provides NodesUsageHistory operations.
type NodesUsageHistoryClient struct {
	client *Client
}

// NewNodesUsageHistoryClient creates a new NodesUsageHistoryClient.
func NewNodesUsageHistoryClient(client *Client) *NodesUsageHistoryClient {
	return &NodesUsageHistoryClient{client: client}
}

// GetStatsNodesUsage calls NodesUsageHistoryController_getStatsNodesUsage.
func (sc *NodesUsageHistoryClient) GetStatsNodesUsage(ctx context.Context, params NodesUsageHistoryControllerGetStatsNodesUsageParams) (NodesUsageHistoryControllerGetStatsNodesUsageRes, error) {
	return sc.client.NodesUsageHistoryControllerGetStatsNodesUsage(ctx, params)
}

// PasskeyClient provides Passkey operations.
type PasskeyClient struct {
	client *Client
}

// NewPasskeyClient creates a new PasskeyClient.
func NewPasskeyClient(client *Client) *PasskeyClient {
	return &PasskeyClient{client: client}
}

// DeletePasskey calls PasskeyController_deletePasskey.
func (sc *PasskeyClient) DeletePasskey(ctx context.Context, request *DeletePasskeyRequestDto) (PasskeyControllerDeletePasskeyRes, error) {
	return sc.client.PasskeyControllerDeletePasskey(ctx, request)
}

// GetActivePasskeys calls PasskeyController_getActivePasskeys.
func (sc *PasskeyClient) GetActivePasskeys(ctx context.Context) (PasskeyControllerGetActivePasskeysRes, error) {
	return sc.client.PasskeyControllerGetActivePasskeys(ctx)
}

// PasskeyRegistrationOptions calls PasskeyController_passkeyRegistrationOptions.
func (sc *PasskeyClient) PasskeyRegistrationOptions(ctx context.Context) (PasskeyControllerPasskeyRegistrationOptionsRes, error) {
	return sc.client.PasskeyControllerPasskeyRegistrationOptions(ctx)
}

// PasskeyRegistrationVerify calls PasskeyController_passkeyRegistrationVerify.
func (sc *PasskeyClient) PasskeyRegistrationVerify(ctx context.Context, request *PasskeyOptions) (PasskeyControllerPasskeyRegistrationVerifyRes, error) {
	return sc.client.PasskeyControllerPasskeyRegistrationVerify(ctx, request)
}

// UpdatePasskey calls PasskeyController_updatePasskey.
func (sc *PasskeyClient) UpdatePasskey(ctx context.Context, request *UpdatePasskeyRequestDto) (PasskeyControllerUpdatePasskeyRes, error) {
	return sc.client.PasskeyControllerUpdatePasskey(ctx, request)
}

// RemnawaveSettingsClient provides RemnawaveSettings operations.
type RemnawaveSettingsClient struct {
	client *Client
}

// NewRemnawaveSettingsClient creates a new RemnawaveSettingsClient.
func NewRemnawaveSettingsClient(client *Client) *RemnawaveSettingsClient {
	return &RemnawaveSettingsClient{client: client}
}

// GetSettings calls RemnawaveSettingsController_getSettings.
func (sc *RemnawaveSettingsClient) GetSettings(ctx context.Context) (RemnawaveSettingsControllerGetSettingsRes, error) {
	return sc.client.RemnawaveSettingsControllerGetSettings(ctx)
}

// UpdateSettings calls RemnawaveSettingsController_updateSettings.
func (sc *RemnawaveSettingsClient) UpdateSettings(ctx context.Context, request *UpdateRemnawaveSettingsRequestDto) (RemnawaveSettingsControllerUpdateSettingsRes, error) {
	return sc.client.RemnawaveSettingsControllerUpdateSettings(ctx, request)
}

// SnippetsClient provides Snippets operations.
type SnippetsClient struct {
	client *Client
}

// NewSnippetsClient creates a new SnippetsClient.
func NewSnippetsClient(client *Client) *SnippetsClient {
	return &SnippetsClient{client: client}
}

// CreateSnippet calls SnippetsController_createSnippet.
func (sc *SnippetsClient) CreateSnippet(ctx context.Context, request *SnippetRequest) (SnippetsControllerCreateSnippetRes, error) {
	return sc.client.SnippetsControllerCreateSnippet(ctx, request)
}

// DeleteSnippetByName calls SnippetsController_deleteSnippetByName.
func (sc *SnippetsClient) DeleteSnippetByName(ctx context.Context, request *DeleteSnippetRequestDto) (SnippetsControllerDeleteSnippetByNameRes, error) {
	return sc.client.SnippetsControllerDeleteSnippetByName(ctx, request)
}

// GetSnippets calls SnippetsController_getSnippets.
func (sc *SnippetsClient) GetSnippets(ctx context.Context) (SnippetsControllerGetSnippetsRes, error) {
	return sc.client.SnippetsControllerGetSnippets(ctx)
}

// UpdateSnippet calls SnippetsController_updateSnippet.
func (sc *SnippetsClient) UpdateSnippet(ctx context.Context, request *SnippetRequest) (SnippetsControllerUpdateSnippetRes, error) {
	return sc.client.SnippetsControllerUpdateSnippet(ctx, request)
}

// SubscriptionClient provides Subscription operations.
type SubscriptionClient struct {
	client *Client
}

// NewSubscriptionClient creates a new SubscriptionClient.
func NewSubscriptionClient(client *Client) *SubscriptionClient {
	return &SubscriptionClient{client: client}
}

// GetSubscription calls SubscriptionController_getSubscription.
func (sc *SubscriptionClient) GetSubscription(ctx context.Context, shortuuid string) (SubscriptionControllerGetSubscriptionOK, error) {
	return sc.client.SubscriptionControllerGetSubscription(ctx, SubscriptionControllerGetSubscriptionParams{
		ShortUuid: shortuuid,
	})
}

// GetSubscriptionByClientType calls SubscriptionController_getSubscriptionByClientType.
func (sc *SubscriptionClient) GetSubscriptionByClientType(ctx context.Context, params SubscriptionControllerGetSubscriptionByClientTypeParams) (SubscriptionControllerGetSubscriptionByClientTypeOK, error) {
	return sc.client.SubscriptionControllerGetSubscriptionByClientType(ctx, params)
}

// GetSubscriptionInfoByShortUuid calls SubscriptionController_getSubscriptionInfoByShortUuid.
func (sc *SubscriptionClient) GetSubscriptionInfoByShortUuid(ctx context.Context, shortuuid string) (SubscriptionControllerGetSubscriptionInfoByShortUuidRes, error) {
	return sc.client.SubscriptionControllerGetSubscriptionInfoByShortUuid(ctx, SubscriptionControllerGetSubscriptionInfoByShortUuidParams{
		ShortUuid: shortuuid,
	})
}

// GetSubscriptionWithType calls SubscriptionController_getSubscriptionWithType.
func (sc *SubscriptionClient) GetSubscriptionWithType(ctx context.Context, typeVal string, encodedtag string, shortuuid string) (SubscriptionControllerGetSubscriptionWithTypeOK, error) {
	return sc.client.SubscriptionControllerGetSubscriptionWithType(ctx, SubscriptionControllerGetSubscriptionWithTypeParams{
		Type: typeVal,
		EncodedTag: encodedtag,
		ShortUuid: shortuuid,
	})
}

// SubscriptionPageConfigClient provides SubscriptionPageConfig operations.
type SubscriptionPageConfigClient struct {
	client *Client
}

// NewSubscriptionPageConfigClient creates a new SubscriptionPageConfigClient.
func NewSubscriptionPageConfigClient(client *Client) *SubscriptionPageConfigClient {
	return &SubscriptionPageConfigClient{client: client}
}

// CloneSubscriptionPageConfig calls SubscriptionPageConfigController_cloneSubscriptionPageConfig.
func (sc *SubscriptionPageConfigClient) CloneSubscriptionPageConfig(ctx context.Context, request *CloneSubscriptionPageConfigRequestDto) (SubscriptionPageConfigControllerCloneSubscriptionPageConfigRes, error) {
	return sc.client.SubscriptionPageConfigControllerCloneSubscriptionPageConfig(ctx, request)
}

// CreateConfig calls SubscriptionPageConfigController_createConfig.
func (sc *SubscriptionPageConfigClient) CreateConfig(ctx context.Context, request *CreateSubscriptionPageConfigRequestDto) (SubscriptionPageConfigControllerCreateConfigRes, error) {
	return sc.client.SubscriptionPageConfigControllerCreateConfig(ctx, request)
}

// DeleteConfig calls SubscriptionPageConfigController_deleteConfig.
func (sc *SubscriptionPageConfigClient) DeleteConfig(ctx context.Context, uuid string) (SubscriptionPageConfigControllerDeleteConfigRes, error) {
	return sc.client.SubscriptionPageConfigControllerDeleteConfig(ctx, SubscriptionPageConfigControllerDeleteConfigParams{
		UUID: uuid,
	})
}

// GetAllConfigs calls SubscriptionPageConfigController_getAllConfigs.
func (sc *SubscriptionPageConfigClient) GetAllConfigs(ctx context.Context) (SubscriptionPageConfigControllerGetAllConfigsRes, error) {
	return sc.client.SubscriptionPageConfigControllerGetAllConfigs(ctx)
}

// GetConfigByUuid calls SubscriptionPageConfigController_getConfigByUuid.
func (sc *SubscriptionPageConfigClient) GetConfigByUuid(ctx context.Context, uuid string) (SubscriptionPageConfigControllerGetConfigByUuidRes, error) {
	return sc.client.SubscriptionPageConfigControllerGetConfigByUuid(ctx, SubscriptionPageConfigControllerGetConfigByUuidParams{
		UUID: uuid,
	})
}

// ReorderSubscriptionPageConfigs calls SubscriptionPageConfigController_reorderSubscriptionPageConfigs.
func (sc *SubscriptionPageConfigClient) ReorderSubscriptionPageConfigs(ctx context.Context, request *ReorderRequest) (SubscriptionPageConfigControllerReorderSubscriptionPageConfigsRes, error) {
	return sc.client.SubscriptionPageConfigControllerReorderSubscriptionPageConfigs(ctx, request)
}

// UpdateConfig calls SubscriptionPageConfigController_updateConfig.
func (sc *SubscriptionPageConfigClient) UpdateConfig(ctx context.Context, request *UpdateSubscriptionPageConfigRequestDto) (SubscriptionPageConfigControllerUpdateConfigRes, error) {
	return sc.client.SubscriptionPageConfigControllerUpdateConfig(ctx, request)
}

// SubscriptionSettingsClient provides SubscriptionSettings operations.
type SubscriptionSettingsClient struct {
	client *Client
}

// NewSubscriptionSettingsClient creates a new SubscriptionSettingsClient.
func NewSubscriptionSettingsClient(client *Client) *SubscriptionSettingsClient {
	return &SubscriptionSettingsClient{client: client}
}

// GetSettings calls SubscriptionSettingsController_getSettings.
func (sc *SubscriptionSettingsClient) GetSettings(ctx context.Context) (SubscriptionSettingsControllerGetSettingsRes, error) {
	return sc.client.SubscriptionSettingsControllerGetSettings(ctx)
}

// UpdateSettings calls SubscriptionSettingsController_updateSettings.
func (sc *SubscriptionSettingsClient) UpdateSettings(ctx context.Context, request *UpdateSubscriptionSettingsRequestDto) (SubscriptionSettingsControllerUpdateSettingsRes, error) {
	return sc.client.SubscriptionSettingsControllerUpdateSettings(ctx, request)
}

// SubscriptionTemplateClient provides SubscriptionTemplate operations.
type SubscriptionTemplateClient struct {
	client *Client
}

// NewSubscriptionTemplateClient creates a new SubscriptionTemplateClient.
func NewSubscriptionTemplateClient(client *Client) *SubscriptionTemplateClient {
	return &SubscriptionTemplateClient{client: client}
}

// CreateTemplate calls SubscriptionTemplateController_createTemplate.
func (sc *SubscriptionTemplateClient) CreateTemplate(ctx context.Context, request *CreateSubscriptionTemplateRequestDto) (SubscriptionTemplateControllerCreateTemplateRes, error) {
	return sc.client.SubscriptionTemplateControllerCreateTemplate(ctx, request)
}

// DeleteTemplate calls SubscriptionTemplateController_deleteTemplate.
func (sc *SubscriptionTemplateClient) DeleteTemplate(ctx context.Context, uuid string) (SubscriptionTemplateControllerDeleteTemplateRes, error) {
	return sc.client.SubscriptionTemplateControllerDeleteTemplate(ctx, SubscriptionTemplateControllerDeleteTemplateParams{
		UUID: uuid,
	})
}

// GetAllTemplates calls SubscriptionTemplateController_getAllTemplates.
func (sc *SubscriptionTemplateClient) GetAllTemplates(ctx context.Context) (SubscriptionTemplateControllerGetAllTemplatesRes, error) {
	return sc.client.SubscriptionTemplateControllerGetAllTemplates(ctx)
}

// GetTemplateByUuid calls SubscriptionTemplateController_getTemplateByUuid.
func (sc *SubscriptionTemplateClient) GetTemplateByUuid(ctx context.Context, uuid string) (SubscriptionTemplateControllerGetTemplateByUuidRes, error) {
	return sc.client.SubscriptionTemplateControllerGetTemplateByUuid(ctx, SubscriptionTemplateControllerGetTemplateByUuidParams{
		UUID: uuid,
	})
}

// ReorderSubscriptionTemplates calls SubscriptionTemplateController_reorderSubscriptionTemplates.
func (sc *SubscriptionTemplateClient) ReorderSubscriptionTemplates(ctx context.Context, request *ReorderRequest) (SubscriptionTemplateControllerReorderSubscriptionTemplatesRes, error) {
	return sc.client.SubscriptionTemplateControllerReorderSubscriptionTemplates(ctx, request)
}

// UpdateTemplate calls SubscriptionTemplateController_updateTemplate.
func (sc *SubscriptionTemplateClient) UpdateTemplate(ctx context.Context, request *UpdateTemplateRequestDto) (SubscriptionTemplateControllerUpdateTemplateRes, error) {
	return sc.client.SubscriptionTemplateControllerUpdateTemplate(ctx, request)
}

// SubscriptionsClient provides Subscriptions operations.
type SubscriptionsClient struct {
	client *Client
}

// NewSubscriptionsClient creates a new SubscriptionsClient.
func NewSubscriptionsClient(client *Client) *SubscriptionsClient {
	return &SubscriptionsClient{client: client}
}

// GetAllSubscriptions calls SubscriptionsController_getAllSubscriptions.
func (sc *SubscriptionsClient) GetAllSubscriptions(ctx context.Context, size float64, start float64) (SubscriptionsControllerGetAllSubscriptionsRes, error) {
	return sc.client.SubscriptionsControllerGetAllSubscriptions(ctx, SubscriptionsControllerGetAllSubscriptionsParams{
		Size: NewOptFloat64(size),
		Start: NewOptFloat64(start),
	})
}

// GetRawSubscriptionByShortUuid calls SubscriptionsController_getRawSubscriptionByShortUuid.
func (sc *SubscriptionsClient) GetRawSubscriptionByShortUuid(ctx context.Context, withdisabledhosts bool, shortuuid string) (SubscriptionsControllerGetRawSubscriptionByShortUuidRes, error) {
	return sc.client.SubscriptionsControllerGetRawSubscriptionByShortUuid(ctx, SubscriptionsControllerGetRawSubscriptionByShortUuidParams{
		WithDisabledHosts: NewOptBool(withdisabledhosts),
		ShortUuid: shortuuid,
	})
}

// GetSubpageConfigByShortUuid calls SubscriptionsController_getSubpageConfigByShortUuid.
func (sc *SubscriptionsClient) GetSubpageConfigByShortUuid(ctx context.Context, request *GetSubpageConfigByShortUuidRequestBodyDto, shortuuid string) (SubscriptionsControllerGetSubpageConfigByShortUuidRes, error) {
	return sc.client.SubscriptionsControllerGetSubpageConfigByShortUuid(ctx, request, SubscriptionsControllerGetSubpageConfigByShortUuidParams{
		ShortUuid: shortuuid,
	})
}

// GetSubscriptionByShortUuidProtected calls SubscriptionsController_getSubscriptionByShortUuidProtected.
func (sc *SubscriptionsClient) GetSubscriptionByShortUuidProtected(ctx context.Context, shortuuid string) (SubscriptionsControllerGetSubscriptionByShortUuidProtectedRes, error) {
	return sc.client.SubscriptionsControllerGetSubscriptionByShortUuidProtected(ctx, SubscriptionsControllerGetSubscriptionByShortUuidProtectedParams{
		ShortUuid: shortuuid,
	})
}

// GetSubscriptionByUsername calls SubscriptionsController_getSubscriptionByUsername.
func (sc *SubscriptionsClient) GetSubscriptionByUsername(ctx context.Context, username string) (SubscriptionsControllerGetSubscriptionByUsernameRes, error) {
	return sc.client.SubscriptionsControllerGetSubscriptionByUsername(ctx, SubscriptionsControllerGetSubscriptionByUsernameParams{
		Username: username,
	})
}

// GetSubscriptionByUuid calls SubscriptionsController_getSubscriptionByUuid.
func (sc *SubscriptionsClient) GetSubscriptionByUuid(ctx context.Context, uuid string) (SubscriptionsControllerGetSubscriptionByUuidRes, error) {
	return sc.client.SubscriptionsControllerGetSubscriptionByUuid(ctx, SubscriptionsControllerGetSubscriptionByUuidParams{
		UUID: uuid,
	})
}

// SystemClient provides System operations.
type SystemClient struct {
	client *Client
}

// NewSystemClient creates a new SystemClient.
func NewSystemClient(client *Client) *SystemClient {
	return &SystemClient{client: client}
}

// DebugSrrMatcher calls SystemController_debugSrrMatcher.
func (sc *SystemClient) DebugSrrMatcher(ctx context.Context, request *DebugSrrMatcherRequestDto) (SystemControllerDebugSrrMatcherRes, error) {
	return sc.client.SystemControllerDebugSrrMatcher(ctx, request)
}

// EncryptHappCryptoLink calls SystemController_encryptHappCryptoLink.
func (sc *SystemClient) EncryptHappCryptoLink(ctx context.Context, request *EncryptHappCryptoLinkRequestDto) (SystemControllerEncryptHappCryptoLinkRes, error) {
	return sc.client.SystemControllerEncryptHappCryptoLink(ctx, request)
}

// GetBandwidthStats calls SystemController_getBandwidthStats.
func (sc *SystemClient) GetBandwidthStats(ctx context.Context) (SystemControllerGetBandwidthStatsRes, error) {
	return sc.client.SystemControllerGetBandwidthStats(ctx)
}

// GetMetadata calls SystemController_getMetadata.
func (sc *SystemClient) GetMetadata(ctx context.Context) (SystemControllerGetMetadataRes, error) {
	return sc.client.SystemControllerGetMetadata(ctx)
}

// GetNodesMetrics calls SystemController_getNodesMetrics.
func (sc *SystemClient) GetNodesMetrics(ctx context.Context) (SystemControllerGetNodesMetricsRes, error) {
	return sc.client.SystemControllerGetNodesMetrics(ctx)
}

// GetNodesStatistics calls SystemController_getNodesStatistics.
func (sc *SystemClient) GetNodesStatistics(ctx context.Context) (SystemControllerGetNodesStatisticsRes, error) {
	return sc.client.SystemControllerGetNodesStatistics(ctx)
}

// GetRemnawaveHealth calls SystemController_getRemnawaveHealth.
func (sc *SystemClient) GetRemnawaveHealth(ctx context.Context) (SystemControllerGetRemnawaveHealthRes, error) {
	return sc.client.SystemControllerGetRemnawaveHealth(ctx)
}

// GetStats calls SystemController_getStats.
func (sc *SystemClient) GetStats(ctx context.Context) (SystemControllerGetStatsRes, error) {
	return sc.client.SystemControllerGetStats(ctx)
}

// GetX25519Keypairs calls SystemController_getX25519Keypairs.
func (sc *SystemClient) GetX25519Keypairs(ctx context.Context) (SystemControllerGetX25519KeypairsRes, error) {
	return sc.client.SystemControllerGetX25519Keypairs(ctx)
}

// UserSubscriptionRequestHistoryClient provides UserSubscriptionRequestHistory operations.
type UserSubscriptionRequestHistoryClient struct {
	client *Client
}

// NewUserSubscriptionRequestHistoryClient creates a new UserSubscriptionRequestHistoryClient.
func NewUserSubscriptionRequestHistoryClient(client *Client) *UserSubscriptionRequestHistoryClient {
	return &UserSubscriptionRequestHistoryClient{client: client}
}

// GetSubscriptionRequestHistory calls UserSubscriptionRequestHistoryController_getSubscriptionRequestHistory.
func (sc *UserSubscriptionRequestHistoryClient) GetSubscriptionRequestHistory(ctx context.Context, size float64, start float64) (UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryRes, error) {
	return sc.client.UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistory(ctx, UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryParams{
		Size: NewOptFloat64(size),
		Start: NewOptFloat64(start),
	})
}

// GetSubscriptionRequestHistoryStats calls UserSubscriptionRequestHistoryController_getSubscriptionRequestHistoryStats.
func (sc *UserSubscriptionRequestHistoryClient) GetSubscriptionRequestHistoryStats(ctx context.Context) (UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryStatsRes, error) {
	return sc.client.UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryStats(ctx)
}

// UsersClient provides Users operations.
type UsersClient struct {
	client *Client
}

// NewUsersClient creates a new UsersClient.
func NewUsersClient(client *Client) *UsersClient {
	return &UsersClient{client: client}
}

// CreateUser calls UsersController_createUser.
func (sc *UsersClient) CreateUser(ctx context.Context, request *CreateUserRequestDto) (UsersControllerCreateUserRes, error) {
	return sc.client.UsersControllerCreateUser(ctx, request)
}

// DeleteUser calls UsersController_deleteUser.
func (sc *UsersClient) DeleteUser(ctx context.Context, uuid string) (UsersControllerDeleteUserRes, error) {
	return sc.client.UsersControllerDeleteUser(ctx, UsersControllerDeleteUserParams{
		UUID: uuid,
	})
}

// DisableUser calls UsersController_disableUser.
func (sc *UsersClient) DisableUser(ctx context.Context, uuid string) (UsersControllerDisableUserRes, error) {
	return sc.client.UsersControllerDisableUser(ctx, UsersControllerDisableUserParams{
		UUID: uuid,
	})
}

// EnableUser calls UsersController_enableUser.
func (sc *UsersClient) EnableUser(ctx context.Context, uuid string) (UsersControllerEnableUserRes, error) {
	return sc.client.UsersControllerEnableUser(ctx, UsersControllerEnableUserParams{
		UUID: uuid,
	})
}

// GetAllTags calls UsersController_getAllTags.
func (sc *UsersClient) GetAllTags(ctx context.Context) (UsersControllerGetAllTagsRes, error) {
	return sc.client.UsersControllerGetAllTags(ctx)
}

// GetAllUsers calls UsersController_getAllUsers.
func (sc *UsersClient) GetAllUsers(ctx context.Context, size float64, start float64) (UsersControllerGetAllUsersRes, error) {
	return sc.client.UsersControllerGetAllUsers(ctx, UsersControllerGetAllUsersParams{
		Size: NewOptFloat64(size),
		Start: NewOptFloat64(start),
	})
}

// GetUserAccessibleNodes calls UsersController_getUserAccessibleNodes.
func (sc *UsersClient) GetUserAccessibleNodes(ctx context.Context, uuid string) (UsersControllerGetUserAccessibleNodesRes, error) {
	return sc.client.UsersControllerGetUserAccessibleNodes(ctx, UsersControllerGetUserAccessibleNodesParams{
		UUID: uuid,
	})
}

// GetUserById calls UsersController_getUserById.
func (sc *UsersClient) GetUserById(ctx context.Context, id string) (UsersControllerGetUserByIdRes, error) {
	return sc.client.UsersControllerGetUserById(ctx, UsersControllerGetUserByIdParams{
		ID: id,
	})
}

// GetUserByShortUuid calls UsersController_getUserByShortUuid.
func (sc *UsersClient) GetUserByShortUuid(ctx context.Context, shortuuid string) (UsersControllerGetUserByShortUuidRes, error) {
	return sc.client.UsersControllerGetUserByShortUuid(ctx, UsersControllerGetUserByShortUuidParams{
		ShortUuid: shortuuid,
	})
}

// GetUserByTelegramId calls UsersController_getUserByTelegramId.
func (sc *UsersClient) GetUserByTelegramId(ctx context.Context, telegramid string) (UsersControllerGetUserByTelegramIdRes, error) {
	return sc.client.UsersControllerGetUserByTelegramId(ctx, UsersControllerGetUserByTelegramIdParams{
		TelegramId: telegramid,
	})
}

// GetUserByUsername calls UsersController_getUserByUsername.
func (sc *UsersClient) GetUserByUsername(ctx context.Context, username string) (UsersControllerGetUserByUsernameRes, error) {
	return sc.client.UsersControllerGetUserByUsername(ctx, UsersControllerGetUserByUsernameParams{
		Username: username,
	})
}

// GetUserByUuid calls UsersController_getUserByUuid.
func (sc *UsersClient) GetUserByUuid(ctx context.Context, uuid string) (UsersControllerGetUserByUuidRes, error) {
	return sc.client.UsersControllerGetUserByUuid(ctx, UsersControllerGetUserByUuidParams{
		UUID: uuid,
	})
}

// GetUserSubscriptionRequestHistory calls UsersController_getUserSubscriptionRequestHistory.
func (sc *UsersClient) GetUserSubscriptionRequestHistory(ctx context.Context, uuid string) (UsersControllerGetUserSubscriptionRequestHistoryRes, error) {
	return sc.client.UsersControllerGetUserSubscriptionRequestHistory(ctx, UsersControllerGetUserSubscriptionRequestHistoryParams{
		UUID: uuid,
	})
}

// GetUsersByEmail calls UsersController_getUsersByEmail.
func (sc *UsersClient) GetUsersByEmail(ctx context.Context, email string) (UsersControllerGetUsersByEmailRes, error) {
	return sc.client.UsersControllerGetUsersByEmail(ctx, UsersControllerGetUsersByEmailParams{
		Email: email,
	})
}

// GetUsersByTag calls UsersController_getUsersByTag.
func (sc *UsersClient) GetUsersByTag(ctx context.Context, tag string) (UsersControllerGetUsersByTagRes, error) {
	return sc.client.UsersControllerGetUsersByTag(ctx, UsersControllerGetUsersByTagParams{
		Tag: tag,
	})
}

// ResetUserTraffic calls UsersController_resetUserTraffic.
func (sc *UsersClient) ResetUserTraffic(ctx context.Context, uuid string) (UsersControllerResetUserTrafficRes, error) {
	return sc.client.UsersControllerResetUserTraffic(ctx, UsersControllerResetUserTrafficParams{
		UUID: uuid,
	})
}

// RevokeUserSubscription calls UsersController_revokeUserSubscription.
func (sc *UsersClient) RevokeUserSubscription(ctx context.Context, request *RevokeUserSubscriptionBodyDto, uuid string) (UsersControllerRevokeUserSubscriptionRes, error) {
	return sc.client.UsersControllerRevokeUserSubscription(ctx, request, UsersControllerRevokeUserSubscriptionParams{
		UUID: uuid,
	})
}

// UpdateUser calls UsersController_updateUser.
func (sc *UsersClient) UpdateUser(ctx context.Context, request *UpdateUserRequestDto) (UsersControllerUpdateUserRes, error) {
	return sc.client.UsersControllerUpdateUser(ctx, request)
}

// UsersBulkActionsClient provides UsersBulkActions operations.
type UsersBulkActionsClient struct {
	client *Client
}

// NewUsersBulkActionsClient creates a new UsersBulkActionsClient.
func NewUsersBulkActionsClient(client *Client) *UsersBulkActionsClient {
	return &UsersBulkActionsClient{client: client}
}

// BulkAllExtendExpirationDate calls UsersBulkActionsController_bulkAllExtendExpirationDate.
func (sc *UsersBulkActionsClient) BulkAllExtendExpirationDate(ctx context.Context, request *BulkAllExtendExpirationDateRequestDto) (UsersBulkActionsControllerBulkAllExtendExpirationDateRes, error) {
	return sc.client.UsersBulkActionsControllerBulkAllExtendExpirationDate(ctx, request)
}

// BulkAllResetUserTraffic calls UsersBulkActionsController_bulkAllResetUserTraffic.
func (sc *UsersBulkActionsClient) BulkAllResetUserTraffic(ctx context.Context) (UsersBulkActionsControllerBulkAllResetUserTrafficRes, error) {
	return sc.client.UsersBulkActionsControllerBulkAllResetUserTraffic(ctx)
}

// BulkDeleteUsers calls UsersBulkActionsController_bulkDeleteUsers.
func (sc *UsersBulkActionsClient) BulkDeleteUsers(ctx context.Context, request *BulkUuidsRequest) (UsersBulkActionsControllerBulkDeleteUsersRes, error) {
	return sc.client.UsersBulkActionsControllerBulkDeleteUsers(ctx, request)
}

// BulkDeleteUsersByStatus calls UsersBulkActionsController_bulkDeleteUsersByStatus.
func (sc *UsersBulkActionsClient) BulkDeleteUsersByStatus(ctx context.Context, request *BulkDeleteUsersByStatusRequestDto) (UsersBulkActionsControllerBulkDeleteUsersByStatusRes, error) {
	return sc.client.UsersBulkActionsControllerBulkDeleteUsersByStatus(ctx, request)
}

// BulkExtendExpirationDate calls UsersBulkActionsController_bulkExtendExpirationDate.
func (sc *UsersBulkActionsClient) BulkExtendExpirationDate(ctx context.Context, request *BulkExtendExpirationDateRequestDto) (UsersBulkActionsControllerBulkExtendExpirationDateRes, error) {
	return sc.client.UsersBulkActionsControllerBulkExtendExpirationDate(ctx, request)
}

// BulkResetUserTraffic calls UsersBulkActionsController_bulkResetUserTraffic.
func (sc *UsersBulkActionsClient) BulkResetUserTraffic(ctx context.Context, request *BulkUuidsRequest) (UsersBulkActionsControllerBulkResetUserTrafficRes, error) {
	return sc.client.UsersBulkActionsControllerBulkResetUserTraffic(ctx, request)
}

// BulkRevokeUsersSubscription calls UsersBulkActionsController_bulkRevokeUsersSubscription.
func (sc *UsersBulkActionsClient) BulkRevokeUsersSubscription(ctx context.Context, request *BulkUuidsRequest) (UsersBulkActionsControllerBulkRevokeUsersSubscriptionRes, error) {
	return sc.client.UsersBulkActionsControllerBulkRevokeUsersSubscription(ctx, request)
}

// BulkUpdateAllUsers calls UsersBulkActionsController_bulkUpdateAllUsers.
func (sc *UsersBulkActionsClient) BulkUpdateAllUsers(ctx context.Context, request *BulkAllUpdateUsersRequestDto) (UsersBulkActionsControllerBulkUpdateAllUsersRes, error) {
	return sc.client.UsersBulkActionsControllerBulkUpdateAllUsers(ctx, request)
}

// BulkUpdateUsers calls UsersBulkActionsController_bulkUpdateUsers.
func (sc *UsersBulkActionsClient) BulkUpdateUsers(ctx context.Context, request *BulkUpdateUsersRequestDto) (UsersBulkActionsControllerBulkUpdateUsersRes, error) {
	return sc.client.UsersBulkActionsControllerBulkUpdateUsers(ctx, request)
}

// BulkUpdateUsersInternalSquads calls UsersBulkActionsController_bulkUpdateUsersInternalSquads.
func (sc *UsersBulkActionsClient) BulkUpdateUsersInternalSquads(ctx context.Context, request *BulkUpdateUsersSquadsRequestDto) (UsersBulkActionsControllerBulkUpdateUsersInternalSquadsRes, error) {
	return sc.client.UsersBulkActionsControllerBulkUpdateUsersInternalSquads(ctx, request)
}

