// Code generated by ogen, DO NOT EDIT.
package api

type ApiTokensControllerCreateRes interface {
	apiTokensControllerCreateRes()
}

type ApiTokensControllerDeleteRes interface {
	apiTokensControllerDeleteRes()
}

type ApiTokensControllerFindAllRes interface {
	apiTokensControllerFindAllRes()
}

type AuthControllerGetStatusRes interface {
	authControllerGetStatusRes()
}

type AuthControllerLoginRes interface {
	authControllerLoginRes()
}

type AuthControllerOauth2AuthorizeRes interface {
	authControllerOauth2AuthorizeRes()
}

type AuthControllerOauth2CallbackRes interface {
	authControllerOauth2CallbackRes()
}

type AuthControllerPasskeyAuthenticationOptionsRes interface {
	authControllerPasskeyAuthenticationOptionsRes()
}

type AuthControllerPasskeyAuthenticationVerifyRes interface {
	authControllerPasskeyAuthenticationVerifyRes()
}

type AuthControllerRegisterRes interface {
	authControllerRegisterRes()
}

type AuthControllerTelegramCallbackRes interface {
	authControllerTelegramCallbackRes()
}

type BandwidthStatsNodesControllerGetNodeUserUsageRes interface {
	bandwidthStatsNodesControllerGetNodeUserUsageRes()
}

type BandwidthStatsNodesControllerGetNodesRealtimeUsageRes interface {
	bandwidthStatsNodesControllerGetNodesRealtimeUsageRes()
}

type BandwidthStatsNodesControllerGetStatsNodeUsersUsageRes interface {
	bandwidthStatsNodesControllerGetStatsNodeUsersUsageRes()
}

type BandwidthStatsUsersControllerGetStatsNodesUsageRes interface {
	bandwidthStatsUsersControllerGetStatsNodesUsageRes()
}

type BandwidthStatsUsersControllerGetUserUsageByRangeRes interface {
	bandwidthStatsUsersControllerGetUserUsageByRangeRes()
}

type ConfigProfileControllerCreateConfigProfileRes interface {
	configProfileControllerCreateConfigProfileRes()
}

type ConfigProfileControllerDeleteConfigProfileByUuidRes interface {
	configProfileControllerDeleteConfigProfileByUuidRes()
}

type ConfigProfileControllerGetAllInboundsRes interface {
	configProfileControllerGetAllInboundsRes()
}

type ConfigProfileControllerGetComputedConfigProfileByUuidRes interface {
	configProfileControllerGetComputedConfigProfileByUuidRes()
}

type ConfigProfileControllerGetConfigProfileByUuidRes interface {
	configProfileControllerGetConfigProfileByUuidRes()
}

type ConfigProfileControllerGetConfigProfilesRes interface {
	configProfileControllerGetConfigProfilesRes()
}

type ConfigProfileControllerGetInboundsByProfileUuidRes interface {
	configProfileControllerGetInboundsByProfileUuidRes()
}

type ConfigProfileControllerReorderConfigProfilesRes interface {
	configProfileControllerReorderConfigProfilesRes()
}

type ConfigProfileControllerUpdateConfigProfileRes interface {
	configProfileControllerUpdateConfigProfileRes()
}

type ExternalSquadControllerAddUsersToExternalSquadRes interface {
	externalSquadControllerAddUsersToExternalSquadRes()
}

type ExternalSquadControllerCreateExternalSquadRes interface {
	externalSquadControllerCreateExternalSquadRes()
}

type ExternalSquadControllerDeleteExternalSquadRes interface {
	externalSquadControllerDeleteExternalSquadRes()
}

type ExternalSquadControllerGetExternalSquadByUuidRes interface {
	externalSquadControllerGetExternalSquadByUuidRes()
}

type ExternalSquadControllerGetExternalSquadsRes interface {
	externalSquadControllerGetExternalSquadsRes()
}

type ExternalSquadControllerRemoveUsersFromExternalSquadRes interface {
	externalSquadControllerRemoveUsersFromExternalSquadRes()
}

type ExternalSquadControllerReorderExternalSquadsRes interface {
	externalSquadControllerReorderExternalSquadsRes()
}

type ExternalSquadControllerUpdateExternalSquadRes interface {
	externalSquadControllerUpdateExternalSquadRes()
}

type HostsBulkActionsControllerDeleteHostsRes interface {
	hostsBulkActionsControllerDeleteHostsRes()
}

type HostsBulkActionsControllerDisableHostsRes interface {
	hostsBulkActionsControllerDisableHostsRes()
}

type HostsBulkActionsControllerEnableHostsRes interface {
	hostsBulkActionsControllerEnableHostsRes()
}

type HostsBulkActionsControllerSetInboundToHostsRes interface {
	hostsBulkActionsControllerSetInboundToHostsRes()
}

type HostsBulkActionsControllerSetPortToHostsRes interface {
	hostsBulkActionsControllerSetPortToHostsRes()
}

type HostsControllerCreateHostRes interface {
	hostsControllerCreateHostRes()
}

type HostsControllerDeleteHostRes interface {
	hostsControllerDeleteHostRes()
}

type HostsControllerGetAllHostTagsRes interface {
	hostsControllerGetAllHostTagsRes()
}

type HostsControllerGetAllHostsRes interface {
	hostsControllerGetAllHostsRes()
}

type HostsControllerGetOneHostRes interface {
	hostsControllerGetOneHostRes()
}

type HostsControllerReorderHostsRes interface {
	hostsControllerReorderHostsRes()
}

type HostsControllerUpdateHostRes interface {
	hostsControllerUpdateHostRes()
}

type HwidUserDevicesControllerCreateUserHwidDeviceRes interface {
	hwidUserDevicesControllerCreateUserHwidDeviceRes()
}

type HwidUserDevicesControllerDeleteAllUserHwidDevicesRes interface {
	hwidUserDevicesControllerDeleteAllUserHwidDevicesRes()
}

type HwidUserDevicesControllerDeleteUserHwidDeviceRes interface {
	hwidUserDevicesControllerDeleteUserHwidDeviceRes()
}

type HwidUserDevicesControllerGetAllUsersRes interface {
	hwidUserDevicesControllerGetAllUsersRes()
}

type HwidUserDevicesControllerGetHwidDevicesStatsRes interface {
	hwidUserDevicesControllerGetHwidDevicesStatsRes()
}

type HwidUserDevicesControllerGetTopUsersByHwidDevicesRes interface {
	hwidUserDevicesControllerGetTopUsersByHwidDevicesRes()
}

type HwidUserDevicesControllerGetUserHwidDevicesRes interface {
	hwidUserDevicesControllerGetUserHwidDevicesRes()
}

type InfraBillingControllerCreateInfraBillingHistoryRecordRes interface {
	infraBillingControllerCreateInfraBillingHistoryRecordRes()
}

type InfraBillingControllerCreateInfraBillingNodeRes interface {
	infraBillingControllerCreateInfraBillingNodeRes()
}

type InfraBillingControllerCreateInfraProviderRes interface {
	infraBillingControllerCreateInfraProviderRes()
}

type InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidRes interface {
	infraBillingControllerDeleteInfraBillingHistoryRecordByUuidRes()
}

type InfraBillingControllerDeleteInfraBillingNodeByUuidRes interface {
	infraBillingControllerDeleteInfraBillingNodeByUuidRes()
}

type InfraBillingControllerDeleteInfraProviderByUuidRes interface {
	infraBillingControllerDeleteInfraProviderByUuidRes()
}

type InfraBillingControllerGetBillingNodesRes interface {
	infraBillingControllerGetBillingNodesRes()
}

type InfraBillingControllerGetInfraBillingHistoryRecordsRes interface {
	infraBillingControllerGetInfraBillingHistoryRecordsRes()
}

type InfraBillingControllerGetInfraProviderByUuidRes interface {
	infraBillingControllerGetInfraProviderByUuidRes()
}

type InfraBillingControllerGetInfraProvidersRes interface {
	infraBillingControllerGetInfraProvidersRes()
}

type InfraBillingControllerUpdateInfraBillingNodeRes interface {
	infraBillingControllerUpdateInfraBillingNodeRes()
}

type InfraBillingControllerUpdateInfraProviderRes interface {
	infraBillingControllerUpdateInfraProviderRes()
}

type InternalSquadControllerAddUsersToInternalSquadRes interface {
	internalSquadControllerAddUsersToInternalSquadRes()
}

type InternalSquadControllerCreateInternalSquadRes interface {
	internalSquadControllerCreateInternalSquadRes()
}

type InternalSquadControllerDeleteInternalSquadRes interface {
	internalSquadControllerDeleteInternalSquadRes()
}

type InternalSquadControllerGetInternalSquadAccessibleNodesRes interface {
	internalSquadControllerGetInternalSquadAccessibleNodesRes()
}

type InternalSquadControllerGetInternalSquadByUuidRes interface {
	internalSquadControllerGetInternalSquadByUuidRes()
}

type InternalSquadControllerGetInternalSquadsRes interface {
	internalSquadControllerGetInternalSquadsRes()
}

type InternalSquadControllerRemoveUsersFromInternalSquadRes interface {
	internalSquadControllerRemoveUsersFromInternalSquadRes()
}

type InternalSquadControllerReorderInternalSquadsRes interface {
	internalSquadControllerReorderInternalSquadsRes()
}

type InternalSquadControllerUpdateInternalSquadRes interface {
	internalSquadControllerUpdateInternalSquadRes()
}

type KeygenControllerGenerateKeyRes interface {
	keygenControllerGenerateKeyRes()
}

type NodesControllerCreateNodeRes interface {
	nodesControllerCreateNodeRes()
}

type NodesControllerDeleteNodeRes interface {
	nodesControllerDeleteNodeRes()
}

type NodesControllerDisableNodeRes interface {
	nodesControllerDisableNodeRes()
}

type NodesControllerEnableNodeRes interface {
	nodesControllerEnableNodeRes()
}

type NodesControllerGetAllNodesRes interface {
	nodesControllerGetAllNodesRes()
}

type NodesControllerGetAllNodesTagsRes interface {
	nodesControllerGetAllNodesTagsRes()
}

type NodesControllerGetOneNodeRes interface {
	nodesControllerGetOneNodeRes()
}

type NodesControllerProfileModificationRes interface {
	nodesControllerProfileModificationRes()
}

type NodesControllerReorderNodesRes interface {
	nodesControllerReorderNodesRes()
}

type NodesControllerResetNodeTrafficRes interface {
	nodesControllerResetNodeTrafficRes()
}

type NodesControllerRestartAllNodesRes interface {
	nodesControllerRestartAllNodesRes()
}

type NodesControllerRestartNodeRes interface {
	nodesControllerRestartNodeRes()
}

type NodesControllerUpdateNodeRes interface {
	nodesControllerUpdateNodeRes()
}

type NodesUsageHistoryControllerGetStatsNodesUsageRes interface {
	nodesUsageHistoryControllerGetStatsNodesUsageRes()
}

type PasskeyControllerDeletePasskeyRes interface {
	passkeyControllerDeletePasskeyRes()
}

type PasskeyControllerGetActivePasskeysRes interface {
	passkeyControllerGetActivePasskeysRes()
}

type PasskeyControllerPasskeyRegistrationOptionsRes interface {
	passkeyControllerPasskeyRegistrationOptionsRes()
}

type PasskeyControllerPasskeyRegistrationVerifyRes interface {
	passkeyControllerPasskeyRegistrationVerifyRes()
}

type PasskeyControllerUpdatePasskeyRes interface {
	passkeyControllerUpdatePasskeyRes()
}

type RemnawaveSettingsControllerGetSettingsRes interface {
	remnawaveSettingsControllerGetSettingsRes()
}

type RemnawaveSettingsControllerUpdateSettingsRes interface {
	remnawaveSettingsControllerUpdateSettingsRes()
}

type SnippetsControllerCreateSnippetRes interface {
	snippetsControllerCreateSnippetRes()
}

type SnippetsControllerDeleteSnippetByNameRes interface {
	snippetsControllerDeleteSnippetByNameRes()
}

type SnippetsControllerGetSnippetsRes interface {
	snippetsControllerGetSnippetsRes()
}

type SnippetsControllerUpdateSnippetRes interface {
	snippetsControllerUpdateSnippetRes()
}

type SubscriptionControllerGetSubscriptionInfoByShortUuidRes interface {
	subscriptionControllerGetSubscriptionInfoByShortUuidRes()
}

type SubscriptionPageConfigControllerCloneSubscriptionPageConfigRes interface {
	subscriptionPageConfigControllerCloneSubscriptionPageConfigRes()
}

type SubscriptionPageConfigControllerCreateConfigRes interface {
	subscriptionPageConfigControllerCreateConfigRes()
}

type SubscriptionPageConfigControllerDeleteConfigRes interface {
	subscriptionPageConfigControllerDeleteConfigRes()
}

type SubscriptionPageConfigControllerGetAllConfigsRes interface {
	subscriptionPageConfigControllerGetAllConfigsRes()
}

type SubscriptionPageConfigControllerGetConfigByUuidRes interface {
	subscriptionPageConfigControllerGetConfigByUuidRes()
}

type SubscriptionPageConfigControllerReorderSubscriptionPageConfigsRes interface {
	subscriptionPageConfigControllerReorderSubscriptionPageConfigsRes()
}

type SubscriptionPageConfigControllerUpdateConfigRes interface {
	subscriptionPageConfigControllerUpdateConfigRes()
}

type SubscriptionSettingsControllerGetSettingsRes interface {
	subscriptionSettingsControllerGetSettingsRes()
}

type SubscriptionSettingsControllerUpdateSettingsRes interface {
	subscriptionSettingsControllerUpdateSettingsRes()
}

type SubscriptionTemplateControllerCreateTemplateRes interface {
	subscriptionTemplateControllerCreateTemplateRes()
}

type SubscriptionTemplateControllerDeleteTemplateRes interface {
	subscriptionTemplateControllerDeleteTemplateRes()
}

type SubscriptionTemplateControllerGetAllTemplatesRes interface {
	subscriptionTemplateControllerGetAllTemplatesRes()
}

type SubscriptionTemplateControllerGetTemplateByUuidRes interface {
	subscriptionTemplateControllerGetTemplateByUuidRes()
}

type SubscriptionTemplateControllerReorderSubscriptionTemplatesRes interface {
	subscriptionTemplateControllerReorderSubscriptionTemplatesRes()
}

type SubscriptionTemplateControllerUpdateTemplateRes interface {
	subscriptionTemplateControllerUpdateTemplateRes()
}

type SubscriptionsControllerGetAllSubscriptionsRes interface {
	subscriptionsControllerGetAllSubscriptionsRes()
}

type SubscriptionsControllerGetRawSubscriptionByShortUuidRes interface {
	subscriptionsControllerGetRawSubscriptionByShortUuidRes()
}

type SubscriptionsControllerGetSubpageConfigByShortUuidRes interface {
	subscriptionsControllerGetSubpageConfigByShortUuidRes()
}

type SubscriptionsControllerGetSubscriptionByShortUuidProtectedRes interface {
	subscriptionsControllerGetSubscriptionByShortUuidProtectedRes()
}

type SubscriptionsControllerGetSubscriptionByUsernameRes interface {
	subscriptionsControllerGetSubscriptionByUsernameRes()
}

type SubscriptionsControllerGetSubscriptionByUuidRes interface {
	subscriptionsControllerGetSubscriptionByUuidRes()
}

type SystemControllerDebugSrrMatcherRes interface {
	systemControllerDebugSrrMatcherRes()
}

type SystemControllerEncryptHappCryptoLinkRes interface {
	systemControllerEncryptHappCryptoLinkRes()
}

type SystemControllerGetBandwidthStatsRes interface {
	systemControllerGetBandwidthStatsRes()
}

type SystemControllerGetMetadataRes interface {
	systemControllerGetMetadataRes()
}

type SystemControllerGetNodesMetricsRes interface {
	systemControllerGetNodesMetricsRes()
}

type SystemControllerGetNodesStatisticsRes interface {
	systemControllerGetNodesStatisticsRes()
}

type SystemControllerGetRemnawaveHealthRes interface {
	systemControllerGetRemnawaveHealthRes()
}

type SystemControllerGetStatsRes interface {
	systemControllerGetStatsRes()
}

type SystemControllerGetX25519KeypairsRes interface {
	systemControllerGetX25519KeypairsRes()
}

type UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryRes interface {
	userSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryRes()
}

type UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryStatsRes interface {
	userSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryStatsRes()
}

type UsersBulkActionsControllerBulkAllExtendExpirationDateRes interface {
	usersBulkActionsControllerBulkAllExtendExpirationDateRes()
}

type UsersBulkActionsControllerBulkAllResetUserTrafficRes interface {
	usersBulkActionsControllerBulkAllResetUserTrafficRes()
}

type UsersBulkActionsControllerBulkDeleteUsersByStatusRes interface {
	usersBulkActionsControllerBulkDeleteUsersByStatusRes()
}

type UsersBulkActionsControllerBulkDeleteUsersRes interface {
	usersBulkActionsControllerBulkDeleteUsersRes()
}

type UsersBulkActionsControllerBulkExtendExpirationDateRes interface {
	usersBulkActionsControllerBulkExtendExpirationDateRes()
}

type UsersBulkActionsControllerBulkResetUserTrafficRes interface {
	usersBulkActionsControllerBulkResetUserTrafficRes()
}

type UsersBulkActionsControllerBulkRevokeUsersSubscriptionRes interface {
	usersBulkActionsControllerBulkRevokeUsersSubscriptionRes()
}

type UsersBulkActionsControllerBulkUpdateAllUsersRes interface {
	usersBulkActionsControllerBulkUpdateAllUsersRes()
}

type UsersBulkActionsControllerBulkUpdateUsersInternalSquadsRes interface {
	usersBulkActionsControllerBulkUpdateUsersInternalSquadsRes()
}

type UsersBulkActionsControllerBulkUpdateUsersRes interface {
	usersBulkActionsControllerBulkUpdateUsersRes()
}

type UsersControllerCreateUserRes interface {
	usersControllerCreateUserRes()
}

type UsersControllerDeleteUserRes interface {
	usersControllerDeleteUserRes()
}

type UsersControllerDisableUserRes interface {
	usersControllerDisableUserRes()
}

type UsersControllerEnableUserRes interface {
	usersControllerEnableUserRes()
}

type UsersControllerGetAllTagsRes interface {
	usersControllerGetAllTagsRes()
}

type UsersControllerGetAllUsersRes interface {
	usersControllerGetAllUsersRes()
}

type UsersControllerGetUserAccessibleNodesRes interface {
	usersControllerGetUserAccessibleNodesRes()
}

type UsersControllerGetUserByIdRes interface {
	usersControllerGetUserByIdRes()
}

type UsersControllerGetUserByShortUuidRes interface {
	usersControllerGetUserByShortUuidRes()
}

type UsersControllerGetUserByTelegramIdRes interface {
	usersControllerGetUserByTelegramIdRes()
}

type UsersControllerGetUserByUsernameRes interface {
	usersControllerGetUserByUsernameRes()
}

type UsersControllerGetUserByUuidRes interface {
	usersControllerGetUserByUuidRes()
}

type UsersControllerGetUserSubscriptionRequestHistoryRes interface {
	usersControllerGetUserSubscriptionRequestHistoryRes()
}

type UsersControllerGetUsersByEmailRes interface {
	usersControllerGetUsersByEmailRes()
}

type UsersControllerGetUsersByTagRes interface {
	usersControllerGetUsersByTagRes()
}

type UsersControllerResetUserTrafficRes interface {
	usersControllerResetUserTrafficRes()
}

type UsersControllerRevokeUserSubscriptionRes interface {
	usersControllerRevokeUserSubscriptionRes()
}

type UsersControllerUpdateUserRes interface {
	usersControllerUpdateUserRes()
}
