// Code generated by ogen, DO NOT EDIT.
package api

type ApiTokensControllerCreateRes interface {
	apiTokensControllerCreateRes()
}

type ApiTokensControllerDeleteRes interface {
	apiTokensControllerDeleteRes()
}

type ApiTokensControllerFindAllRes interface {
	apiTokensControllerFindAllRes()
}

type AuthControllerGetStatusRes interface {
	authControllerGetStatusRes()
}

type AuthControllerLoginRes interface {
	authControllerLoginRes()
}

type AuthControllerOauth2AuthorizeRes interface {
	authControllerOauth2AuthorizeRes()
}

type AuthControllerOauth2CallbackRes interface {
	authControllerOauth2CallbackRes()
}

type AuthControllerRegisterRes interface {
	authControllerRegisterRes()
}

type AuthControllerTelegramCallbackRes interface {
	authControllerTelegramCallbackRes()
}

type ConfigProfileControllerCreateConfigProfileRes interface {
	configProfileControllerCreateConfigProfileRes()
}

type ConfigProfileControllerDeleteConfigProfileByUuidRes interface {
	configProfileControllerDeleteConfigProfileByUuidRes()
}

type ConfigProfileControllerGetAllInboundsRes interface {
	configProfileControllerGetAllInboundsRes()
}

type ConfigProfileControllerGetConfigProfileByUuidRes interface {
	configProfileControllerGetConfigProfileByUuidRes()
}

type ConfigProfileControllerGetConfigProfilesRes interface {
	configProfileControllerGetConfigProfilesRes()
}

type ConfigProfileControllerGetInboundsByProfileUuidRes interface {
	configProfileControllerGetInboundsByProfileUuidRes()
}

type ConfigProfileControllerUpdateConfigProfileRes interface {
	configProfileControllerUpdateConfigProfileRes()
}

type HostsBulkActionsControllerDeleteHostsRes interface {
	hostsBulkActionsControllerDeleteHostsRes()
}

type HostsBulkActionsControllerDisableHostsRes interface {
	hostsBulkActionsControllerDisableHostsRes()
}

type HostsBulkActionsControllerEnableHostsRes interface {
	hostsBulkActionsControllerEnableHostsRes()
}

type HostsBulkActionsControllerSetInboundToHostsRes interface {
	hostsBulkActionsControllerSetInboundToHostsRes()
}

type HostsBulkActionsControllerSetPortToHostsRes interface {
	hostsBulkActionsControllerSetPortToHostsRes()
}

type HostsControllerCreateHostRes interface {
	hostsControllerCreateHostRes()
}

type HostsControllerDeleteHostRes interface {
	hostsControllerDeleteHostRes()
}

type HostsControllerGetAllHostsRes interface {
	hostsControllerGetAllHostsRes()
}

type HostsControllerGetOneHostRes interface {
	hostsControllerGetOneHostRes()
}

type HostsControllerReorderHostsRes interface {
	hostsControllerReorderHostsRes()
}

type HostsControllerUpdateHostRes interface {
	hostsControllerUpdateHostRes()
}

type HwidUserDevicesControllerCreateUserHwidDeviceRes interface {
	hwidUserDevicesControllerCreateUserHwidDeviceRes()
}

type HwidUserDevicesControllerDeleteUserHwidDeviceRes interface {
	hwidUserDevicesControllerDeleteUserHwidDeviceRes()
}

type HwidUserDevicesControllerGetUserHwidDevicesRes interface {
	hwidUserDevicesControllerGetUserHwidDevicesRes()
}

type InfraBillingControllerCreateInfraBillingHistoryRecordRes interface {
	infraBillingControllerCreateInfraBillingHistoryRecordRes()
}

type InfraBillingControllerCreateInfraBillingNodeRes interface {
	infraBillingControllerCreateInfraBillingNodeRes()
}

type InfraBillingControllerCreateInfraProviderRes interface {
	infraBillingControllerCreateInfraProviderRes()
}

type InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidRes interface {
	infraBillingControllerDeleteInfraBillingHistoryRecordByUuidRes()
}

type InfraBillingControllerDeleteInfraBillingNodeByUuidRes interface {
	infraBillingControllerDeleteInfraBillingNodeByUuidRes()
}

type InfraBillingControllerDeleteInfraProviderByUuidRes interface {
	infraBillingControllerDeleteInfraProviderByUuidRes()
}

type InfraBillingControllerGetBillingNodesRes interface {
	infraBillingControllerGetBillingNodesRes()
}

type InfraBillingControllerGetInfraBillingHistoryRecordsRes interface {
	infraBillingControllerGetInfraBillingHistoryRecordsRes()
}

type InfraBillingControllerGetInfraProviderByUuidRes interface {
	infraBillingControllerGetInfraProviderByUuidRes()
}

type InfraBillingControllerGetInfraProvidersRes interface {
	infraBillingControllerGetInfraProvidersRes()
}

type InfraBillingControllerUpdateInfraBillingNodeRes interface {
	infraBillingControllerUpdateInfraBillingNodeRes()
}

type InfraBillingControllerUpdateInfraProviderRes interface {
	infraBillingControllerUpdateInfraProviderRes()
}

type InternalSquadControllerAddUsersToInternalSquadRes interface {
	internalSquadControllerAddUsersToInternalSquadRes()
}

type InternalSquadControllerCreateInternalSquadRes interface {
	internalSquadControllerCreateInternalSquadRes()
}

type InternalSquadControllerDeleteInternalSquadRes interface {
	internalSquadControllerDeleteInternalSquadRes()
}

type InternalSquadControllerGetInternalSquadByUuidRes interface {
	internalSquadControllerGetInternalSquadByUuidRes()
}

type InternalSquadControllerGetInternalSquadsRes interface {
	internalSquadControllerGetInternalSquadsRes()
}

type InternalSquadControllerRemoveUsersFromInternalSquadRes interface {
	internalSquadControllerRemoveUsersFromInternalSquadRes()
}

type InternalSquadControllerUpdateInternalSquadRes interface {
	internalSquadControllerUpdateInternalSquadRes()
}

type KeygenControllerGenerateKeyRes interface {
	keygenControllerGenerateKeyRes()
}

type NodesControllerCreateNodeRes interface {
	nodesControllerCreateNodeRes()
}

type NodesControllerDeleteNodeRes interface {
	nodesControllerDeleteNodeRes()
}

type NodesControllerDisableNodeRes interface {
	nodesControllerDisableNodeRes()
}

type NodesControllerEnableNodeRes interface {
	nodesControllerEnableNodeRes()
}

type NodesControllerGetAllNodesRes interface {
	nodesControllerGetAllNodesRes()
}

type NodesControllerGetOneNodeRes interface {
	nodesControllerGetOneNodeRes()
}

type NodesControllerReorderNodesRes interface {
	nodesControllerReorderNodesRes()
}

type NodesControllerRestartAllNodesRes interface {
	nodesControllerRestartAllNodesRes()
}

type NodesControllerRestartNodeRes interface {
	nodesControllerRestartNodeRes()
}

type NodesControllerUpdateNodeRes interface {
	nodesControllerUpdateNodeRes()
}

type NodesUsageHistoryControllerGetNodesUsageByRangeRes interface {
	nodesUsageHistoryControllerGetNodesUsageByRangeRes()
}

type NodesUserUsageHistoryControllerGetNodeUserUsageRes interface {
	nodesUserUsageHistoryControllerGetNodeUserUsageRes()
}

type NodesUserUsageHistoryControllerGetNodesRealtimeUsageRes interface {
	nodesUserUsageHistoryControllerGetNodesRealtimeUsageRes()
}

type SubscriptionControllerGetRawSubscriptionByShortUuidRes interface {
	subscriptionControllerGetRawSubscriptionByShortUuidRes()
}

type SubscriptionControllerGetSubscriptionInfoByShortUuidRes interface {
	subscriptionControllerGetSubscriptionInfoByShortUuidRes()
}

type SubscriptionSettingsControllerGetSettingsRes interface {
	subscriptionSettingsControllerGetSettingsRes()
}

type SubscriptionSettingsControllerUpdateSettingsRes interface {
	subscriptionSettingsControllerUpdateSettingsRes()
}

type SubscriptionTemplateControllerGetTemplateRes interface {
	subscriptionTemplateControllerGetTemplateRes()
}

type SubscriptionTemplateControllerUpdateTemplateRes interface {
	subscriptionTemplateControllerUpdateTemplateRes()
}

type SubscriptionsControllerGetAllSubscriptionsRes interface {
	subscriptionsControllerGetAllSubscriptionsRes()
}

type SubscriptionsControllerGetSubscriptionByUsernameRes interface {
	subscriptionsControllerGetSubscriptionByUsernameRes()
}

type SystemControllerGetBandwidthStatsRes interface {
	systemControllerGetBandwidthStatsRes()
}

type SystemControllerGetNodesMetricsRes interface {
	systemControllerGetNodesMetricsRes()
}

type SystemControllerGetNodesStatisticsRes interface {
	systemControllerGetNodesStatisticsRes()
}

type SystemControllerGetRemnawaveHealthRes interface {
	systemControllerGetRemnawaveHealthRes()
}

type SystemControllerGetStatsRes interface {
	systemControllerGetStatsRes()
}

type UsersBulkActionsControllerBulkAllResetUserTrafficRes interface {
	usersBulkActionsControllerBulkAllResetUserTrafficRes()
}

type UsersBulkActionsControllerBulkDeleteUsersByStatusRes interface {
	usersBulkActionsControllerBulkDeleteUsersByStatusRes()
}

type UsersBulkActionsControllerBulkDeleteUsersRes interface {
	usersBulkActionsControllerBulkDeleteUsersRes()
}

type UsersBulkActionsControllerBulkResetUserTrafficRes interface {
	usersBulkActionsControllerBulkResetUserTrafficRes()
}

type UsersBulkActionsControllerBulkRevokeUsersSubscriptionRes interface {
	usersBulkActionsControllerBulkRevokeUsersSubscriptionRes()
}

type UsersBulkActionsControllerBulkUpdateAllUsersRes interface {
	usersBulkActionsControllerBulkUpdateAllUsersRes()
}

type UsersBulkActionsControllerBulkUpdateUsersInternalSquadsRes interface {
	usersBulkActionsControllerBulkUpdateUsersInternalSquadsRes()
}

type UsersBulkActionsControllerBulkUpdateUsersRes interface {
	usersBulkActionsControllerBulkUpdateUsersRes()
}

type UsersControllerCreateUserRes interface {
	usersControllerCreateUserRes()
}

type UsersControllerDeleteUserRes interface {
	usersControllerDeleteUserRes()
}

type UsersControllerDisableUserRes interface {
	usersControllerDisableUserRes()
}

type UsersControllerEnableUserRes interface {
	usersControllerEnableUserRes()
}

type UsersControllerGetAllTagsRes interface {
	usersControllerGetAllTagsRes()
}

type UsersControllerGetAllUsersRes interface {
	usersControllerGetAllUsersRes()
}

type UsersControllerGetUserAccessibleNodesRes interface {
	usersControllerGetUserAccessibleNodesRes()
}

type UsersControllerGetUserByShortUuidRes interface {
	usersControllerGetUserByShortUuidRes()
}

type UsersControllerGetUserByTelegramIdRes interface {
	usersControllerGetUserByTelegramIdRes()
}

type UsersControllerGetUserByUsernameRes interface {
	usersControllerGetUserByUsernameRes()
}

type UsersControllerGetUserByUuidRes interface {
	usersControllerGetUserByUuidRes()
}

type UsersControllerGetUsersByEmailRes interface {
	usersControllerGetUsersByEmailRes()
}

type UsersControllerGetUsersByTagRes interface {
	usersControllerGetUsersByTagRes()
}

type UsersControllerResetUserTrafficRes interface {
	usersControllerResetUserTrafficRes()
}

type UsersControllerRevokeUserSubscriptionRes interface {
	usersControllerRevokeUserSubscriptionRes()
}

type UsersControllerUpdateUserRes interface {
	usersControllerUpdateUserRes()
}

type UsersStatsControllerGetUserUsageByRangeRes interface {
	usersStatsControllerGetUserUsageByRangeRes()
}
