// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

// ApiTokensDeleteParams is parameters of ApiTokens_delete operation.
type ApiTokensDeleteParams struct {
	// UUID of the API token.
	UUID string
}

// BandwidthStatsNodesGetNodeUserUsageParams is parameters of BandwidthStatsNodes_getNodeUserUsage operation.
type BandwidthStatsNodesGetNodeUserUsageParams struct {
	// Start date.
	Start time.Time
	// End date.
	End time.Time
	// UUID of the node.
	UUID string
}

// BandwidthStatsNodesGetStatsNodeUsersUsageParams is parameters of BandwidthStatsNodes_getStatsNodeUsersUsage operation.
type BandwidthStatsNodesGetStatsNodeUsersUsageParams struct {
	// Limit of top users to return.
	TopUsersLimit int
	// Start date (YYYY-MM-DD).
	Start time.Time
	// End date (YYYY-MM-DD).
	End time.Time
	// UUID of the node.
	UUID string
}

// BandwidthStatsUsersGetStatsNodesUsageParams is parameters of BandwidthStatsUsers_getStatsNodesUsage operation.
type BandwidthStatsUsersGetStatsNodesUsageParams struct {
	// Limit of top nodes to return.
	TopNodesLimit int
	// Start date (YYYY-MM-DD).
	Start time.Time
	// End date (YYYY-MM-DD).
	End time.Time
	// UUID of the user.
	UUID string
}

// BandwidthStatsUsersGetUserUsageByRangeParams is parameters of BandwidthStatsUsers_getUserUsageByRange operation.
type BandwidthStatsUsersGetUserUsageByRangeParams struct {
	// Start date.
	Start time.Time
	// End date.
	End time.Time
	// UUID of the user.
	UUID string
}

// ConfigProfileDeleteConfigProfileByUuidParams is parameters of ConfigProfile_deleteConfigProfileByUuid operation.
type ConfigProfileDeleteConfigProfileByUuidParams struct {
	UUID string
}

// ConfigProfileGetComputedConfigProfileByUuidParams is parameters of ConfigProfile_getComputedConfigProfileByUuid operation.
type ConfigProfileGetComputedConfigProfileByUuidParams struct {
	UUID string
}

// ConfigProfileGetConfigProfileByUuidParams is parameters of ConfigProfile_getConfigProfileByUuid operation.
type ConfigProfileGetConfigProfileByUuidParams struct {
	UUID string
}

// ConfigProfileGetInboundsByProfileUuidParams is parameters of ConfigProfile_getInboundsByProfileUuid operation.
type ConfigProfileGetInboundsByProfileUuidParams struct {
	UUID string
}

// ExternalSquadAddUsersToExternalSquadParams is parameters of ExternalSquad_addUsersToExternalSquad operation.
type ExternalSquadAddUsersToExternalSquadParams struct {
	UUID string
}

// ExternalSquadDeleteExternalSquadParams is parameters of ExternalSquad_deleteExternalSquad operation.
type ExternalSquadDeleteExternalSquadParams struct {
	UUID string
}

// ExternalSquadGetExternalSquadByUuidParams is parameters of ExternalSquad_getExternalSquadByUuid operation.
type ExternalSquadGetExternalSquadByUuidParams struct {
	UUID string
}

// ExternalSquadRemoveUsersFromExternalSquadParams is parameters of ExternalSquad_removeUsersFromExternalSquad operation.
type ExternalSquadRemoveUsersFromExternalSquadParams struct {
	UUID string
}

// HostsDeleteHostParams is parameters of Hosts_deleteHost operation.
type HostsDeleteHostParams struct {
	// UUID of the host.
	UUID string
}

// HostsGetOneHostParams is parameters of Hosts_getOneHost operation.
type HostsGetOneHostParams struct {
	// UUID of the host.
	UUID string
}

// HwidUserDevicesGetAllUsersParams is parameters of HwidUserDevices_getAllUsers operation.
type HwidUserDevicesGetAllUsersParams struct {
	// Page size for pagination.
	Size OptInt `json:",omitempty,omitzero"`
	// Offset for pagination.
	Start OptInt `json:",omitempty,omitzero"`
}

// HwidUserDevicesGetTopUsersByHwidDevicesParams is parameters of HwidUserDevices_getTopUsersByHwidDevices operation.
type HwidUserDevicesGetTopUsersByHwidDevicesParams struct {
	// Page size for pagination.
	Size OptInt `json:",omitempty,omitzero"`
	// Offset for pagination.
	Start OptInt `json:",omitempty,omitzero"`
}

// HwidUserDevicesGetUserHwidDevicesParams is parameters of HwidUserDevices_getUserHwidDevices operation.
type HwidUserDevicesGetUserHwidDevicesParams struct {
	// UUID of the user.
	UserUuid string
}

// InfraBillingDeleteInfraBillingHistoryRecordByUuidParams is parameters of InfraBilling_deleteInfraBillingHistoryRecordByUuid operation.
type InfraBillingDeleteInfraBillingHistoryRecordByUuidParams struct {
	UUID string
}

// InfraBillingDeleteInfraBillingNodeByUuidParams is parameters of InfraBilling_deleteInfraBillingNodeByUuid operation.
type InfraBillingDeleteInfraBillingNodeByUuidParams struct {
	UUID string
}

// InfraBillingDeleteInfraProviderByUuidParams is parameters of InfraBilling_deleteInfraProviderByUuid operation.
type InfraBillingDeleteInfraProviderByUuidParams struct {
	UUID string
}

// InfraBillingGetInfraProviderByUuidParams is parameters of InfraBilling_getInfraProviderByUuid operation.
type InfraBillingGetInfraProviderByUuidParams struct {
	UUID string
}

// InternalSquadAddUsersToInternalSquadParams is parameters of InternalSquad_addUsersToInternalSquad operation.
type InternalSquadAddUsersToInternalSquadParams struct {
	UUID string
}

// InternalSquadDeleteInternalSquadParams is parameters of InternalSquad_deleteInternalSquad operation.
type InternalSquadDeleteInternalSquadParams struct {
	UUID string
}

// InternalSquadGetInternalSquadAccessibleNodesParams is parameters of InternalSquad_getInternalSquadAccessibleNodes operation.
type InternalSquadGetInternalSquadAccessibleNodesParams struct {
	// UUID of the internal squad.
	UUID string
}

// InternalSquadGetInternalSquadByUuidParams is parameters of InternalSquad_getInternalSquadByUuid operation.
type InternalSquadGetInternalSquadByUuidParams struct {
	UUID string
}

// InternalSquadRemoveUsersFromInternalSquadParams is parameters of InternalSquad_removeUsersFromInternalSquad operation.
type InternalSquadRemoveUsersFromInternalSquadParams struct {
	UUID string
}

// NodesDeleteNodeParams is parameters of Nodes_deleteNode operation.
type NodesDeleteNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesDisableNodeParams is parameters of Nodes_disableNode operation.
type NodesDisableNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesEnableNodeParams is parameters of Nodes_enableNode operation.
type NodesEnableNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesGetOneNodeParams is parameters of Nodes_getOneNode operation.
type NodesGetOneNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesResetNodeTrafficParams is parameters of Nodes_resetNodeTraffic operation.
type NodesResetNodeTrafficParams struct {
	// Node UUID.
	UUID string
}

// NodesRestartNodeParams is parameters of Nodes_restartNode operation.
type NodesRestartNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesUsageHistoryGetStatsNodesUsageParams is parameters of NodesUsageHistory_getStatsNodesUsage operation.
type NodesUsageHistoryGetStatsNodesUsageParams struct {
	// Limit of top nodes to return.
	TopNodesLimit int
	// Start date (YYYY-MM-DD).
	Start time.Time
	// End date (YYYY-MM-DD).
	End time.Time
}

// SubscriptionGetSubscriptionParams is parameters of Subscription_getSubscription operation.
type SubscriptionGetSubscriptionParams struct {
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionGetSubscriptionByClientTypeParams is parameters of Subscription_getSubscriptionByClientType operation.
type SubscriptionGetSubscriptionByClientTypeParams struct {
	// Client type.
	ClientType SubscriptionGetSubscriptionByClientTypeClientType
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionGetSubscriptionInfoByShortUuidParams is parameters of Subscription_getSubscriptionInfoByShortUuid operation.
type SubscriptionGetSubscriptionInfoByShortUuidParams struct {
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionGetSubscriptionWithTypeParams is parameters of Subscription_getSubscriptionWithType operation.
type SubscriptionGetSubscriptionWithTypeParams struct {
	// Subscription type (required if encodedTag is provided). Only SS is supported for now.
	Type string
	// Base64 encoded tag for Outline config. This paramter is optional. It is required only when type=ss.
	EncodedTag string
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionPageConfigDeleteConfigParams is parameters of SubscriptionPageConfig_deleteConfig operation.
type SubscriptionPageConfigDeleteConfigParams struct {
	// Subscription page config UUID.
	UUID string
}

// SubscriptionPageConfigGetConfigByUuidParams is parameters of SubscriptionPageConfig_getConfigByUuid operation.
type SubscriptionPageConfigGetConfigByUuidParams struct {
	// Subscription page config UUID.
	UUID string
}

// SubscriptionTemplateDeleteTemplateParams is parameters of SubscriptionTemplate_deleteTemplate operation.
type SubscriptionTemplateDeleteTemplateParams struct {
	// Template UUID.
	UUID string
}

// SubscriptionTemplateGetTemplateByUuidParams is parameters of SubscriptionTemplate_getTemplateByUuid operation.
type SubscriptionTemplateGetTemplateByUuidParams struct {
	// Template UUID.
	UUID string
}

// SubscriptionsGetAllSubscriptionsParams is parameters of Subscriptions_getAllSubscriptions operation.
type SubscriptionsGetAllSubscriptionsParams struct {
	// Number of subscriptions to return, no more than 500.
	Size OptInt `json:",omitempty,omitzero"`
	// Start index (offset) of the users to return, default is 0.
	Start OptInt `json:",omitempty,omitzero"`
}

// SubscriptionsGetRawSubscriptionByShortUuidParams is parameters of Subscriptions_getRawSubscriptionByShortUuid operation.
type SubscriptionsGetRawSubscriptionByShortUuidParams struct {
	// Include disabled hosts in the subscription. Default is false.
	WithDisabledHosts OptBool `json:",omitempty,omitzero"`
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionsGetSubpageConfigByShortUuidParams is parameters of Subscriptions_getSubpageConfigByShortUuid operation.
type SubscriptionsGetSubpageConfigByShortUuidParams struct {
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionsGetSubscriptionByShortUuidProtectedParams is parameters of Subscriptions_getSubscriptionByShortUuidProtected operation.
type SubscriptionsGetSubscriptionByShortUuidProtectedParams struct {
	// Short uuid of the user.
	ShortUuid string
}

// SubscriptionsGetSubscriptionByUsernameParams is parameters of Subscriptions_getSubscriptionByUsername operation.
type SubscriptionsGetSubscriptionByUsernameParams struct {
	// Username of the user.
	Username string
}

// SubscriptionsGetSubscriptionByUuidParams is parameters of Subscriptions_getSubscriptionByUuid operation.
type SubscriptionsGetSubscriptionByUuidParams struct {
	// Uuid of the user.
	UUID string
}

// UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryParams is parameters of UserSubscriptionRequestHistory_getSubscriptionRequestHistory operation.
type UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryParams struct {
	// Page size for pagination.
	Size OptInt `json:",omitempty,omitzero"`
	// Offset for pagination.
	Start OptInt `json:",omitempty,omitzero"`
}

// UsersDeleteUserParams is parameters of Users_deleteUser operation.
type UsersDeleteUserParams struct {
	// UUID of the user.
	UUID string
}

// UsersDisableUserParams is parameters of Users_disableUser operation.
type UsersDisableUserParams struct {
	// UUID of the user.
	UUID string
}

// UsersEnableUserParams is parameters of Users_enableUser operation.
type UsersEnableUserParams struct {
	// UUID of the user.
	UUID string
}

// UsersGetAllUsersParams is parameters of Users_getAllUsers operation.
type UsersGetAllUsersParams struct {
	// Page size for pagination.
	Size OptInt `json:",omitempty,omitzero"`
	// Offset for pagination.
	Start OptInt `json:",omitempty,omitzero"`
}

// UsersGetUserAccessibleNodesParams is parameters of Users_getUserAccessibleNodes operation.
type UsersGetUserAccessibleNodesParams struct {
	// UUID of the user.
	UUID string
}

// UsersGetUserByIdParams is parameters of Users_getUserById operation.
type UsersGetUserByIdParams struct {
	// ID of the user.
	ID string
}

// UsersGetUserByShortUuidParams is parameters of Users_getUserByShortUuid operation.
type UsersGetUserByShortUuidParams struct {
	// Short UUID of the user.
	ShortUuid string
}

// UsersGetUserByTelegramIdParams is parameters of Users_getUserByTelegramId operation.
type UsersGetUserByTelegramIdParams struct {
	// Telegram ID of the user.
	TelegramId string
}

// UsersGetUserByUsernameParams is parameters of Users_getUserByUsername operation.
type UsersGetUserByUsernameParams struct {
	// Username of the user.
	Username string
}

// UsersGetUserByUuidParams is parameters of Users_getUserByUuid operation.
type UsersGetUserByUuidParams struct {
	// UUID of the user.
	UUID string
}

// UsersGetUserSubscriptionRequestHistoryParams is parameters of Users_getUserSubscriptionRequestHistory operation.
type UsersGetUserSubscriptionRequestHistoryParams struct {
	// UUID of the user.
	UUID string
}

// UsersGetUsersByEmailParams is parameters of Users_getUsersByEmail operation.
type UsersGetUsersByEmailParams struct {
	// Email of the user.
	Email string
}

// UsersGetUsersByTagParams is parameters of Users_getUsersByTag operation.
type UsersGetUsersByTagParams struct {
	// Tag of the user.
	Tag string
}

// UsersResetUserTrafficParams is parameters of Users_resetUserTraffic operation.
type UsersResetUserTrafficParams struct {
	// UUID of the user.
	UUID string
}

// UsersRevokeUserSubscriptionParams is parameters of Users_revokeUserSubscription operation.
type UsersRevokeUserSubscriptionParams struct {
	// UUID of the user.
	UUID string
}
