// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/google/uuid"
)

// ApiTokensControllerDeleteParams is parameters of ApiTokensController_delete operation.
type ApiTokensControllerDeleteParams struct {
	// UUID of the API token.
	UUID string
}

// ConfigProfileControllerDeleteConfigProfileByUuidParams is parameters of ConfigProfileController_deleteConfigProfileByUuid operation.
type ConfigProfileControllerDeleteConfigProfileByUuidParams struct {
	UUID string
}

// ConfigProfileControllerGetConfigProfileByUuidParams is parameters of ConfigProfileController_getConfigProfileByUuid operation.
type ConfigProfileControllerGetConfigProfileByUuidParams struct {
	UUID string
}

// ConfigProfileControllerGetInboundsByProfileUuidParams is parameters of ConfigProfileController_getInboundsByProfileUuid operation.
type ConfigProfileControllerGetInboundsByProfileUuidParams struct {
	UUID string
}

// ExternalSquadControllerAddUsersToExternalSquadParams is parameters of ExternalSquadController_addUsersToExternalSquad operation.
type ExternalSquadControllerAddUsersToExternalSquadParams struct {
	UUID string
}

// ExternalSquadControllerDeleteExternalSquadParams is parameters of ExternalSquadController_deleteExternalSquad operation.
type ExternalSquadControllerDeleteExternalSquadParams struct {
	UUID string
}

// ExternalSquadControllerGetExternalSquadByUuidParams is parameters of ExternalSquadController_getExternalSquadByUuid operation.
type ExternalSquadControllerGetExternalSquadByUuidParams struct {
	UUID string
}

// ExternalSquadControllerRemoveUsersFromExternalSquadParams is parameters of ExternalSquadController_removeUsersFromExternalSquad operation.
type ExternalSquadControllerRemoveUsersFromExternalSquadParams struct {
	UUID string
}

// HostsControllerDeleteHostParams is parameters of HostsController_deleteHost operation.
type HostsControllerDeleteHostParams struct {
	// UUID of the host.
	UUID string
}

// HostsControllerGetOneHostParams is parameters of HostsController_getOneHost operation.
type HostsControllerGetOneHostParams struct {
	// UUID of the host.
	UUID string
}

// HwidUserDevicesControllerGetAllUsersParams is parameters of HwidUserDevicesController_getAllUsers operation.
type HwidUserDevicesControllerGetAllUsersParams struct {
	// Page size for pagination.
	Size OptFloat64 `json:",omitempty,omitzero"`
	// Offset for pagination.
	Start OptFloat64 `json:",omitempty,omitzero"`
}

// HwidUserDevicesControllerGetUserHwidDevicesParams is parameters of HwidUserDevicesController_getUserHwidDevices operation.
type HwidUserDevicesControllerGetUserHwidDevicesParams struct {
	// UUID of the user.
	UserUuid string
}

// InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidParams is parameters of InfraBillingController_deleteInfraBillingHistoryRecordByUuid operation.
type InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidParams struct {
	UUID string
}

// InfraBillingControllerDeleteInfraBillingNodeByUuidParams is parameters of InfraBillingController_deleteInfraBillingNodeByUuid operation.
type InfraBillingControllerDeleteInfraBillingNodeByUuidParams struct {
	UUID string
}

// InfraBillingControllerDeleteInfraProviderByUuidParams is parameters of InfraBillingController_deleteInfraProviderByUuid operation.
type InfraBillingControllerDeleteInfraProviderByUuidParams struct {
	UUID string
}

// InfraBillingControllerGetInfraProviderByUuidParams is parameters of InfraBillingController_getInfraProviderByUuid operation.
type InfraBillingControllerGetInfraProviderByUuidParams struct {
	UUID string
}

// InternalSquadControllerAddUsersToInternalSquadParams is parameters of InternalSquadController_addUsersToInternalSquad operation.
type InternalSquadControllerAddUsersToInternalSquadParams struct {
	UUID string
}

// InternalSquadControllerDeleteInternalSquadParams is parameters of InternalSquadController_deleteInternalSquad operation.
type InternalSquadControllerDeleteInternalSquadParams struct {
	UUID string
}

// InternalSquadControllerGetInternalSquadAccessibleNodesParams is parameters of InternalSquadController_getInternalSquadAccessibleNodes operation.
type InternalSquadControllerGetInternalSquadAccessibleNodesParams struct {
	// UUID of the internal squad.
	UUID string
}

// InternalSquadControllerGetInternalSquadByUuidParams is parameters of InternalSquadController_getInternalSquadByUuid operation.
type InternalSquadControllerGetInternalSquadByUuidParams struct {
	UUID string
}

// InternalSquadControllerRemoveUsersFromInternalSquadParams is parameters of InternalSquadController_removeUsersFromInternalSquad operation.
type InternalSquadControllerRemoveUsersFromInternalSquadParams struct {
	UUID string
}

// NodesControllerDeleteNodeParams is parameters of NodesController_deleteNode operation.
type NodesControllerDeleteNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesControllerDisableNodeParams is parameters of NodesController_disableNode operation.
type NodesControllerDisableNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesControllerEnableNodeParams is parameters of NodesController_enableNode operation.
type NodesControllerEnableNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesControllerGetOneNodeParams is parameters of NodesController_getOneNode operation.
type NodesControllerGetOneNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesControllerRestartNodeParams is parameters of NodesController_restartNode operation.
type NodesControllerRestartNodeParams struct {
	// Node UUID.
	UUID string
}

// NodesUsageHistoryControllerGetNodesUsageByRangeParams is parameters of NodesUsageHistoryController_getNodesUsageByRange operation.
type NodesUsageHistoryControllerGetNodesUsageByRangeParams struct {
	// Start date.
	Start time.Time
	// End date.
	End time.Time
}

// NodesUserUsageHistoryControllerGetNodeUserUsageParams is parameters of NodesUserUsageHistoryController_getNodeUserUsage operation.
type NodesUserUsageHistoryControllerGetNodeUserUsageParams struct {
	// Start date.
	Start time.Time
	// End date.
	End time.Time
	// UUID of the node.
	UUID string
}

// SubscriptionControllerGetSubscriptionParams is parameters of SubscriptionController_getSubscription operation.
type SubscriptionControllerGetSubscriptionParams struct {
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionControllerGetSubscriptionByClientTypeParams is parameters of SubscriptionController_getSubscriptionByClientType operation.
type SubscriptionControllerGetSubscriptionByClientTypeParams struct {
	// Client type.
	ClientType SubscriptionControllerGetSubscriptionByClientTypeClientType
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionControllerGetSubscriptionInfoByShortUuidParams is parameters of SubscriptionController_getSubscriptionInfoByShortUuid operation.
type SubscriptionControllerGetSubscriptionInfoByShortUuidParams struct {
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionControllerGetSubscriptionWithTypeParams is parameters of SubscriptionController_getSubscriptionWithType operation.
type SubscriptionControllerGetSubscriptionWithTypeParams struct {
	// Subscription type (required if encodedTag is provided). Only SS is supported for now.
	Type string
	// Base64 encoded tag for Outline config. This paramter is optional. It is required only when type=ss.
	EncodedTag string
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionTemplateControllerDeleteTemplateParams is parameters of SubscriptionTemplateController_deleteTemplate operation.
type SubscriptionTemplateControllerDeleteTemplateParams struct {
	// Template UUID.
	UUID string
}

// SubscriptionTemplateControllerGetTemplateByUuidParams is parameters of SubscriptionTemplateController_getTemplateByUuid operation.
type SubscriptionTemplateControllerGetTemplateByUuidParams struct {
	// UUID of the subscription template.
	UUID uuid.UUID
}

// SubscriptionsControllerGetAllSubscriptionsParams is parameters of SubscriptionsController_getAllSubscriptions operation.
type SubscriptionsControllerGetAllSubscriptionsParams struct {
	// Number of subscriptions to return, no more than 500.
	Size OptFloat64 `json:",omitempty,omitzero"`
	// Start index (offset) of the users to return, default is 0.
	Start OptFloat64 `json:",omitempty,omitzero"`
}

// SubscriptionsControllerGetRawSubscriptionByShortUuidParams is parameters of SubscriptionsController_getRawSubscriptionByShortUuid operation.
type SubscriptionsControllerGetRawSubscriptionByShortUuidParams struct {
	// Include disabled hosts in the subscription. Default is false.
	WithDisabledHosts OptBool `json:",omitempty,omitzero"`
	// Short UUID of the user.
	ShortUuid string
}

// SubscriptionsControllerGetSubscriptionByShortUuidProtectedParams is parameters of SubscriptionsController_getSubscriptionByShortUuidProtected operation.
type SubscriptionsControllerGetSubscriptionByShortUuidProtectedParams struct {
	// Short uuid of the user.
	ShortUuid string
}

// SubscriptionsControllerGetSubscriptionByUsernameParams is parameters of SubscriptionsController_getSubscriptionByUsername operation.
type SubscriptionsControllerGetSubscriptionByUsernameParams struct {
	// Username of the user.
	Username string
}

// SubscriptionsControllerGetSubscriptionByUuidParams is parameters of SubscriptionsController_getSubscriptionByUuid operation.
type SubscriptionsControllerGetSubscriptionByUuidParams struct {
	// Uuid of the user.
	UUID string
}

// UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryParams is parameters of UserSubscriptionRequestHistoryController_getSubscriptionRequestHistory operation.
type UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryParams struct {
	// Page size for pagination.
	Size OptFloat64 `json:",omitempty,omitzero"`
	// Offset for pagination.
	Start OptFloat64 `json:",omitempty,omitzero"`
}

// UsersControllerDeleteUserParams is parameters of UsersController_deleteUser operation.
type UsersControllerDeleteUserParams struct {
	// UUID of the user.
	UUID string
}

// UsersControllerDisableUserParams is parameters of UsersController_disableUser operation.
type UsersControllerDisableUserParams struct {
	// UUID of the user.
	UUID string
}

// UsersControllerEnableUserParams is parameters of UsersController_enableUser operation.
type UsersControllerEnableUserParams struct {
	// UUID of the user.
	UUID string
}

// UsersControllerGetAllUsersParams is parameters of UsersController_getAllUsers operation.
type UsersControllerGetAllUsersParams struct {
	// Page size for pagination.
	Size OptFloat64 `json:",omitempty,omitzero"`
	// Offset for pagination.
	Start OptFloat64 `json:",omitempty,omitzero"`
}

// UsersControllerGetUserAccessibleNodesParams is parameters of UsersController_getUserAccessibleNodes operation.
type UsersControllerGetUserAccessibleNodesParams struct {
	// UUID of the user.
	UUID string
}

// UsersControllerGetUserByShortUuidParams is parameters of UsersController_getUserByShortUuid operation.
type UsersControllerGetUserByShortUuidParams struct {
	// Short UUID of the user.
	ShortUuid string
}

// UsersControllerGetUserByTelegramIdParams is parameters of UsersController_getUserByTelegramId operation.
type UsersControllerGetUserByTelegramIdParams struct {
	// Telegram ID of the user.
	TelegramId string
}

// UsersControllerGetUserByUsernameParams is parameters of UsersController_getUserByUsername operation.
type UsersControllerGetUserByUsernameParams struct {
	// Username of the user.
	Username string
}

// UsersControllerGetUserByUuidParams is parameters of UsersController_getUserByUuid operation.
type UsersControllerGetUserByUuidParams struct {
	// UUID of the user.
	UUID string
}

// UsersControllerGetUserSubscriptionRequestHistoryParams is parameters of UsersController_getUserSubscriptionRequestHistory operation.
type UsersControllerGetUserSubscriptionRequestHistoryParams struct {
	// UUID of the user.
	UUID string
}

// UsersControllerGetUsersByEmailParams is parameters of UsersController_getUsersByEmail operation.
type UsersControllerGetUsersByEmailParams struct {
	// Email of the user.
	Email string
}

// UsersControllerGetUsersByTagParams is parameters of UsersController_getUsersByTag operation.
type UsersControllerGetUsersByTagParams struct {
	// Tag of the user.
	Tag string
}

// UsersControllerResetUserTrafficParams is parameters of UsersController_resetUserTraffic operation.
type UsersControllerResetUserTrafficParams struct {
	// UUID of the user.
	UUID string
}

// UsersControllerRevokeUserSubscriptionParams is parameters of UsersController_revokeUserSubscription operation.
type UsersControllerRevokeUserSubscriptionParams struct {
	// UUID of the user.
	UUID string
}

// UsersStatsControllerGetUserUsageByRangeParams is parameters of UsersStatsController_getUserUsageByRange operation.
type UsersStatsControllerGetUserUsageByRangeParams struct {
	// Start date.
	Start time.Time
	// End date.
	End time.Time
	// UUID of the user.
	UUID string
}
