// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"net/url"
	"time"

	"github.com/google/uuid"
)

// SetFake set fake values.
func (s *ActiveInternalSquad) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *AllHwidDevices) SetFake() {
	{
		{
			s.Devices = nil
			for i := 0; i < 0; i++ {
				var elem Device
				{
					elem.SetFake()
				}
				s.Devices = append(s.Devices, elem)
			}
		}
	}
	{
		{
			s.Total = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *BadRequestError) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
	{
		{
			s.StatusCode = float64(0)
		}
	}
	{
		{
			s.Errors = nil
			for i := 0; i < 0; i++ {
				var elem ValidationError
				{
					elem.SetFake()
				}
				s.Errors = append(s.Errors, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *BandwidthLastTwoDays) SetFake() {
	{
		{
			s.Current = "string"
		}
	}
	{
		{
			s.Previous = "string"
		}
	}
	{
		{
			s.Difference = "string"
		}
	}
}

// SetFake set fake values.
func (s *BillingHistoryItem) SetFake() {
	{
		{
			s.TotalAmount = float64(0)
		}
	}
	{
		{
			s.TotalBills = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *BillingHistoryResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BillingHistoryResponseResponse) SetFake() {
	{
		{
			s.Records = nil
			for i := 0; i < 0; i++ {
				var elem BillingHistoryResponseResponseRecordsItem
				{
					elem.SetFake()
				}
				s.Records = append(s.Records, elem)
			}
		}
	}
	{
		{
			s.Total = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *BillingHistoryResponseResponseRecordsItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.ProviderUuid = uuid.New()
		}
	}
	{
		{
			s.Amount = float64(0)
		}
	}
	{
		{
			s.BilledAt = time.Now()
		}
	}
	{
		{
			s.Provider.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BillingHistoryResponseResponseRecordsItemProvider) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.FaviconLink.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BillingNode) SetFake() {
	{
		{
			s.NodeUuid = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
}

// SetFake set fake values.
func (s *BillingNodesResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BillingNodesResponseResponse) SetFake() {
	{
		{
			s.TotalBillingNodes = float64(0)
		}
	}
	{
		{
			s.BillingNodes = nil
			for i := 0; i < 0; i++ {
				var elem BillingNodesResponseResponseBillingNodesItem
				{
					elem.SetFake()
				}
				s.BillingNodes = append(s.BillingNodes, elem)
			}
		}
	}
	{
		{
			s.AvailableBillingNodes = nil
			for i := 0; i < 0; i++ {
				var elem Node
				{
					elem.SetFake()
				}
				s.AvailableBillingNodes = append(s.AvailableBillingNodes, elem)
			}
		}
	}
	{
		{
			s.TotalAvailableBillingNodes = float64(0)
		}
	}
	{
		{
			s.Stats.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BillingNodesResponseResponseBillingNodesItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.NodeUuid = uuid.New()
		}
	}
	{
		{
			s.ProviderUuid = uuid.New()
		}
	}
	{
		{
			s.Provider.SetFake()
		}
	}
	{
		{
			s.Node.SetFake()
		}
	}
	{
		{
			s.NextBillingAt = time.Now()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *BillingNodesResponseResponseBillingNodesItemProvider) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.LoginUrl.SetFake()
		}
	}
	{
		{
			s.FaviconLink.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BillingNodesResponseResponseStats) SetFake() {
	{
		{
			s.UpcomingNodesCount = float64(0)
		}
	}
	{
		{
			s.CurrentMonthPayments = float64(0)
		}
	}
	{
		{
			s.TotalSpent = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *BrandingSettings) SetFake() {
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.LogoUrl.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BulkActionResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BulkActionResponseResponse) SetFake() {
	{
		{
			s.AffectedRows = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *BulkAllUpdateUsersRequestDto) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.TrafficLimitStrategy.SetFake()
		}
	}
	{
		{
			s.ExpireAt.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.TelegramId.SetFake()
		}
	}
	{
		{
			s.Email.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.HwidDeviceLimit.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BulkAllUpdateUsersRequestDtoStatus) SetFake() {
	*s = BulkAllUpdateUsersRequestDtoStatusACTIVE
}

// SetFake set fake values.
func (s *BulkAllUpdateUsersRequestDtoTrafficLimitStrategy) SetFake() {
	*s = BulkAllUpdateUsersRequestDtoTrafficLimitStrategyNORESET
}

// SetFake set fake values.
func (s *BulkDeleteUsersByStatusRequestDto) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BulkDeleteUsersByStatusRequestDtoStatus) SetFake() {
	*s = BulkDeleteUsersByStatusRequestDtoStatusACTIVE
}

// SetFake set fake values.
func (s *BulkUpdateUsersRequestDto) SetFake() {
	{
		{
			s.Uuids = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Uuids = append(s.Uuids, elem)
			}
		}
	}
	{
		{
			s.Fields.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BulkUpdateUsersRequestDtoFields) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.TrafficLimitStrategy.SetFake()
		}
	}
	{
		{
			s.ExpireAt.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.TelegramId.SetFake()
		}
	}
	{
		{
			s.Email.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.HwidDeviceLimit.SetFake()
		}
	}
	{
		{
			s.ExternalSquadUuid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BulkUpdateUsersRequestDtoFieldsStatus) SetFake() {
	*s = BulkUpdateUsersRequestDtoFieldsStatusACTIVE
}

// SetFake set fake values.
func (s *BulkUpdateUsersRequestDtoFieldsTrafficLimitStrategy) SetFake() {
	*s = BulkUpdateUsersRequestDtoFieldsTrafficLimitStrategyNORESET
}

// SetFake set fake values.
func (s *BulkUpdateUsersSquadsRequestDto) SetFake() {
	{
		{
			s.Uuids = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Uuids = append(s.Uuids, elem)
			}
		}
	}
	{
		{
			s.ActiveInternalSquads = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.ActiveInternalSquads = append(s.ActiveInternalSquads, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *BulkUuidsRequest) SetFake() {
	{
		{
			s.Uuids = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Uuids = append(s.Uuids, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ByAppItem) SetFake() {
	{
		{
			s.App = "string"
		}
	}
	{
		{
			s.Count = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *Condition) SetFake() {
	{
		{
			s.HeaderName = "string"
		}
	}
	{
		{
			s.Operator.SetFake()
		}
	}
	{
		{
			s.Value = "string"
		}
	}
	{
		{
			s.CaseSensitive = true
		}
	}
}

// SetFake set fake values.
func (s *ConditionOperator) SetFake() {
	*s = ConditionOperatorEQUALS
}

// SetFake set fake values.
func (s *ConfigProfile) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Config = []byte("null")
		}
	}
	{
		{
			s.Inbounds = nil
			for i := 0; i < 0; i++ {
				var elem Inbound
				{
					elem.SetFake()
				}
				s.Inbounds = append(s.Inbounds, elem)
			}
		}
	}
	{
		{
			s.Nodes = nil
			for i := 0; i < 0; i++ {
				var elem Node
				{
					elem.SetFake()
				}
				s.Nodes = append(s.Nodes, elem)
			}
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *ConfigProfileItem) SetFake() {
	{
		{
			s.ActiveConfigProfileUuid.SetFake()
		}
	}
	{
		{
			s.ActiveInbounds = nil
			for i := 0; i < 0; i++ {
				var elem Inbound
				{
					elem.SetFake()
				}
				s.ActiveInbounds = append(s.ActiveInbounds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ConfigProfileRef) SetFake() {
	{
		{
			s.ActiveConfigProfileUuid = uuid.New()
		}
	}
	{
		{
			s.ActiveInbounds = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.ActiveInbounds = append(s.ActiveInbounds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ConfigProfileResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateApiTokenRequestDto) SetFake() {
	{
		{
			s.TokenName = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateApiTokenResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateApiTokenResponseDtoResponse) SetFake() {
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.UUID = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateConfigProfileRequestDto) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Config.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateConfigProfileRequestDtoConfig) SetFake() {
}

// SetFake set fake values.
func (s *CreateExternalSquadRequestDto) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateHostRequestDto) SetFake() {
	{
		{
			s.Inbound.SetFake()
		}
	}
	{
		{
			s.Remark = "string"
		}
	}
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Path.SetFake()
		}
	}
	{
		{
			s.Sni.SetFake()
		}
	}
	{
		{
			s.Host.SetFake()
		}
	}
	{
		{
			s.Alpn.SetFake()
		}
	}
	{
		{
			s.Fingerprint.SetFake()
		}
	}
	{
		{
			s.IsDisabled.SetFake()
		}
	}
	{
		{
			s.SecurityLayer.SetFake()
		}
	}
	{
		{
			s.XHttpExtraParams = []byte("null")
		}
	}
	{
		{
			s.MuxParams = []byte("null")
		}
	}
	{
		{
			s.SockoptParams = []byte("null")
		}
	}
	{
		{
			s.ServerDescription.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.IsHidden.SetFake()
		}
	}
	{
		{
			s.OverrideSniFromAddress.SetFake()
		}
	}
	{
		{
			s.AllowInsecure.SetFake()
		}
	}
	{
		{
			s.VlessRouteId.SetFake()
		}
	}
	{
		{
			s.ShuffleHost.SetFake()
		}
	}
	{
		{
			s.MihomoX25519.SetFake()
		}
	}
	{
		{
			s.Nodes = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Nodes = append(s.Nodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateHostRequestDtoAlpn) SetFake() {
	*s = CreateHostRequestDtoAlpnH3
}

// SetFake set fake values.
func (s *CreateHostRequestDtoFingerprint) SetFake() {
	*s = CreateHostRequestDtoFingerprintChrome
}

// SetFake set fake values.
func (s *CreateHostRequestDtoSecurityLayer) SetFake() {
	*s = CreateHostRequestDtoSecurityLayerDEFAULT
}

// SetFake set fake values.
func (s *CreateInfraBillingHistoryRecordRequestDto) SetFake() {
	{
		{
			s.ProviderUuid = uuid.New()
		}
	}
	{
		{
			s.Amount = float64(0)
		}
	}
	{
		{
			s.BilledAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *CreateInfraBillingNodeRequestDto) SetFake() {
	{
		{
			s.ProviderUuid = uuid.New()
		}
	}
	{
		{
			s.NodeUuid = uuid.New()
		}
	}
	{
		{
			s.NextBillingAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateInfraProviderRequestDto) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.FaviconLink.SetFake()
		}
	}
	{
		{
			s.LoginUrl.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateInternalSquadRequestDto) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Inbounds = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Inbounds = append(s.Inbounds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateNodeRequestDto) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.IsTrafficTrackingActive.SetFake()
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.NotifyPercent.SetFake()
		}
	}
	{
		{
			s.TrafficResetDay.SetFake()
		}
	}
	{
		{
			s.CountryCode.SetFake()
		}
	}
	{
		{
			s.ConsumptionMultiplier.SetFake()
		}
	}
	{
		{
			s.ConfigProfile.SetFake()
		}
	}
	{
		{
			s.ProviderUuid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateSubscriptionTemplateRequestDto) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.TemplateType.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateSubscriptionTemplateRequestDtoTemplateType) SetFake() {
	*s = CreateSubscriptionTemplateRequestDtoTemplateTypeXRAYJSON
}

// SetFake set fake values.
func (s *CreateUserHwidDeviceRequestDto) SetFake() {
	{
		{
			s.Hwid = "string"
		}
	}
	{
		{
			s.UserUuid = uuid.New()
		}
	}
	{
		{
			s.Platform.SetFake()
		}
	}
	{
		{
			s.OsVersion.SetFake()
		}
	}
	{
		{
			s.DeviceModel.SetFake()
		}
	}
	{
		{
			s.UserAgent.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateUserRequestDto) SetFake() {
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ShortUuid.SetFake()
		}
	}
	{
		{
			s.TrojanPassword.SetFake()
		}
	}
	{
		{
			s.VlessUuid.SetFake()
		}
	}
	{
		{
			s.SsPassword.SetFake()
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.TrafficLimitStrategy.SetFake()
		}
	}
	{
		{
			s.ExpireAt = time.Now()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.LastTrafficResetAt.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.TelegramId.SetFake()
		}
	}
	{
		{
			s.Email.SetFake()
		}
	}
	{
		{
			s.HwidDeviceLimit.SetFake()
		}
	}
	{
		{
			s.ActiveInternalSquads = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.ActiveInternalSquads = append(s.ActiveInternalSquads, elem)
			}
		}
	}
	{
		{
			s.UUID.SetFake()
		}
	}
	{
		{
			s.ExternalSquadUuid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateUserRequestDtoStatus) SetFake() {
	*s = CreateUserRequestDtoStatusACTIVE
}

// SetFake set fake values.
func (s *CreateUserRequestDtoTrafficLimitStrategy) SetFake() {
	*s = CreateUserRequestDtoTrafficLimitStrategyNORESET
}

// SetFake set fake values.
func (s *DebugSrrMatcherRequestDto) SetFake() {
	{
		{
			s.ResponseRules.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DebugSrrMatcherResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DebugSrrMatcherResponseDtoResponse) SetFake() {
	{
		{
			s.Matched = true
		}
	}
	{
		{
			s.ResponseType.SetFake()
		}
	}
	{
		{
			s.MatchedRule.SetFake()
		}
	}
	{
		{
			s.InputHeaders.SetFake()
		}
	}
	{
		{
			s.OutputHeaders.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DebugSrrMatcherResponseDtoResponseInputHeaders) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *DebugSrrMatcherResponseDtoResponseOutputHeaders) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *DebugSrrMatcherResponseDtoResponseResponseType) SetFake() {
	*s = DebugSrrMatcherResponseDtoResponseResponseTypeXRAYJSON
}

// SetFake set fake values.
func (s *DeleteAllUserHwidDevicesRequestDto) SetFake() {
	{
		{
			s.UserUuid = uuid.New()
		}
	}
}

// SetFake set fake values.
func (s *DeleteApiTokenResponseDto) SetFake() {
	{
		{
			s.Response = true
		}
	}
}

// SetFake set fake values.
func (s *DeletePasskeyRequestDto) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DeleteResponseResponse) SetFake() {
	{
		{
			s.IsDeleted = true
		}
	}
}

// SetFake set fake values.
func (s *DeleteSnippetRequestDto) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteUserHwidDeviceRequestDto) SetFake() {
	{
		{
			s.UserUuid = uuid.New()
		}
	}
	{
		{
			s.Hwid = "string"
		}
	}
}

// SetFake set fake values.
func (s *Device) SetFake() {
	{
		{
			s.Hwid = "string"
		}
	}
	{
		{
			s.UserUuid = uuid.New()
		}
	}
	{
		{
			s.Platform.SetFake()
		}
	}
	{
		{
			s.OsVersion.SetFake()
		}
	}
	{
		{
			s.DeviceModel.SetFake()
		}
	}
	{
		{
			s.UserAgent.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *EncryptHappCryptoLinkRequestDto) SetFake() {
	{
		{
			s.LinkToEncrypt = url.URL{Scheme: "https", Host: "github.com", Path: "/ogen-go/ogen"}
		}
	}
}

// SetFake set fake values.
func (s *EncryptHappCryptoLinkResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *EncryptHappCryptoLinkResponseDtoResponse) SetFake() {
	{
		{
			s.EncryptedLink = "string"
		}
	}
}

// SetFake set fake values.
func (s *EventResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *EventResponseResponse) SetFake() {
	{
		{
			s.EventSent = true
		}
	}
}

// SetFake set fake values.
func (s *ExternalSquad) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Info.SetFake()
		}
	}
	{
		{
			s.Templates = nil
			for i := 0; i < 0; i++ {
				var elem TemplateRef
				{
					elem.SetFake()
				}
				s.Templates = append(s.Templates, elem)
			}
		}
	}
	{
		{
			s.SubscriptionSettings.SetFake()
		}
	}
	{
		{
			s.HostOverrides.SetFake()
		}
	}
	{
		{
			s.ResponseHeaders.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *ExternalSquadResponseHeaders) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *ExternalSquadResponseResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ExternalSquadsInfoItem) SetFake() {
	{
		{
			s.MembersCount = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *FindAllApiTokensResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *FindAllApiTokensResponseDtoResponse) SetFake() {
	{
		{
			s.ApiKeys = nil
			for i := 0; i < 0; i++ {
				var elem FindAllApiTokensResponseDtoResponseApiKeysItem
				{
					elem.SetFake()
				}
				s.ApiKeys = append(s.ApiKeys, elem)
			}
		}
	}
	{
		{
			s.Docs.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *FindAllApiTokensResponseDtoResponseApiKeysItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.TokenName = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *FindAllApiTokensResponseDtoResponseDocs) SetFake() {
	{
		{
			s.IsDocsEnabled = true
		}
	}
	{
		{
			s.ScalarPath.SetFake()
		}
	}
	{
		{
			s.SwaggerPath.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ForbiddenError) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
	{
		{
			s.StatusCode = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GenerateX25519ResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GenerateX25519ResponseDtoResponse) SetFake() {
	{
		{
			s.Keypairs = nil
			for i := 0; i < 0; i++ {
				var elem GenerateX25519ResponseDtoResponseKeypairsItem
				{
					elem.SetFake()
				}
				s.Keypairs = append(s.Keypairs, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GenerateX25519ResponseDtoResponseKeypairsItem) SetFake() {
	{
		{
			s.PublicKey = "string"
		}
	}
	{
		{
			s.PrivateKey = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetAllHwidDevicesResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetAllSubscriptionsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetAllSubscriptionsResponseDtoResponse) SetFake() {
	{
		{
			s.Subscriptions = nil
			for i := 0; i < 0; i++ {
				var elem GetAllSubscriptionsResponseDtoResponseSubscriptionsItem
				{
					elem.SetFake()
				}
				s.Subscriptions = append(s.Subscriptions, elem)
			}
		}
	}
	{
		{
			s.Total = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetAllSubscriptionsResponseDtoResponseSubscriptionsItem) SetFake() {
	{
		{
			s.IsFound = true
		}
	}
	{
		{
			s.User.SetFake()
		}
	}
	{
		{
			s.Links = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Links = append(s.Links, elem)
			}
		}
	}
	{
		{
			s.SsConfLinks.SetFake()
		}
	}
	{
		{
			s.SubscriptionUrl = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetAllSubscriptionsResponseDtoResponseSubscriptionsItemSsConfLinks) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUser) SetFake() {
	{
		{
			s.ShortUuid = "string"
		}
	}
	{
		{
			s.DaysLeft = float64(0)
		}
	}
	{
		{
			s.TrafficUsed = "string"
		}
	}
	{
		{
			s.TrafficLimit = "string"
		}
	}
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.ExpiresAt = time.Now()
		}
	}
	{
		{
			s.IsActive = true
		}
	}
	{
		{
			s.UserStatus.SetFake()
		}
	}
	{
		{
			s.TrafficLimitStrategy.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserTrafficLimitStrategy) SetFake() {
	*s = GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserTrafficLimitStrategyNORESET
}

// SetFake set fake values.
func (s *GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserUserStatus) SetFake() {
	*s = GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserUserStatusACTIVE
}

// SetFake set fake values.
func (s *GetAllUsersResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetAllUsersResponseDtoResponse) SetFake() {
	{
		{
			s.Users = nil
			for i := 0; i < 0; i++ {
				var elem User
				{
					elem.SetFake()
				}
				s.Users = append(s.Users, elem)
			}
		}
	}
	{
		{
			s.Total = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetBandwidthStatsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetBandwidthStatsResponseDtoResponse) SetFake() {
	{
		{
			s.BandwidthLastTwoDays.SetFake()
		}
	}
	{
		{
			s.BandwidthLastSevenDays.SetFake()
		}
	}
	{
		{
			s.BandwidthLast30Days.SetFake()
		}
	}
	{
		{
			s.BandwidthCalendarMonth.SetFake()
		}
	}
	{
		{
			s.BandwidthCurrentYear.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetConfigProfilesResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetConfigProfilesResponseDtoResponse) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.ConfigProfiles = nil
			for i := 0; i < 0; i++ {
				var elem ConfigProfile
				{
					elem.SetFake()
				}
				s.ConfigProfiles = append(s.ConfigProfiles, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetExternalSquadsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetExternalSquadsResponseDtoResponse) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.ExternalSquads = nil
			for i := 0; i < 0; i++ {
				var elem ExternalSquad
				{
					elem.SetFake()
				}
				s.ExternalSquads = append(s.ExternalSquads, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetHwidDevicesStatsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetHwidDevicesStatsResponseDtoResponse) SetFake() {
	{
		{
			s.ByPlatform = nil
			for i := 0; i < 0; i++ {
				var elem GetHwidDevicesStatsResponseDtoResponseByPlatformItem
				{
					elem.SetFake()
				}
				s.ByPlatform = append(s.ByPlatform, elem)
			}
		}
	}
	{
		{
			s.ByApp = nil
			for i := 0; i < 0; i++ {
				var elem ByAppItem
				{
					elem.SetFake()
				}
				s.ByApp = append(s.ByApp, elem)
			}
		}
	}
	{
		{
			s.Stats.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetHwidDevicesStatsResponseDtoResponseByPlatformItem) SetFake() {
	{
		{
			s.Platform = "string"
		}
	}
	{
		{
			s.Count = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetHwidDevicesStatsResponseDtoResponseStats) SetFake() {
	{
		{
			s.TotalUniqueDevices = float64(0)
		}
	}
	{
		{
			s.TotalHwidDevices = float64(0)
		}
	}
	{
		{
			s.AverageHwidDevicesPerUser = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetInfraProvidersResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetInfraProvidersResponseDtoResponse) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Providers = nil
			for i := 0; i < 0; i++ {
				var elem Provider
				{
					elem.SetFake()
				}
				s.Providers = append(s.Providers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetInternalSquadAccessibleNodesResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetInternalSquadAccessibleNodesResponseDtoResponse) SetFake() {
	{
		{
			s.SquadUuid = uuid.New()
		}
	}
	{
		{
			s.AccessibleNodes = nil
			for i := 0; i < 0; i++ {
				var elem GetInternalSquadAccessibleNodesResponseDtoResponseAccessibleNodesItem
				{
					elem.SetFake()
				}
				s.AccessibleNodes = append(s.AccessibleNodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetInternalSquadAccessibleNodesResponseDtoResponseAccessibleNodesItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
	{
		{
			s.ConfigProfileUuid = uuid.New()
		}
	}
	{
		{
			s.ConfigProfileName = "string"
		}
	}
	{
		{
			s.ActiveInbounds = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.ActiveInbounds = append(s.ActiveInbounds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetInternalSquadsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetInternalSquadsResponseDtoResponse) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.InternalSquads = nil
			for i := 0; i < 0; i++ {
				var elem InternalSquad
				{
					elem.SetFake()
				}
				s.InternalSquads = append(s.InternalSquads, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetNodeUserUsageByRangeResponseDto) SetFake() {
	{
		{
			s.Response = nil
			for i := 0; i < 0; i++ {
				var elem GetNodeUserUsageByRangeResponseDtoResponseItem
				{
					elem.SetFake()
				}
				s.Response = append(s.Response, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetNodeUserUsageByRangeResponseDtoResponseItem) SetFake() {
	{
		{
			s.UserUuid = uuid.New()
		}
	}
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.NodeUuid = uuid.New()
		}
	}
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Date = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetNodesMetricsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetNodesMetricsResponseDtoResponse) SetFake() {
	{
		{
			s.Nodes = nil
			for i := 0; i < 0; i++ {
				var elem GetNodesMetricsResponseDtoResponseNodesItem
				{
					elem.SetFake()
				}
				s.Nodes = append(s.Nodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetNodesMetricsResponseDtoResponseNodesItem) SetFake() {
	{
		{
			s.NodeUuid = "string"
		}
	}
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.CountryEmoji = "string"
		}
	}
	{
		{
			s.ProviderName = "string"
		}
	}
	{
		{
			s.UsersOnline = float64(0)
		}
	}
	{
		{
			s.InboundsStats = nil
			for i := 0; i < 0; i++ {
				var elem InboundsStat
				{
					elem.SetFake()
				}
				s.InboundsStats = append(s.InboundsStats, elem)
			}
		}
	}
	{
		{
			s.OutboundsStats = nil
			for i := 0; i < 0; i++ {
				var elem InboundsStat
				{
					elem.SetFake()
				}
				s.OutboundsStats = append(s.OutboundsStats, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetNodesRealtimeUsageResponseDto) SetFake() {
	{
		{
			s.Response = nil
			for i := 0; i < 0; i++ {
				var elem GetNodesRealtimeUsageResponseDtoResponseItem
				{
					elem.SetFake()
				}
				s.Response = append(s.Response, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetNodesRealtimeUsageResponseDtoResponseItem) SetFake() {
	{
		{
			s.NodeUuid = uuid.New()
		}
	}
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
	{
		{
			s.DownloadBytes = float64(0)
		}
	}
	{
		{
			s.UploadBytes = float64(0)
		}
	}
	{
		{
			s.TotalBytes = float64(0)
		}
	}
	{
		{
			s.DownloadSpeedBps = float64(0)
		}
	}
	{
		{
			s.UploadSpeedBps = float64(0)
		}
	}
	{
		{
			s.TotalSpeedBps = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetNodesStatisticsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetNodesStatisticsResponseDtoResponse) SetFake() {
	{
		{
			s.LastSevenDays = nil
			for i := 0; i < 0; i++ {
				var elem GetNodesStatisticsResponseDtoResponseLastSevenDaysItem
				{
					elem.SetFake()
				}
				s.LastSevenDays = append(s.LastSevenDays, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetNodesStatisticsResponseDtoResponseLastSevenDaysItem) SetFake() {
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.Date = "string"
		}
	}
	{
		{
			s.TotalBytes = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetNodesUsageByRangeResponseDto) SetFake() {
	{
		{
			s.Response = nil
			for i := 0; i < 0; i++ {
				var elem GetNodesUsageByRangeResponseDtoResponseItem
				{
					elem.SetFake()
				}
				s.Response = append(s.Response, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetNodesUsageByRangeResponseDtoResponseItem) SetFake() {
	{
		{
			s.NodeUuid = uuid.New()
		}
	}
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.NodeCountryCode = "string"
		}
	}
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.TotalDownload = float64(0)
		}
	}
	{
		{
			s.TotalUpload = float64(0)
		}
	}
	{
		{
			s.HumanReadableTotal = "string"
		}
	}
	{
		{
			s.HumanReadableTotalDownload = "string"
		}
	}
	{
		{
			s.HumanReadableTotalUpload = "string"
		}
	}
	{
		{
			s.Date = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetPubKeyResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetPubKeyResponseDtoResponse) SetFake() {
	{
		{
			s.PubKey = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponse) SetFake() {
	{
		{
			s.User.SetFake()
		}
	}
	{
		{
			s.ConvertedUserInfo.SetFake()
		}
	}
	{
		{
			s.Headers.SetFake()
		}
	}
	{
		{
			s.RawHosts = nil
			for i := 0; i < 0; i++ {
				var elem GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItem
				{
					elem.SetFake()
				}
				s.RawHosts = append(s.RawHosts, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseConvertedUserInfo) SetFake() {
	{
		{
			s.DaysLeft = float64(0)
		}
	}
	{
		{
			s.TrafficLimit = "string"
		}
	}
	{
		{
			s.TrafficUsed = "string"
		}
	}
	{
		{
			s.LifetimeTrafficUsed = "string"
		}
	}
	{
		{
			s.IsHwidLimited = true
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseHeaders) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItem) SetFake() {
	{
		{
			s.Address.SetFake()
		}
	}
	{
		{
			s.Alpn.SetFake()
		}
	}
	{
		{
			s.Fingerprint.SetFake()
		}
	}
	{
		{
			s.Host.SetFake()
		}
	}
	{
		{
			s.Network.SetFake()
		}
	}
	{
		{
			s.Password.SetFake()
		}
	}
	{
		{
			s.Path.SetFake()
		}
	}
	{
		{
			s.PublicKey.SetFake()
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.Protocol.SetFake()
		}
	}
	{
		{
			s.Remark.SetFake()
		}
	}
	{
		{
			s.ShortId.SetFake()
		}
	}
	{
		{
			s.Sni.SetFake()
		}
	}
	{
		{
			s.SpiderX.SetFake()
		}
	}
	{
		{
			s.TLS.SetFake()
		}
	}
	{
		{
			s.HeaderType.SetFake()
		}
	}
	{
		{
			s.AdditionalParams.SetFake()
		}
	}
	{
		{
			s.XHttpExtraParams.SetFake()
		}
	}
	{
		{
			s.MuxParams.SetFake()
		}
	}
	{
		{
			s.SockoptParams.SetFake()
		}
	}
	{
		{
			s.ServerDescription.SetFake()
		}
	}
	{
		{
			s.Flow.SetFake()
		}
	}
	{
		{
			s.AllowInsecure.SetFake()
		}
	}
	{
		{
			s.ShuffleHost.SetFake()
		}
	}
	{
		{
			s.MihomoX25519.SetFake()
		}
	}
	{
		{
			s.Mldsa65Verify.SetFake()
		}
	}
	{
		{
			s.Encryption.SetFake()
		}
	}
	{
		{
			s.ProtocolOptions.SetFake()
		}
	}
	{
		{
			s.DbData.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemAdditionalParams) SetFake() {
	{
		{
			s.Mode.SetFake()
		}
	}
	{
		{
			s.HeartbeatPeriod.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbData) SetFake() {
	{
		{ // Keep pointer nil to prevent infinite recursion.
			s.RawInbound = nil
		}
	}
	{
		{
			s.InboundTag = "string"
		}
	}
	{
		{
			s.UUID = "string"
		}
	}
	{
		{
			s.ConfigProfileUuid.SetFake()
		}
	}
	{
		{
			s.ConfigProfileInboundUuid.SetFake()
		}
	}
	{
		{
			s.IsDisabled = true
		}
	}
	{
		{
			s.ViewPosition = float64(0)
		}
	}
	{
		{
			s.Remark = "string"
		}
	}
	{
		{
			s.IsHidden = true
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.VlessRouteId.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbDataRawInbound) SetFake() {
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemMuxParams) SetFake() {
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemPassword) SetFake() {
	{
		{
			s.SsPassword = "string"
		}
	}
	{
		{
			s.TrojanPassword = "string"
		}
	}
	{
		{
			s.VlessPassword = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptions) SetFake() {
	{
		{
			s.Ss.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptionsSs) SetFake() {
	{
		{
			s.Method.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemSockoptParams) SetFake() {
}

// SetFake set fake values.
func (s *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemXHttpExtraParams) SetFake() {
}

// SetFake set fake values.
func (s *GetRemnawaveHealthResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetRemnawaveHealthResponseDtoResponse) SetFake() {
	{
		{
			s.Pm2Stats = nil
			for i := 0; i < 0; i++ {
				var elem GetRemnawaveHealthResponseDtoResponsePm2StatsItem
				{
					elem.SetFake()
				}
				s.Pm2Stats = append(s.Pm2Stats, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetRemnawaveHealthResponseDtoResponsePm2StatsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Memory = "string"
		}
	}
	{
		{
			s.CPU = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDtoResponse) SetFake() {
	{
		{
			s.CPU.SetFake()
		}
	}
	{
		{
			s.Memory.SetFake()
		}
	}
	{
		{
			s.Uptime = float64(0)
		}
	}
	{
		{
			s.Timestamp = float64(0)
		}
	}
	{
		{
			s.Users.SetFake()
		}
	}
	{
		{
			s.OnlineStats.SetFake()
		}
	}
	{
		{
			s.Nodes.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDtoResponseCPU) SetFake() {
	{
		{
			s.Cores = float64(0)
		}
	}
	{
		{
			s.PhysicalCores = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDtoResponseMemory) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Free = float64(0)
		}
	}
	{
		{
			s.Used = float64(0)
		}
	}
	{
		{
			s.Active = float64(0)
		}
	}
	{
		{
			s.Available = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDtoResponseNodes) SetFake() {
	{
		{
			s.TotalOnline = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDtoResponseOnlineStats) SetFake() {
	{
		{
			s.LastDay = float64(0)
		}
	}
	{
		{
			s.LastWeek = float64(0)
		}
	}
	{
		{
			s.NeverOnline = float64(0)
		}
	}
	{
		{
			s.OnlineNow = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDtoResponseUsers) SetFake() {
	{
		{
			s.StatusCounts.SetFake()
		}
	}
	{
		{
			s.TotalUsers = float64(0)
		}
	}
	{
		{
			s.TotalTrafficBytes = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetStatsResponseDtoResponseUsersStatusCounts) SetFake() {
	var (
		elem float64
		m    map[string]float64 = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *GetStatusResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetStatusResponseDtoResponse) SetFake() {
	{
		{
			s.IsLoginAllowed = true
		}
	}
	{
		{
			s.IsRegisterAllowed = true
		}
	}
	{
		{
			s.Authentication.SetFake()
		}
	}
	{
		{
			s.Branding.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetStatusResponseDtoResponseAuthentication) SetFake() {
	{
		{
			s.Passkey.SetFake()
		}
	}
	{
		{
			s.TgAuth.SetFake()
		}
	}
	{
		{
			s.OAuth2.SetFake()
		}
	}
	{
		{
			s.Password.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetStatusResponseDtoResponseAuthenticationOAuth2) SetFake() {
	{
		{
			s.Providers.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetStatusResponseDtoResponseAuthenticationOAuth2Providers) SetFake() {
	var (
		elem bool
		m    map[string]bool = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *GetStatusResponseDtoResponseAuthenticationTgAuth) SetFake() {
	{
		{
			s.Enabled = true
		}
	}
	{
		{
			s.BotId.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetStatusResponseDtoResponseBranding) SetFake() {
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.LogoUrl.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetSubscriptionRequestHistoryResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetSubscriptionRequestHistoryStatsResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetSubscriptionRequestHistoryStatsResponseDtoResponse) SetFake() {
	{
		{
			s.ByParsedApp = nil
			for i := 0; i < 0; i++ {
				var elem ByAppItem
				{
					elem.SetFake()
				}
				s.ByParsedApp = append(s.ByParsedApp, elem)
			}
		}
	}
	{
		{
			s.HourlyRequestStats = nil
			for i := 0; i < 0; i++ {
				var elem GetSubscriptionRequestHistoryStatsResponseDtoResponseHourlyRequestStatsItem
				{
					elem.SetFake()
				}
				s.HourlyRequestStats = append(s.HourlyRequestStats, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetSubscriptionRequestHistoryStatsResponseDtoResponseHourlyRequestStatsItem) SetFake() {
	{
		{
			s.DateTime = time.Now()
		}
	}
	{
		{
			s.RequestCount = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *GetTemplatesResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetTemplatesResponseDtoResponse) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Templates = nil
			for i := 0; i < 0; i++ {
				var elem Template
				{
					elem.SetFake()
				}
				s.Templates = append(s.Templates, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetUserAccessibleNodesResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetUserAccessibleNodesResponseDtoResponse) SetFake() {
	{
		{
			s.UserUuid = uuid.New()
		}
	}
	{
		{
			s.ActiveNodes = nil
			for i := 0; i < 0; i++ {
				var elem GetUserAccessibleNodesResponseDtoResponseActiveNodesItem
				{
					elem.SetFake()
				}
				s.ActiveNodes = append(s.ActiveNodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetUserAccessibleNodesResponseDtoResponseActiveNodesItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
	{
		{
			s.ConfigProfileUuid = uuid.New()
		}
	}
	{
		{
			s.ConfigProfileName = "string"
		}
	}
	{
		{
			s.ActiveSquads = nil
			for i := 0; i < 0; i++ {
				var elem GetUserAccessibleNodesResponseDtoResponseActiveNodesItemActiveSquadsItem
				{
					elem.SetFake()
				}
				s.ActiveSquads = append(s.ActiveSquads, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetUserAccessibleNodesResponseDtoResponseActiveNodesItemActiveSquadsItem) SetFake() {
	{
		{
			s.SquadName = "string"
		}
	}
	{
		{
			s.ActiveInbounds = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.ActiveInbounds = append(s.ActiveInbounds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetUserSubscriptionRequestHistoryResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetUserUsageByRangeResponseDto) SetFake() {
	{
		{
			s.Response = nil
			for i := 0; i < 0; i++ {
				var elem GetUserUsageByRangeResponseDtoResponseItem
				{
					elem.SetFake()
				}
				s.Response = append(s.Response, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetUserUsageByRangeResponseDtoResponseItem) SetFake() {
	{
		{
			s.UserUuid = uuid.New()
		}
	}
	{
		{
			s.NodeUuid = uuid.New()
		}
	}
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Date = "string"
		}
	}
}

// SetFake set fake values.
func (s *Github) SetFake() {
	{
		{
			s.Enabled = true
		}
	}
	{
		{
			s.ClientId.SetFake()
		}
	}
	{
		{
			s.ClientSecret.SetFake()
		}
	}
	{
		{
			s.AllowedEmails = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.AllowedEmails = append(s.AllowedEmails, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HappItem) SetFake() {
	{
		{
			s.CryptoLink = "string"
		}
	}
}

// SetFake set fake values.
func (s *Header) SetFake() {
	{
		{
			s.Key = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *HostItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.ViewPosition = int(0)
		}
	}
	{
		{
			s.Remark = "string"
		}
	}
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Path.SetFake()
		}
	}
	{
		{
			s.Sni.SetFake()
		}
	}
	{
		{
			s.Host.SetFake()
		}
	}
	{
		{
			s.Alpn.SetFake()
		}
	}
	{
		{
			s.Fingerprint.SetFake()
		}
	}
	{
		{
			s.IsDisabled.SetFake()
		}
	}
	{
		{
			s.SecurityLayer.SetFake()
		}
	}
	{
		{
			s.XHttpExtraParams = []byte("null")
		}
	}
	{
		{
			s.MuxParams = []byte("null")
		}
	}
	{
		{
			s.SockoptParams = []byte("null")
		}
	}
	{
		{
			s.Inbound.SetFake()
		}
	}
	{
		{
			s.ServerDescription.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.IsHidden.SetFake()
		}
	}
	{
		{
			s.OverrideSniFromAddress.SetFake()
		}
	}
	{
		{
			s.VlessRouteId.SetFake()
		}
	}
	{
		{
			s.AllowInsecure.SetFake()
		}
	}
	{
		{
			s.ShuffleHost = true
		}
	}
	{
		{
			s.MihomoX25519 = true
		}
	}
	{
		{
			s.Nodes = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Nodes = append(s.Nodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HostItemSecurityLayer) SetFake() {
	*s = HostItemSecurityLayerDEFAULT
}

// SetFake set fake values.
func (s *HostListResponse) SetFake() {
	{
		{
			s.Response = nil
			for i := 0; i < 0; i++ {
				var elem HostItem
				{
					elem.SetFake()
				}
				s.Response = append(s.Response, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HostOverride) SetFake() {
	{
		{
			s.ServerDescription.SetFake()
		}
	}
	{
		{
			s.VlessRouteId.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HostResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HwidDevicesResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Inbound) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.ProfileUuid = uuid.New()
		}
	}
	{
		{
			s.Tag = "string"
		}
	}
	{
		{
			s.Type = "string"
		}
	}
	{
		{
			s.Network.SetFake()
		}
	}
	{
		{
			s.Security.SetFake()
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.RawInbound = []byte("null")
		}
	}
}

// SetFake set fake values.
func (s *InboundItem) SetFake() {
	{
		{
			s.ConfigProfileUuid.SetFake()
		}
	}
	{
		{
			s.ConfigProfileInboundUuid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InboundRef) SetFake() {
	{
		{
			s.ConfigProfileUuid = uuid.New()
		}
	}
	{
		{
			s.ConfigProfileInboundUuid = uuid.New()
		}
	}
}

// SetFake set fake values.
func (s *InboundsResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InboundsResponseResponse) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Inbounds = nil
			for i := 0; i < 0; i++ {
				var elem InboundsResponseResponseInboundsItem
				{
					elem.SetFake()
				}
				s.Inbounds = append(s.Inbounds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *InboundsResponseResponseInboundsItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.ProfileUuid = uuid.New()
		}
	}
	{
		{
			s.Tag = "string"
		}
	}
	{
		{
			s.Type = "string"
		}
	}
	{
		{
			s.Network.SetFake()
		}
	}
	{
		{
			s.Security.SetFake()
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.RawInbound = []byte("null")
		}
	}
	{
		{
			s.ActiveSquads = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.ActiveSquads = append(s.ActiveSquads, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *InboundsStat) SetFake() {
	{
		{
			s.Tag = "string"
		}
	}
	{
		{
			s.Upload = "string"
		}
	}
	{
		{
			s.Download = "string"
		}
	}
}

// SetFake set fake values.
func (s *InfraProviderResponseResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InternalServerError) SetFake() {
	{
		{
			s.Timestamp.SetFake()
		}
	}
	{
		{
			s.Path.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InternalSquad) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Info.SetFake()
		}
	}
	{
		{
			s.Inbounds = nil
			for i := 0; i < 0; i++ {
				var elem Inbound
				{
					elem.SetFake()
				}
				s.Inbounds = append(s.Inbounds, elem)
			}
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *InternalSquadResponseResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InternalSquadsInfoItem) SetFake() {
	{
		{
			s.MembersCount = float64(0)
		}
	}
	{
		{
			s.InboundsCount = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *LastConnectedNodeItem) SetFake() {
	{
		{
			s.ConnectedAt = time.Now()
		}
	}
	{
		{
			s.NodeName = "string"
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
}

// SetFake set fake values.
func (s *LoginRequestDto) SetFake() {
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.Password = "string"
		}
	}
}

// SetFake set fake values.
func (s *NilBrandingSettings) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilDateTime) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilExternalSquadResponseHeaders) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilFloat64) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilGetStatusResponseDtoResponseAuthentication) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilHostOverride) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilInt) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilLastConnectedNodeItem) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilOauth2Settings) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilPasskeySettings) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilPasswordSettings) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilProviderItem) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilString) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilSubscriptionSettings) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilSubscriptionSettingsResponseResponseCustomResponseHeaders) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilTgAuthSettings) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilURI) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilUUID) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *Node) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
}

// SetFake set fake values.
func (s *NodeItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.IsConnected = true
		}
	}
	{
		{
			s.IsDisabled = true
		}
	}
	{
		{
			s.IsConnecting = true
		}
	}
	{
		{
			s.IsNodeOnline = true
		}
	}
	{
		{
			s.IsXrayRunning = true
		}
	}
	{
		{
			s.LastStatusChange.SetFake()
		}
	}
	{
		{
			s.LastStatusMessage.SetFake()
		}
	}
	{
		{
			s.XrayVersion.SetFake()
		}
	}
	{
		{
			s.NodeVersion.SetFake()
		}
	}
	{
		{
			s.XrayUptime = "string"
		}
	}
	{
		{
			s.IsTrafficTrackingActive = true
		}
	}
	{
		{
			s.TrafficResetDay.SetFake()
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.TrafficUsedBytes.SetFake()
		}
	}
	{
		{
			s.NotifyPercent.SetFake()
		}
	}
	{
		{
			s.UsersOnline.SetFake()
		}
	}
	{
		{
			s.ViewPosition = int(0)
		}
	}
	{
		{
			s.CountryCode = "string"
		}
	}
	{
		{
			s.ConsumptionMultiplier = float64(0)
		}
	}
	{
		{
			s.CpuCount.SetFake()
		}
	}
	{
		{
			s.CpuModel.SetFake()
		}
	}
	{
		{
			s.TotalRam.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.ConfigProfile.SetFake()
		}
	}
	{
		{
			s.ProviderUuid.SetFake()
		}
	}
	{
		{
			s.Provider.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NodeRef) SetFake() {
	{
		{
			s.ViewPosition = int(0)
		}
	}
	{
		{
			s.UUID = uuid.New()
		}
	}
}

// SetFake set fake values.
func (s *NodeResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NodesResponse) SetFake() {
	{
		{
			s.Response = nil
			for i := 0; i < 0; i++ {
				var elem NodeItem
				{
					elem.SetFake()
				}
				s.Response = append(s.Response, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NotFoundError) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
	{
		{
			s.StatusCode = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *OAuth2AuthorizeRequestDto) SetFake() {
	{
		{
			s.Provider.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OAuth2AuthorizeRequestDtoProvider) SetFake() {
	*s = OAuth2AuthorizeRequestDtoProviderGithub
}

// SetFake set fake values.
func (s *OAuth2AuthorizeResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OAuth2AuthorizeResponseDtoResponse) SetFake() {
	{
		{
			s.AuthorizationUrl.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OAuth2CallbackRequestDto) SetFake() {
	{
		{
			s.Provider.SetFake()
		}
	}
	{
		{
			s.Code = "string"
		}
	}
	{
		{
			s.State = "string"
		}
	}
}

// SetFake set fake values.
func (s *OAuth2CallbackRequestDtoProvider) SetFake() {
	*s = OAuth2CallbackRequestDtoProviderGithub
}

// SetFake set fake values.
func (s *Oauth2Settings) SetFake() {
	{
		{
			s.Github.SetFake()
		}
	}
	{
		{
			s.Pocketid.SetFake()
		}
	}
	{
		{
			s.Yandex.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBulkAllUpdateUsersRequestDtoStatus) SetFake() {
	var elem BulkAllUpdateUsersRequestDtoStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBulkAllUpdateUsersRequestDtoTrafficLimitStrategy) SetFake() {
	var elem BulkAllUpdateUsersRequestDtoTrafficLimitStrategy
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBulkDeleteUsersByStatusRequestDtoStatus) SetFake() {
	var elem BulkDeleteUsersByStatusRequestDtoStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBulkUpdateUsersRequestDtoFieldsStatus) SetFake() {
	var elem BulkUpdateUsersRequestDtoFieldsStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBulkUpdateUsersRequestDtoFieldsTrafficLimitStrategy) SetFake() {
	var elem BulkUpdateUsersRequestDtoFieldsTrafficLimitStrategy
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptConfigProfileRef) SetFake() {
	var elem ConfigProfileRef
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateHostRequestDtoSecurityLayer) SetFake() {
	var elem CreateHostRequestDtoSecurityLayer
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateUserRequestDtoStatus) SetFake() {
	var elem CreateUserRequestDtoStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateUserRequestDtoTrafficLimitStrategy) SetFake() {
	var elem CreateUserRequestDtoTrafficLimitStrategy
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptFloat64) SetFake() {
	var elem float64
	{
		elem = float64(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptGetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbData) SetFake() {
	var elem GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptGetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemMuxParams) SetFake() {
	var elem *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemMuxParams
	{ // Keep pointer nil to prevent infinite recursion.
		elem = nil
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptGetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemSockoptParams) SetFake() {
	var elem *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemSockoptParams
	{ // Keep pointer nil to prevent infinite recursion.
		elem = nil
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptGetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemXHttpExtraParams) SetFake() {
	var elem *GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemXHttpExtraParams
	{ // Keep pointer nil to prevent infinite recursion.
		elem = nil
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptHostItemSecurityLayer) SetFake() {
	var elem HostItemSecurityLayer
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInboundRef) SetFake() {
	var elem InboundRef
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilBool) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilBrandingSettings) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilCreateHostRequestDtoAlpn) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilCreateHostRequestDtoFingerprint) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilFloat64) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilGetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemAdditionalParams) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilGetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptions) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilGetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptionsSs) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHostOverride) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilInt) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilOauth2Settings) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPasskeySettings) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPasswordSettings) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilString) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilSubscriptionSettings) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilTgAuthSettings) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilURI) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilUUID) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilUpdateExternalSquadRequestDtoResponseHeaders) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilUpdateHostRequestDtoAlpn) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilUpdateHostRequestDtoFingerprint) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptResponseModification) SetFake() {
	var elem ResponseModification
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptResponseRules) SetFake() {
	var elem ResponseRules
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptURI) SetFake() {
	var elem url.URL
	{
		elem = url.URL{Scheme: "https", Host: "github.com", Path: "/ogen-go/ogen"}
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUUID) SetFake() {
	var elem uuid.UUID
	{
		elem = uuid.New()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateHostRequestDtoSecurityLayer) SetFake() {
	var elem UpdateHostRequestDtoSecurityLayer
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateSubscriptionSettingsRequestDtoCustomResponseHeaders) SetFake() {
	var elem UpdateSubscriptionSettingsRequestDtoCustomResponseHeaders
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateUserRequestDtoStatus) SetFake() {
	var elem UpdateUserRequestDtoStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateUserRequestDtoTrafficLimitStrategy) SetFake() {
	var elem UpdateUserRequestDtoTrafficLimitStrategy
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUserStatus) SetFake() {
	var elem UserStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUserTrafficLimitStrategy) SetFake() {
	var elem UserTrafficLimitStrategy
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *PasskeyOptions) SetFake() {
	{
		{
			s.Response = []byte("null")
		}
	}
}

// SetFake set fake values.
func (s *PasskeySettings) SetFake() {
	{
		{
			s.Enabled = true
		}
	}
	{
		{
			s.RpId.SetFake()
		}
	}
	{
		{
			s.Origin.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PasskeysResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PasskeysResponseResponse) SetFake() {
	{
		{
			s.Passkeys = nil
			for i := 0; i < 0; i++ {
				var elem PasskeysResponseResponsePasskeysItem
				{
					elem.SetFake()
				}
				s.Passkeys = append(s.Passkeys, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PasskeysResponseResponsePasskeysItem) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.LastUsedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *PasswordSettings) SetFake() {
	{
		{
			s.Enabled = true
		}
	}
}

// SetFake set fake values.
func (s *Pocketid) SetFake() {
	{
		{
			s.Enabled = true
		}
	}
	{
		{
			s.ClientId.SetFake()
		}
	}
	{
		{
			s.ClientSecret.SetFake()
		}
	}
	{
		{
			s.PlainDomain.SetFake()
		}
	}
	{
		{
			s.AllowedEmails = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.AllowedEmails = append(s.AllowedEmails, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *Provider) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.FaviconLink.SetFake()
		}
	}
	{
		{
			s.LoginUrl.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.BillingHistory.SetFake()
		}
	}
	{
		{
			s.BillingNodes = nil
			for i := 0; i < 0; i++ {
				var elem BillingNode
				{
					elem.SetFake()
				}
				s.BillingNodes = append(s.BillingNodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ProviderItem) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.FaviconLink.SetFake()
		}
	}
	{
		{
			s.LoginUrl.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *Record) SetFake() {
	{
		{
			s.ID = float64(0)
		}
	}
	{
		{
			s.UserUuid = uuid.New()
		}
	}
	{
		{
			s.RequestAt = time.Now()
		}
	}
	{
		{
			s.RequestIp.SetFake()
		}
	}
	{
		{
			s.UserAgent.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *RegisterRequestDto) SetFake() {
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.Password = "string"
		}
	}
}

// SetFake set fake values.
func (s *ReorderHostRequestDto) SetFake() {
	{
		{
			s.Hosts = nil
			for i := 0; i < 0; i++ {
				var elem NodeRef
				{
					elem.SetFake()
				}
				s.Hosts = append(s.Hosts, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ReorderHostResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ReorderHostResponseDtoResponse) SetFake() {
	{
		{
			s.IsUpdated = true
		}
	}
}

// SetFake set fake values.
func (s *ReorderNodeRequestDto) SetFake() {
	{
		{
			s.Nodes = nil
			for i := 0; i < 0; i++ {
				var elem NodeRef
				{
					elem.SetFake()
				}
				s.Nodes = append(s.Nodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ResponseModification) SetFake() {
	{
		{
			s.Headers = nil
			for i := 0; i < 0; i++ {
				var elem Header
				{
					elem.SetFake()
				}
				s.Headers = append(s.Headers, elem)
			}
		}
	}
	{
		{
			s.SubscriptionTemplate.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ResponseRules) SetFake() {
	{
		{
			s.Version.SetFake()
		}
	}
	{
		{
			s.Rules = nil
			for i := 0; i < 0; i++ {
				var elem Rule
				{
					elem.SetFake()
				}
				s.Rules = append(s.Rules, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ResponseRulesVersion) SetFake() {
	*s = ResponseRulesVersion1
}

// SetFake set fake values.
func (s *RestartAllNodesRequestBodyDto) SetFake() {
	{
		{
			s.ForceRestart.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *RevokeUserSubscriptionBodyDto) SetFake() {
	{
		{
			s.ShortUuid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Rule) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Enabled = true
		}
	}
	{
		{
			s.Operator.SetFake()
		}
	}
	{
		{
			s.Conditions = nil
			for i := 0; i < 0; i++ {
				var elem Condition
				{
					elem.SetFake()
				}
				s.Conditions = append(s.Conditions, elem)
			}
		}
	}
	{
		{
			s.ResponseType.SetFake()
		}
	}
	{
		{
			s.ResponseModifications.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *RuleOperator) SetFake() {
	*s = RuleOperatorAND
}

// SetFake set fake values.
func (s *RuleResponseType) SetFake() {
	*s = RuleResponseTypeXRAYJSON
}

// SetFake set fake values.
func (s *SetInboundToManyHostsRequestDto) SetFake() {
	{
		{
			s.Uuids = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Uuids = append(s.Uuids, elem)
			}
		}
	}
	{
		{
			s.ConfigProfileUuid = uuid.New()
		}
	}
	{
		{
			s.ConfigProfileInboundUuid = uuid.New()
		}
	}
}

// SetFake set fake values.
func (s *SetPortToManyHostsRequestDto) SetFake() {
	{
		{
			s.Uuids = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Uuids = append(s.Uuids, elem)
			}
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
}

// SetFake set fake values.
func (s *SettingsResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SettingsResponseResponse) SetFake() {
	{
		{
			s.PasskeySettings.SetFake()
		}
	}
	{
		{
			s.Oauth2Settings.SetFake()
		}
	}
	{
		{
			s.TgAuthSettings.SetFake()
		}
	}
	{
		{
			s.PasswordSettings.SetFake()
		}
	}
	{
		{
			s.BrandingSettings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SnippetRequest) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Snippet = nil
			for i := 0; i < 0; i++ {
				var elem SnippetRequestSnippetItem
				{
					elem.SetFake()
				}
				s.Snippet = append(s.Snippet, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *SnippetRequestSnippetItem) SetFake() {
}

// SetFake set fake values.
func (s *SnippetsResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SnippetsResponseResponse) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Snippets = nil
			for i := 0; i < 0; i++ {
				var elem SnippetsResponseResponseSnippetsItem
				{
					elem.SetFake()
				}
				s.Snippets = append(s.Snippets, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *SnippetsResponseResponseSnippetsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Snippet = []byte("null")
		}
	}
}

// SetFake set fake values.
func (s *SubscriptionResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SubscriptionResponseResponse) SetFake() {
	{
		{
			s.IsFound = true
		}
	}
	{
		{
			s.User.SetFake()
		}
	}
	{
		{
			s.Links = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Links = append(s.Links, elem)
			}
		}
	}
	{
		{
			s.SsConfLinks.SetFake()
		}
	}
	{
		{
			s.SubscriptionUrl = "string"
		}
	}
	{
		{
			s.Happ.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SubscriptionResponseResponseSsConfLinks) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *SubscriptionResponseResponseUser) SetFake() {
	{
		{
			s.ShortUuid = "string"
		}
	}
	{
		{
			s.DaysLeft = float64(0)
		}
	}
	{
		{
			s.TrafficUsed = "string"
		}
	}
	{
		{
			s.TrafficLimit = "string"
		}
	}
	{
		{
			s.LifetimeTrafficUsed = "string"
		}
	}
	{
		{
			s.TrafficUsedBytes = "string"
		}
	}
	{
		{
			s.TrafficLimitBytes = "string"
		}
	}
	{
		{
			s.LifetimeTrafficUsedBytes = "string"
		}
	}
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.ExpiresAt = time.Now()
		}
	}
	{
		{
			s.IsActive = true
		}
	}
	{
		{
			s.UserStatus.SetFake()
		}
	}
	{
		{
			s.TrafficLimitStrategy.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SubscriptionResponseResponseUserTrafficLimitStrategy) SetFake() {
	*s = SubscriptionResponseResponseUserTrafficLimitStrategyNORESET
}

// SetFake set fake values.
func (s *SubscriptionResponseResponseUserUserStatus) SetFake() {
	*s = SubscriptionResponseResponseUserUserStatusACTIVE
}

// SetFake set fake values.
func (s *SubscriptionSettings) SetFake() {
	{
		{
			s.ProfileTitle.SetFake()
		}
	}
	{
		{
			s.SupportLink.SetFake()
		}
	}
	{
		{
			s.ProfileUpdateInterval.SetFake()
		}
	}
	{
		{
			s.IsProfileWebpageUrlEnabled.SetFake()
		}
	}
	{
		{
			s.ServeJsonAtBaseSubscription.SetFake()
		}
	}
	{
		{
			s.AddUsernameToBaseSubscription.SetFake()
		}
	}
	{
		{
			s.IsShowCustomRemarks.SetFake()
		}
	}
	{
		{
			s.HappAnnounce.SetFake()
		}
	}
	{
		{
			s.HappRouting.SetFake()
		}
	}
	{
		{
			s.RandomizeHosts.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SubscriptionSettingsResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SubscriptionSettingsResponseResponse) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.ProfileTitle = "string"
		}
	}
	{
		{
			s.SupportLink = "string"
		}
	}
	{
		{
			s.ProfileUpdateInterval = int(0)
		}
	}
	{
		{
			s.IsProfileWebpageUrlEnabled = true
		}
	}
	{
		{
			s.ServeJsonAtBaseSubscription = true
		}
	}
	{
		{
			s.AddUsernameToBaseSubscription = true
		}
	}
	{
		{
			s.IsShowCustomRemarks = true
		}
	}
	{
		{
			s.HappAnnounce.SetFake()
		}
	}
	{
		{
			s.HappRouting.SetFake()
		}
	}
	{
		{
			s.ExpiredUsersRemarks = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.ExpiredUsersRemarks = append(s.ExpiredUsersRemarks, elem)
			}
		}
	}
	{
		{
			s.LimitedUsersRemarks = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.LimitedUsersRemarks = append(s.LimitedUsersRemarks, elem)
			}
		}
	}
	{
		{
			s.DisabledUsersRemarks = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.DisabledUsersRemarks = append(s.DisabledUsersRemarks, elem)
			}
		}
	}
	{
		{
			s.CustomResponseHeaders.SetFake()
		}
	}
	{
		{
			s.RandomizeHosts = true
		}
	}
	{
		{
			s.ResponseRules.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *SubscriptionSettingsResponseResponseCustomResponseHeaders) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *TagsResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TagsResponseResponse) SetFake() {
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *TelegramCallbackRequestDto) SetFake() {
	{
		{
			s.ID = float64(0)
		}
	}
	{
		{
			s.FirstName = "string"
		}
	}
	{
		{
			s.LastName.SetFake()
		}
	}
	{
		{
			s.Username.SetFake()
		}
	}
	{
		{
			s.PhotoURL.SetFake()
		}
	}
	{
		{
			s.AuthDate = float64(0)
		}
	}
	{
		{
			s.Hash = "string"
		}
	}
}

// SetFake set fake values.
func (s *Template) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.TemplateType.SetFake()
		}
	}
	{
		{
			s.TemplateJson = []byte("null")
		}
	}
	{
		{
			s.EncodedTemplateYaml.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TemplateRef) SetFake() {
	{
		{
			s.TemplateUuid = uuid.New()
		}
	}
	{
		{
			s.TemplateType.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TemplateRefTemplateType) SetFake() {
	*s = TemplateRefTemplateTypeXRAYJSON
}

// SetFake set fake values.
func (s *TemplateResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TemplateTemplateType) SetFake() {
	*s = TemplateTemplateTypeXRAYJSON
}

// SetFake set fake values.
func (s *TgAuthSettings) SetFake() {
	{
		{
			s.Enabled = true
		}
	}
	{
		{
			s.BotToken.SetFake()
		}
	}
	{
		{
			s.AdminIds = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.AdminIds = append(s.AdminIds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *TokenResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TokenResponseResponse) SetFake() {
	{
		{
			s.AccessToken = "string"
		}
	}
}

// SetFake set fake values.
func (s *UnauthorizedError) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
	{
		{
			s.StatusCode = float64(0)
		}
	}
}

// SetFake set fake values.
func (s *UpdateConfigProfileRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{ // Keep pointer nil to prevent infinite recursion.
			s.Config = nil
		}
	}
}

// SetFake set fake values.
func (s *UpdateConfigProfileRequestDtoConfig) SetFake() {
}

// SetFake set fake values.
func (s *UpdateExternalSquadRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Templates = nil
			for i := 0; i < 0; i++ {
				var elem TemplateRef
				{
					elem.SetFake()
				}
				s.Templates = append(s.Templates, elem)
			}
		}
	}
	{
		{
			s.SubscriptionSettings.SetFake()
		}
	}
	{
		{
			s.HostOverrides.SetFake()
		}
	}
	{
		{
			s.ResponseHeaders.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateExternalSquadRequestDtoResponseHeaders) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *UpdateHostRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Inbound.SetFake()
		}
	}
	{
		{
			s.Remark.SetFake()
		}
	}
	{
		{
			s.Address.SetFake()
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.Path.SetFake()
		}
	}
	{
		{
			s.Sni.SetFake()
		}
	}
	{
		{
			s.Host.SetFake()
		}
	}
	{
		{
			s.Alpn.SetFake()
		}
	}
	{
		{
			s.Fingerprint.SetFake()
		}
	}
	{
		{
			s.IsDisabled.SetFake()
		}
	}
	{
		{
			s.SecurityLayer.SetFake()
		}
	}
	{
		{
			s.XHttpExtraParams = []byte("null")
		}
	}
	{
		{
			s.MuxParams = []byte("null")
		}
	}
	{
		{
			s.SockoptParams = []byte("null")
		}
	}
	{
		{
			s.ServerDescription.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.IsHidden.SetFake()
		}
	}
	{
		{
			s.OverrideSniFromAddress.SetFake()
		}
	}
	{
		{
			s.VlessRouteId.SetFake()
		}
	}
	{
		{
			s.AllowInsecure.SetFake()
		}
	}
	{
		{
			s.ShuffleHost.SetFake()
		}
	}
	{
		{
			s.MihomoX25519.SetFake()
		}
	}
	{
		{
			s.Nodes = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Nodes = append(s.Nodes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *UpdateHostRequestDtoAlpn) SetFake() {
	*s = UpdateHostRequestDtoAlpnH3
}

// SetFake set fake values.
func (s *UpdateHostRequestDtoFingerprint) SetFake() {
	*s = UpdateHostRequestDtoFingerprintChrome
}

// SetFake set fake values.
func (s *UpdateHostRequestDtoSecurityLayer) SetFake() {
	*s = UpdateHostRequestDtoSecurityLayerDEFAULT
}

// SetFake set fake values.
func (s *UpdateInfraBillingNodeRequestDto) SetFake() {
	{
		{
			s.Uuids = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Uuids = append(s.Uuids, elem)
			}
		}
	}
	{
		{
			s.NextBillingAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *UpdateInfraProviderRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.FaviconLink.SetFake()
		}
	}
	{
		{
			s.LoginUrl.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateInternalSquadRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Inbounds = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.Inbounds = append(s.Inbounds, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *UpdateNodeRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Address.SetFake()
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.IsTrafficTrackingActive.SetFake()
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.NotifyPercent.SetFake()
		}
	}
	{
		{
			s.TrafficResetDay.SetFake()
		}
	}
	{
		{
			s.CountryCode.SetFake()
		}
	}
	{
		{
			s.ConsumptionMultiplier.SetFake()
		}
	}
	{
		{
			s.ConfigProfile.SetFake()
		}
	}
	{
		{
			s.ProviderUuid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateRemnawaveSettingsRequestDto) SetFake() {
	{
		{
			s.PasskeySettings.SetFake()
		}
	}
	{
		{
			s.Oauth2Settings.SetFake()
		}
	}
	{
		{
			s.TgAuthSettings.SetFake()
		}
	}
	{
		{
			s.PasswordSettings.SetFake()
		}
	}
	{
		{
			s.BrandingSettings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateSubscriptionSettingsRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.ProfileTitle.SetFake()
		}
	}
	{
		{
			s.SupportLink.SetFake()
		}
	}
	{
		{
			s.ProfileUpdateInterval.SetFake()
		}
	}
	{
		{
			s.IsProfileWebpageUrlEnabled.SetFake()
		}
	}
	{
		{
			s.ServeJsonAtBaseSubscription.SetFake()
		}
	}
	{
		{
			s.AddUsernameToBaseSubscription.SetFake()
		}
	}
	{
		{
			s.IsShowCustomRemarks.SetFake()
		}
	}
	{
		{
			s.HappAnnounce.SetFake()
		}
	}
	{
		{
			s.HappRouting.SetFake()
		}
	}
	{
		{
			s.ExpiredUsersRemarks = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.ExpiredUsersRemarks = append(s.ExpiredUsersRemarks, elem)
			}
		}
	}
	{
		{
			s.LimitedUsersRemarks = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.LimitedUsersRemarks = append(s.LimitedUsersRemarks, elem)
			}
		}
	}
	{
		{
			s.DisabledUsersRemarks = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.DisabledUsersRemarks = append(s.DisabledUsersRemarks, elem)
			}
		}
	}
	{
		{
			s.CustomResponseHeaders.SetFake()
		}
	}
	{
		{
			s.RandomizeHosts.SetFake()
		}
	}
	{
		{
			s.ResponseRules.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateSubscriptionSettingsRequestDtoCustomResponseHeaders) SetFake() {
	var (
		elem string
		m    map[string]string = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *UpdateTemplateRequestDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{ // Keep pointer nil to prevent infinite recursion.
			s.TemplateJson = nil
		}
	}
	{
		{
			s.EncodedTemplateYaml.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateTemplateRequestDtoTemplateJson) SetFake() {
}

// SetFake set fake values.
func (s *UpdateUserRequestDto) SetFake() {
	{
		{
			s.Username.SetFake()
		}
	}
	{
		{
			s.UUID.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.TrafficLimitStrategy.SetFake()
		}
	}
	{
		{
			s.ExpireAt.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.TelegramId.SetFake()
		}
	}
	{
		{
			s.Email.SetFake()
		}
	}
	{
		{
			s.HwidDeviceLimit.SetFake()
		}
	}
	{
		{
			s.ActiveInternalSquads = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.ActiveInternalSquads = append(s.ActiveInternalSquads, elem)
			}
		}
	}
	{
		{
			s.ExternalSquadUuid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateUserRequestDtoStatus) SetFake() {
	*s = UpdateUserRequestDtoStatusACTIVE
}

// SetFake set fake values.
func (s *UpdateUserRequestDtoTrafficLimitStrategy) SetFake() {
	*s = UpdateUserRequestDtoTrafficLimitStrategyNORESET
}

// SetFake set fake values.
func (s *User) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.ShortUuid = "string"
		}
	}
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.UsedTrafficBytes = float64(0)
		}
	}
	{
		{
			s.LifetimeUsedTrafficBytes = float64(0)
		}
	}
	{
		{
			s.TrafficLimitBytes.SetFake()
		}
	}
	{
		{
			s.TrafficLimitStrategy.SetFake()
		}
	}
	{
		{
			s.SubLastUserAgent.SetFake()
		}
	}
	{
		{
			s.SubLastOpenedAt.SetFake()
		}
	}
	{
		{
			s.ExpireAt = time.Now()
		}
	}
	{
		{
			s.OnlineAt.SetFake()
		}
	}
	{
		{
			s.SubRevokedAt.SetFake()
		}
	}
	{
		{
			s.LastTrafficResetAt.SetFake()
		}
	}
	{
		{
			s.TrojanPassword = "string"
		}
	}
	{
		{
			s.VlessUuid = uuid.New()
		}
	}
	{
		{
			s.SsPassword = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tag.SetFake()
		}
	}
	{
		{
			s.TelegramId.SetFake()
		}
	}
	{
		{
			s.Email.SetFake()
		}
	}
	{
		{
			s.HwidDeviceLimit.SetFake()
		}
	}
	{
		{
			s.FirstConnectedAt.SetFake()
		}
	}
	{
		{
			s.LastTriggeredThreshold.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.ActiveInternalSquads = nil
			for i := 0; i < 0; i++ {
				var elem ActiveInternalSquad
				{
					elem.SetFake()
				}
				s.ActiveInternalSquads = append(s.ActiveInternalSquads, elem)
			}
		}
	}
	{
		{
			s.ExternalSquadUuid.SetFake()
		}
	}
	{
		{
			s.SubscriptionUrl = "string"
		}
	}
	{
		{
			s.LastConnectedNode.SetFake()
		}
	}
	{
		{
			s.Happ.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UserResponse) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UserStatus) SetFake() {
	*s = UserStatusACTIVE
}

// SetFake set fake values.
func (s *UserSubscriptionHistory) SetFake() {
	{
		{
			s.Total = float64(0)
		}
	}
	{
		{
			s.Records = nil
			for i := 0; i < 0; i++ {
				var elem Record
				{
					elem.SetFake()
				}
				s.Records = append(s.Records, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *UserTrafficLimitStrategy) SetFake() {
	*s = UserTrafficLimitStrategyNORESET
}

// SetFake set fake values.
func (s *UsersResponse) SetFake() {
	{
		{
			s.Response = nil
			for i := 0; i < 0; i++ {
				var elem User
				{
					elem.SetFake()
				}
				s.Response = append(s.Response, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ValidationError) SetFake() {
	{
		{
			s.Validation = "string"
		}
	}
	{
		{
			s.Code = "string"
		}
	}
	{
		{
			s.Message = "string"
		}
	}
	{
		{
			s.Path = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Path = append(s.Path, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *VerifyPasskeyRegistrationResponseDto) SetFake() {
	{
		{
			s.Response.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *VerifyPasskeyRegistrationResponseDtoResponse) SetFake() {
	{
		{
			s.Verified = true
		}
	}
}
