// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Authorization provides Authorization security value.
	// JWT obtained login.
	Authorization(ctx context.Context, operationName OperationName) (Authorization, error)
}

// operationRolesAuthorization is a private map storing roles per operation.
var operationRolesAuthorization = map[string][]string{
	ApiTokensControllerCreateOperation:                                                  []string{},
	ApiTokensControllerDeleteOperation:                                                  []string{},
	ApiTokensControllerFindAllOperation:                                                 []string{},
	BandwidthStatsNodesControllerGetNodeUserUsageOperation:                              []string{},
	BandwidthStatsNodesControllerGetNodesRealtimeUsageOperation:                         []string{},
	BandwidthStatsNodesControllerGetStatsNodeUsersUsageOperation:                        []string{},
	BandwidthStatsUsersControllerGetStatsNodesUsageOperation:                            []string{},
	BandwidthStatsUsersControllerGetUserUsageByRangeOperation:                           []string{},
	ConfigProfileControllerCreateConfigProfileOperation:                                 []string{},
	ConfigProfileControllerDeleteConfigProfileByUuidOperation:                           []string{},
	ConfigProfileControllerGetAllInboundsOperation:                                      []string{},
	ConfigProfileControllerGetComputedConfigProfileByUuidOperation:                      []string{},
	ConfigProfileControllerGetConfigProfileByUuidOperation:                              []string{},
	ConfigProfileControllerGetConfigProfilesOperation:                                   []string{},
	ConfigProfileControllerGetInboundsByProfileUuidOperation:                            []string{},
	ConfigProfileControllerReorderConfigProfilesOperation:                               []string{},
	ConfigProfileControllerUpdateConfigProfileOperation:                                 []string{},
	ExternalSquadControllerAddUsersToExternalSquadOperation:                             []string{},
	ExternalSquadControllerCreateExternalSquadOperation:                                 []string{},
	ExternalSquadControllerDeleteExternalSquadOperation:                                 []string{},
	ExternalSquadControllerGetExternalSquadByUuidOperation:                              []string{},
	ExternalSquadControllerGetExternalSquadsOperation:                                   []string{},
	ExternalSquadControllerRemoveUsersFromExternalSquadOperation:                        []string{},
	ExternalSquadControllerReorderExternalSquadsOperation:                               []string{},
	ExternalSquadControllerUpdateExternalSquadOperation:                                 []string{},
	HostsBulkActionsControllerDeleteHostsOperation:                                      []string{},
	HostsBulkActionsControllerDisableHostsOperation:                                     []string{},
	HostsBulkActionsControllerEnableHostsOperation:                                      []string{},
	HostsBulkActionsControllerSetInboundToHostsOperation:                                []string{},
	HostsBulkActionsControllerSetPortToHostsOperation:                                   []string{},
	HostsControllerCreateHostOperation:                                                  []string{},
	HostsControllerDeleteHostOperation:                                                  []string{},
	HostsControllerGetAllHostTagsOperation:                                              []string{},
	HostsControllerGetAllHostsOperation:                                                 []string{},
	HostsControllerGetOneHostOperation:                                                  []string{},
	HostsControllerReorderHostsOperation:                                                []string{},
	HostsControllerUpdateHostOperation:                                                  []string{},
	HwidUserDevicesControllerCreateUserHwidDeviceOperation:                              []string{},
	HwidUserDevicesControllerDeleteAllUserHwidDevicesOperation:                          []string{},
	HwidUserDevicesControllerDeleteUserHwidDeviceOperation:                              []string{},
	HwidUserDevicesControllerGetAllUsersOperation:                                       []string{},
	HwidUserDevicesControllerGetHwidDevicesStatsOperation:                               []string{},
	HwidUserDevicesControllerGetTopUsersByHwidDevicesOperation:                          []string{},
	HwidUserDevicesControllerGetUserHwidDevicesOperation:                                []string{},
	InfraBillingControllerCreateInfraBillingHistoryRecordOperation:                      []string{},
	InfraBillingControllerCreateInfraBillingNodeOperation:                               []string{},
	InfraBillingControllerCreateInfraProviderOperation:                                  []string{},
	InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidOperation:                []string{},
	InfraBillingControllerDeleteInfraBillingNodeByUuidOperation:                         []string{},
	InfraBillingControllerDeleteInfraProviderByUuidOperation:                            []string{},
	InfraBillingControllerGetBillingNodesOperation:                                      []string{},
	InfraBillingControllerGetInfraBillingHistoryRecordsOperation:                        []string{},
	InfraBillingControllerGetInfraProviderByUuidOperation:                               []string{},
	InfraBillingControllerGetInfraProvidersOperation:                                    []string{},
	InfraBillingControllerUpdateInfraBillingNodeOperation:                               []string{},
	InfraBillingControllerUpdateInfraProviderOperation:                                  []string{},
	InternalSquadControllerAddUsersToInternalSquadOperation:                             []string{},
	InternalSquadControllerCreateInternalSquadOperation:                                 []string{},
	InternalSquadControllerDeleteInternalSquadOperation:                                 []string{},
	InternalSquadControllerGetInternalSquadAccessibleNodesOperation:                     []string{},
	InternalSquadControllerGetInternalSquadByUuidOperation:                              []string{},
	InternalSquadControllerGetInternalSquadsOperation:                                   []string{},
	InternalSquadControllerRemoveUsersFromInternalSquadOperation:                        []string{},
	InternalSquadControllerReorderInternalSquadsOperation:                               []string{},
	InternalSquadControllerUpdateInternalSquadOperation:                                 []string{},
	KeygenControllerGenerateKeyOperation:                                                []string{},
	NodesControllerBulkNodesActionsOperation:                                            []string{},
	NodesControllerCreateNodeOperation:                                                  []string{},
	NodesControllerDeleteNodeOperation:                                                  []string{},
	NodesControllerDisableNodeOperation:                                                 []string{},
	NodesControllerEnableNodeOperation:                                                  []string{},
	NodesControllerGetAllNodesOperation:                                                 []string{},
	NodesControllerGetAllNodesTagsOperation:                                             []string{},
	NodesControllerGetOneNodeOperation:                                                  []string{},
	NodesControllerProfileModificationOperation:                                         []string{},
	NodesControllerReorderNodesOperation:                                                []string{},
	NodesControllerResetNodeTrafficOperation:                                            []string{},
	NodesControllerRestartAllNodesOperation:                                             []string{},
	NodesControllerRestartNodeOperation:                                                 []string{},
	NodesControllerUpdateNodeOperation:                                                  []string{},
	NodesUsageHistoryControllerGetStatsNodesUsageOperation:                              []string{},
	PasskeyControllerDeletePasskeyOperation:                                             []string{},
	PasskeyControllerGetActivePasskeysOperation:                                         []string{},
	PasskeyControllerPasskeyRegistrationOptionsOperation:                                []string{},
	PasskeyControllerPasskeyRegistrationVerifyOperation:                                 []string{},
	PasskeyControllerUpdatePasskeyOperation:                                             []string{},
	RemnawaveSettingsControllerGetSettingsOperation:                                     []string{},
	RemnawaveSettingsControllerUpdateSettingsOperation:                                  []string{},
	SnippetsControllerCreateSnippetOperation:                                            []string{},
	SnippetsControllerDeleteSnippetByNameOperation:                                      []string{},
	SnippetsControllerGetSnippetsOperation:                                              []string{},
	SnippetsControllerUpdateSnippetOperation:                                            []string{},
	SubscriptionPageConfigControllerCloneSubscriptionPageConfigOperation:                []string{},
	SubscriptionPageConfigControllerCreateConfigOperation:                               []string{},
	SubscriptionPageConfigControllerDeleteConfigOperation:                               []string{},
	SubscriptionPageConfigControllerGetAllConfigsOperation:                              []string{},
	SubscriptionPageConfigControllerGetConfigByUuidOperation:                            []string{},
	SubscriptionPageConfigControllerReorderSubscriptionPageConfigsOperation:             []string{},
	SubscriptionPageConfigControllerUpdateConfigOperation:                               []string{},
	SubscriptionSettingsControllerGetSettingsOperation:                                  []string{},
	SubscriptionSettingsControllerUpdateSettingsOperation:                               []string{},
	SubscriptionTemplateControllerCreateTemplateOperation:                               []string{},
	SubscriptionTemplateControllerDeleteTemplateOperation:                               []string{},
	SubscriptionTemplateControllerGetAllTemplatesOperation:                              []string{},
	SubscriptionTemplateControllerGetTemplateByUuidOperation:                            []string{},
	SubscriptionTemplateControllerReorderSubscriptionTemplatesOperation:                 []string{},
	SubscriptionTemplateControllerUpdateTemplateOperation:                               []string{},
	SubscriptionsControllerGetAllSubscriptionsOperation:                                 []string{},
	SubscriptionsControllerGetRawSubscriptionByShortUuidOperation:                       []string{},
	SubscriptionsControllerGetSubpageConfigByShortUuidOperation:                         []string{},
	SubscriptionsControllerGetSubscriptionByShortUuidProtectedOperation:                 []string{},
	SubscriptionsControllerGetSubscriptionByUsernameOperation:                           []string{},
	SubscriptionsControllerGetSubscriptionByUuidOperation:                               []string{},
	SystemControllerDebugSrrMatcherOperation:                                            []string{},
	SystemControllerEncryptHappCryptoLinkOperation:                                      []string{},
	SystemControllerGetBandwidthStatsOperation:                                          []string{},
	SystemControllerGetMetadataOperation:                                                []string{},
	SystemControllerGetNodesMetricsOperation:                                            []string{},
	SystemControllerGetNodesStatisticsOperation:                                         []string{},
	SystemControllerGetRemnawaveHealthOperation:                                         []string{},
	SystemControllerGetStatsOperation:                                                   []string{},
	SystemControllerGetX25519KeypairsOperation:                                          []string{},
	UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryOperation:      []string{},
	UserSubscriptionRequestHistoryControllerGetSubscriptionRequestHistoryStatsOperation: []string{},
	UsersBulkActionsControllerBulkAllExtendExpirationDateOperation:                      []string{},
	UsersBulkActionsControllerBulkAllResetUserTrafficOperation:                          []string{},
	UsersBulkActionsControllerBulkDeleteUsersOperation:                                  []string{},
	UsersBulkActionsControllerBulkDeleteUsersByStatusOperation:                          []string{},
	UsersBulkActionsControllerBulkExtendExpirationDateOperation:                         []string{},
	UsersBulkActionsControllerBulkResetUserTrafficOperation:                             []string{},
	UsersBulkActionsControllerBulkRevokeUsersSubscriptionOperation:                      []string{},
	UsersBulkActionsControllerBulkUpdateAllUsersOperation:                               []string{},
	UsersBulkActionsControllerBulkUpdateUsersOperation:                                  []string{},
	UsersBulkActionsControllerBulkUpdateUsersInternalSquadsOperation:                    []string{},
	UsersControllerCreateUserOperation:                                                  []string{},
	UsersControllerDeleteUserOperation:                                                  []string{},
	UsersControllerDisableUserOperation:                                                 []string{},
	UsersControllerEnableUserOperation:                                                  []string{},
	UsersControllerGetAllTagsOperation:                                                  []string{},
	UsersControllerGetAllUsersOperation:                                                 []string{},
	UsersControllerGetUserAccessibleNodesOperation:                                      []string{},
	UsersControllerGetUserByIdOperation:                                                 []string{},
	UsersControllerGetUserByShortUuidOperation:                                          []string{},
	UsersControllerGetUserByTelegramIdOperation:                                         []string{},
	UsersControllerGetUserByUsernameOperation:                                           []string{},
	UsersControllerGetUserByUuidOperation:                                               []string{},
	UsersControllerGetUserSubscriptionRequestHistoryOperation:                           []string{},
	UsersControllerGetUsersByEmailOperation:                                             []string{},
	UsersControllerGetUsersByTagOperation:                                               []string{},
	UsersControllerResetUserTrafficOperation:                                            []string{},
	UsersControllerRevokeUserSubscriptionOperation:                                      []string{},
	UsersControllerUpdateUserOperation:                                                  []string{},
}

// GetRolesForAuthorization returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAuthorization(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAuthorization(operation string) []string {
	roles, ok := operationRolesAuthorization[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityAuthorization(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Authorization(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Authorization\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
